// Code generated by go-swagger; DO NOT EDIT.

package rbac_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/groundcover-com/groundcover-sdk-go/pkg/models"
)

// UpdateTenantAISettingsReader is a Reader for the UpdateTenantAISettings structure.
type UpdateTenantAISettingsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateTenantAISettingsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateTenantAISettingsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUpdateTenantAISettingsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewUpdateTenantAISettingsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /api/rbac/v2/tenant/ai-settings] updateTenantAISettings", response, response.Code())
	}
}

// NewUpdateTenantAISettingsOK creates a UpdateTenantAISettingsOK with default headers values
func NewUpdateTenantAISettingsOK() *UpdateTenantAISettingsOK {
	return &UpdateTenantAISettingsOK{}
}

/*
UpdateTenantAISettingsOK describes a response with status code 200, with default header values.

UpdateTenantAISettingsOK update tenant a i settings o k
*/
type UpdateTenantAISettingsOK struct {
	Payload *models.TenantAISettingsResponse
}

// IsSuccess returns true when this update tenant a i settings o k response has a 2xx status code
func (o *UpdateTenantAISettingsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update tenant a i settings o k response has a 3xx status code
func (o *UpdateTenantAISettingsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update tenant a i settings o k response has a 4xx status code
func (o *UpdateTenantAISettingsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this update tenant a i settings o k response has a 5xx status code
func (o *UpdateTenantAISettingsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this update tenant a i settings o k response a status code equal to that given
func (o *UpdateTenantAISettingsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the update tenant a i settings o k response
func (o *UpdateTenantAISettingsOK) Code() int {
	return 200
}

func (o *UpdateTenantAISettingsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/rbac/v2/tenant/ai-settings][%d] updateTenantAISettingsOK %s", 200, payload)
}

func (o *UpdateTenantAISettingsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/rbac/v2/tenant/ai-settings][%d] updateTenantAISettingsOK %s", 200, payload)
}

func (o *UpdateTenantAISettingsOK) GetPayload() *models.TenantAISettingsResponse {
	return o.Payload
}

func (o *UpdateTenantAISettingsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TenantAISettingsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewUpdateTenantAISettingsBadRequest creates a UpdateTenantAISettingsBadRequest with default headers values
func NewUpdateTenantAISettingsBadRequest() *UpdateTenantAISettingsBadRequest {
	return &UpdateTenantAISettingsBadRequest{}
}

/*
UpdateTenantAISettingsBadRequest describes a response with status code 400, with default header values.

ErrorResponse defines a common error response structure.
*/
type UpdateTenantAISettingsBadRequest struct {
	Payload *UpdateTenantAISettingsBadRequestBody
}

// IsSuccess returns true when this update tenant a i settings bad request response has a 2xx status code
func (o *UpdateTenantAISettingsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update tenant a i settings bad request response has a 3xx status code
func (o *UpdateTenantAISettingsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update tenant a i settings bad request response has a 4xx status code
func (o *UpdateTenantAISettingsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this update tenant a i settings bad request response has a 5xx status code
func (o *UpdateTenantAISettingsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this update tenant a i settings bad request response a status code equal to that given
func (o *UpdateTenantAISettingsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the update tenant a i settings bad request response
func (o *UpdateTenantAISettingsBadRequest) Code() int {
	return 400
}

func (o *UpdateTenantAISettingsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/rbac/v2/tenant/ai-settings][%d] updateTenantAISettingsBadRequest %s", 400, payload)
}

func (o *UpdateTenantAISettingsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/rbac/v2/tenant/ai-settings][%d] updateTenantAISettingsBadRequest %s", 400, payload)
}

func (o *UpdateTenantAISettingsBadRequest) GetPayload() *UpdateTenantAISettingsBadRequestBody {
	return o.Payload
}

func (o *UpdateTenantAISettingsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(UpdateTenantAISettingsBadRequestBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewUpdateTenantAISettingsInternalServerError creates a UpdateTenantAISettingsInternalServerError with default headers values
func NewUpdateTenantAISettingsInternalServerError() *UpdateTenantAISettingsInternalServerError {
	return &UpdateTenantAISettingsInternalServerError{}
}

/*
UpdateTenantAISettingsInternalServerError describes a response with status code 500, with default header values.

ErrorResponse defines a common error response structure.
*/
type UpdateTenantAISettingsInternalServerError struct {
	Payload *UpdateTenantAISettingsInternalServerErrorBody
}

// IsSuccess returns true when this update tenant a i settings internal server error response has a 2xx status code
func (o *UpdateTenantAISettingsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update tenant a i settings internal server error response has a 3xx status code
func (o *UpdateTenantAISettingsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update tenant a i settings internal server error response has a 4xx status code
func (o *UpdateTenantAISettingsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this update tenant a i settings internal server error response has a 5xx status code
func (o *UpdateTenantAISettingsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this update tenant a i settings internal server error response a status code equal to that given
func (o *UpdateTenantAISettingsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the update tenant a i settings internal server error response
func (o *UpdateTenantAISettingsInternalServerError) Code() int {
	return 500
}

func (o *UpdateTenantAISettingsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/rbac/v2/tenant/ai-settings][%d] updateTenantAISettingsInternalServerError %s", 500, payload)
}

func (o *UpdateTenantAISettingsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/rbac/v2/tenant/ai-settings][%d] updateTenantAISettingsInternalServerError %s", 500, payload)
}

func (o *UpdateTenantAISettingsInternalServerError) GetPayload() *UpdateTenantAISettingsInternalServerErrorBody {
	return o.Payload
}

func (o *UpdateTenantAISettingsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(UpdateTenantAISettingsInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
UpdateTenantAISettingsBadRequestBody update tenant a i settings bad request body
swagger:model UpdateTenantAISettingsBadRequestBody
*/
type UpdateTenantAISettingsBadRequestBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this update tenant a i settings bad request body
func (o *UpdateTenantAISettingsBadRequestBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this update tenant a i settings bad request body based on context it is used
func (o *UpdateTenantAISettingsBadRequestBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *UpdateTenantAISettingsBadRequestBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UpdateTenantAISettingsBadRequestBody) UnmarshalBinary(b []byte) error {
	var res UpdateTenantAISettingsBadRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
UpdateTenantAISettingsInternalServerErrorBody update tenant a i settings internal server error body
swagger:model UpdateTenantAISettingsInternalServerErrorBody
*/
type UpdateTenantAISettingsInternalServerErrorBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this update tenant a i settings internal server error body
func (o *UpdateTenantAISettingsInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this update tenant a i settings internal server error body based on context it is used
func (o *UpdateTenantAISettingsInternalServerErrorBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *UpdateTenantAISettingsInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UpdateTenantAISettingsInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res UpdateTenantAISettingsInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
