// Code generated by go-swagger; DO NOT EDIT.

package agent

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AgentDeleteSkillReader is a Reader for the AgentDeleteSkill structure.
type AgentDeleteSkillReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AgentDeleteSkillReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewAgentDeleteSkillOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewAgentDeleteSkillBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewAgentDeleteSkillUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewAgentDeleteSkillForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewAgentDeleteSkillNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewAgentDeleteSkillInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 502:
		result := NewAgentDeleteSkillBadGateway()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewAgentDeleteSkillServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /api/agent/skills/{skill_id}] agentDeleteSkill", response, response.Code())
	}
}

// NewAgentDeleteSkillOK creates a AgentDeleteSkillOK with default headers values
func NewAgentDeleteSkillOK() *AgentDeleteSkillOK {
	return &AgentDeleteSkillOK{}
}

/*
AgentDeleteSkillOK describes a response with status code 200, with default header values.

AgentSkillDeleteResponse is returned by the Skill delete endpoint.
*/
type AgentDeleteSkillOK struct {
	Payload *AgentDeleteSkillOKBody
}

// IsSuccess returns true when this agent delete skill o k response has a 2xx status code
func (o *AgentDeleteSkillOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this agent delete skill o k response has a 3xx status code
func (o *AgentDeleteSkillOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this agent delete skill o k response has a 4xx status code
func (o *AgentDeleteSkillOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this agent delete skill o k response has a 5xx status code
func (o *AgentDeleteSkillOK) IsServerError() bool {
	return false
}

// IsCode returns true when this agent delete skill o k response a status code equal to that given
func (o *AgentDeleteSkillOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the agent delete skill o k response
func (o *AgentDeleteSkillOK) Code() int {
	return 200
}

func (o *AgentDeleteSkillOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/agent/skills/{skill_id}][%d] agentDeleteSkillOK %s", 200, payload)
}

func (o *AgentDeleteSkillOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/agent/skills/{skill_id}][%d] agentDeleteSkillOK %s", 200, payload)
}

func (o *AgentDeleteSkillOK) GetPayload() *AgentDeleteSkillOKBody {
	return o.Payload
}

func (o *AgentDeleteSkillOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(AgentDeleteSkillOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewAgentDeleteSkillBadRequest creates a AgentDeleteSkillBadRequest with default headers values
func NewAgentDeleteSkillBadRequest() *AgentDeleteSkillBadRequest {
	return &AgentDeleteSkillBadRequest{}
}

/*
AgentDeleteSkillBadRequest describes a response with status code 400, with default header values.

ErrorResponse defines a common error response structure.
*/
type AgentDeleteSkillBadRequest struct {
	Payload *AgentDeleteSkillBadRequestBody
}

// IsSuccess returns true when this agent delete skill bad request response has a 2xx status code
func (o *AgentDeleteSkillBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this agent delete skill bad request response has a 3xx status code
func (o *AgentDeleteSkillBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this agent delete skill bad request response has a 4xx status code
func (o *AgentDeleteSkillBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this agent delete skill bad request response has a 5xx status code
func (o *AgentDeleteSkillBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this agent delete skill bad request response a status code equal to that given
func (o *AgentDeleteSkillBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the agent delete skill bad request response
func (o *AgentDeleteSkillBadRequest) Code() int {
	return 400
}

func (o *AgentDeleteSkillBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/agent/skills/{skill_id}][%d] agentDeleteSkillBadRequest %s", 400, payload)
}

func (o *AgentDeleteSkillBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/agent/skills/{skill_id}][%d] agentDeleteSkillBadRequest %s", 400, payload)
}

func (o *AgentDeleteSkillBadRequest) GetPayload() *AgentDeleteSkillBadRequestBody {
	return o.Payload
}

func (o *AgentDeleteSkillBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(AgentDeleteSkillBadRequestBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewAgentDeleteSkillUnauthorized creates a AgentDeleteSkillUnauthorized with default headers values
func NewAgentDeleteSkillUnauthorized() *AgentDeleteSkillUnauthorized {
	return &AgentDeleteSkillUnauthorized{}
}

/*
AgentDeleteSkillUnauthorized describes a response with status code 401, with default header values.

ErrorResponse defines a common error response structure.
*/
type AgentDeleteSkillUnauthorized struct {
	Payload *AgentDeleteSkillUnauthorizedBody
}

// IsSuccess returns true when this agent delete skill unauthorized response has a 2xx status code
func (o *AgentDeleteSkillUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this agent delete skill unauthorized response has a 3xx status code
func (o *AgentDeleteSkillUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this agent delete skill unauthorized response has a 4xx status code
func (o *AgentDeleteSkillUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this agent delete skill unauthorized response has a 5xx status code
func (o *AgentDeleteSkillUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this agent delete skill unauthorized response a status code equal to that given
func (o *AgentDeleteSkillUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the agent delete skill unauthorized response
func (o *AgentDeleteSkillUnauthorized) Code() int {
	return 401
}

func (o *AgentDeleteSkillUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/agent/skills/{skill_id}][%d] agentDeleteSkillUnauthorized %s", 401, payload)
}

func (o *AgentDeleteSkillUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/agent/skills/{skill_id}][%d] agentDeleteSkillUnauthorized %s", 401, payload)
}

func (o *AgentDeleteSkillUnauthorized) GetPayload() *AgentDeleteSkillUnauthorizedBody {
	return o.Payload
}

func (o *AgentDeleteSkillUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(AgentDeleteSkillUnauthorizedBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewAgentDeleteSkillForbidden creates a AgentDeleteSkillForbidden with default headers values
func NewAgentDeleteSkillForbidden() *AgentDeleteSkillForbidden {
	return &AgentDeleteSkillForbidden{}
}

/*
AgentDeleteSkillForbidden describes a response with status code 403, with default header values.

ErrorResponse defines a common error response structure.
*/
type AgentDeleteSkillForbidden struct {
	Payload *AgentDeleteSkillForbiddenBody
}

// IsSuccess returns true when this agent delete skill forbidden response has a 2xx status code
func (o *AgentDeleteSkillForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this agent delete skill forbidden response has a 3xx status code
func (o *AgentDeleteSkillForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this agent delete skill forbidden response has a 4xx status code
func (o *AgentDeleteSkillForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this agent delete skill forbidden response has a 5xx status code
func (o *AgentDeleteSkillForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this agent delete skill forbidden response a status code equal to that given
func (o *AgentDeleteSkillForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the agent delete skill forbidden response
func (o *AgentDeleteSkillForbidden) Code() int {
	return 403
}

func (o *AgentDeleteSkillForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/agent/skills/{skill_id}][%d] agentDeleteSkillForbidden %s", 403, payload)
}

func (o *AgentDeleteSkillForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/agent/skills/{skill_id}][%d] agentDeleteSkillForbidden %s", 403, payload)
}

func (o *AgentDeleteSkillForbidden) GetPayload() *AgentDeleteSkillForbiddenBody {
	return o.Payload
}

func (o *AgentDeleteSkillForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(AgentDeleteSkillForbiddenBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewAgentDeleteSkillNotFound creates a AgentDeleteSkillNotFound with default headers values
func NewAgentDeleteSkillNotFound() *AgentDeleteSkillNotFound {
	return &AgentDeleteSkillNotFound{}
}

/*
AgentDeleteSkillNotFound describes a response with status code 404, with default header values.

ErrorResponse defines a common error response structure.
*/
type AgentDeleteSkillNotFound struct {
	Payload *AgentDeleteSkillNotFoundBody
}

// IsSuccess returns true when this agent delete skill not found response has a 2xx status code
func (o *AgentDeleteSkillNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this agent delete skill not found response has a 3xx status code
func (o *AgentDeleteSkillNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this agent delete skill not found response has a 4xx status code
func (o *AgentDeleteSkillNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this agent delete skill not found response has a 5xx status code
func (o *AgentDeleteSkillNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this agent delete skill not found response a status code equal to that given
func (o *AgentDeleteSkillNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the agent delete skill not found response
func (o *AgentDeleteSkillNotFound) Code() int {
	return 404
}

func (o *AgentDeleteSkillNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/agent/skills/{skill_id}][%d] agentDeleteSkillNotFound %s", 404, payload)
}

func (o *AgentDeleteSkillNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/agent/skills/{skill_id}][%d] agentDeleteSkillNotFound %s", 404, payload)
}

func (o *AgentDeleteSkillNotFound) GetPayload() *AgentDeleteSkillNotFoundBody {
	return o.Payload
}

func (o *AgentDeleteSkillNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(AgentDeleteSkillNotFoundBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewAgentDeleteSkillInternalServerError creates a AgentDeleteSkillInternalServerError with default headers values
func NewAgentDeleteSkillInternalServerError() *AgentDeleteSkillInternalServerError {
	return &AgentDeleteSkillInternalServerError{}
}

/*
AgentDeleteSkillInternalServerError describes a response with status code 500, with default header values.

ErrorResponse defines a common error response structure.
*/
type AgentDeleteSkillInternalServerError struct {
	Payload *AgentDeleteSkillInternalServerErrorBody
}

// IsSuccess returns true when this agent delete skill internal server error response has a 2xx status code
func (o *AgentDeleteSkillInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this agent delete skill internal server error response has a 3xx status code
func (o *AgentDeleteSkillInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this agent delete skill internal server error response has a 4xx status code
func (o *AgentDeleteSkillInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this agent delete skill internal server error response has a 5xx status code
func (o *AgentDeleteSkillInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this agent delete skill internal server error response a status code equal to that given
func (o *AgentDeleteSkillInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the agent delete skill internal server error response
func (o *AgentDeleteSkillInternalServerError) Code() int {
	return 500
}

func (o *AgentDeleteSkillInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/agent/skills/{skill_id}][%d] agentDeleteSkillInternalServerError %s", 500, payload)
}

func (o *AgentDeleteSkillInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/agent/skills/{skill_id}][%d] agentDeleteSkillInternalServerError %s", 500, payload)
}

func (o *AgentDeleteSkillInternalServerError) GetPayload() *AgentDeleteSkillInternalServerErrorBody {
	return o.Payload
}

func (o *AgentDeleteSkillInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(AgentDeleteSkillInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewAgentDeleteSkillBadGateway creates a AgentDeleteSkillBadGateway with default headers values
func NewAgentDeleteSkillBadGateway() *AgentDeleteSkillBadGateway {
	return &AgentDeleteSkillBadGateway{}
}

/*
AgentDeleteSkillBadGateway describes a response with status code 502, with default header values.

ErrorResponse defines a common error response structure.
*/
type AgentDeleteSkillBadGateway struct {
	Payload *AgentDeleteSkillBadGatewayBody
}

// IsSuccess returns true when this agent delete skill bad gateway response has a 2xx status code
func (o *AgentDeleteSkillBadGateway) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this agent delete skill bad gateway response has a 3xx status code
func (o *AgentDeleteSkillBadGateway) IsRedirect() bool {
	return false
}

// IsClientError returns true when this agent delete skill bad gateway response has a 4xx status code
func (o *AgentDeleteSkillBadGateway) IsClientError() bool {
	return false
}

// IsServerError returns true when this agent delete skill bad gateway response has a 5xx status code
func (o *AgentDeleteSkillBadGateway) IsServerError() bool {
	return true
}

// IsCode returns true when this agent delete skill bad gateway response a status code equal to that given
func (o *AgentDeleteSkillBadGateway) IsCode(code int) bool {
	return code == 502
}

// Code gets the status code for the agent delete skill bad gateway response
func (o *AgentDeleteSkillBadGateway) Code() int {
	return 502
}

func (o *AgentDeleteSkillBadGateway) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/agent/skills/{skill_id}][%d] agentDeleteSkillBadGateway %s", 502, payload)
}

func (o *AgentDeleteSkillBadGateway) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/agent/skills/{skill_id}][%d] agentDeleteSkillBadGateway %s", 502, payload)
}

func (o *AgentDeleteSkillBadGateway) GetPayload() *AgentDeleteSkillBadGatewayBody {
	return o.Payload
}

func (o *AgentDeleteSkillBadGateway) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(AgentDeleteSkillBadGatewayBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewAgentDeleteSkillServiceUnavailable creates a AgentDeleteSkillServiceUnavailable with default headers values
func NewAgentDeleteSkillServiceUnavailable() *AgentDeleteSkillServiceUnavailable {
	return &AgentDeleteSkillServiceUnavailable{}
}

/*
AgentDeleteSkillServiceUnavailable describes a response with status code 503, with default header values.

ErrorResponse defines a common error response structure.
*/
type AgentDeleteSkillServiceUnavailable struct {
	Payload *AgentDeleteSkillServiceUnavailableBody
}

// IsSuccess returns true when this agent delete skill service unavailable response has a 2xx status code
func (o *AgentDeleteSkillServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this agent delete skill service unavailable response has a 3xx status code
func (o *AgentDeleteSkillServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this agent delete skill service unavailable response has a 4xx status code
func (o *AgentDeleteSkillServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this agent delete skill service unavailable response has a 5xx status code
func (o *AgentDeleteSkillServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this agent delete skill service unavailable response a status code equal to that given
func (o *AgentDeleteSkillServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the agent delete skill service unavailable response
func (o *AgentDeleteSkillServiceUnavailable) Code() int {
	return 503
}

func (o *AgentDeleteSkillServiceUnavailable) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/agent/skills/{skill_id}][%d] agentDeleteSkillServiceUnavailable %s", 503, payload)
}

func (o *AgentDeleteSkillServiceUnavailable) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/agent/skills/{skill_id}][%d] agentDeleteSkillServiceUnavailable %s", 503, payload)
}

func (o *AgentDeleteSkillServiceUnavailable) GetPayload() *AgentDeleteSkillServiceUnavailableBody {
	return o.Payload
}

func (o *AgentDeleteSkillServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(AgentDeleteSkillServiceUnavailableBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
AgentDeleteSkillBadGatewayBody agent delete skill bad gateway body
swagger:model AgentDeleteSkillBadGatewayBody
*/
type AgentDeleteSkillBadGatewayBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this agent delete skill bad gateway body
func (o *AgentDeleteSkillBadGatewayBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this agent delete skill bad gateway body based on context it is used
func (o *AgentDeleteSkillBadGatewayBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *AgentDeleteSkillBadGatewayBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *AgentDeleteSkillBadGatewayBody) UnmarshalBinary(b []byte) error {
	var res AgentDeleteSkillBadGatewayBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
AgentDeleteSkillBadRequestBody agent delete skill bad request body
swagger:model AgentDeleteSkillBadRequestBody
*/
type AgentDeleteSkillBadRequestBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this agent delete skill bad request body
func (o *AgentDeleteSkillBadRequestBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this agent delete skill bad request body based on context it is used
func (o *AgentDeleteSkillBadRequestBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *AgentDeleteSkillBadRequestBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *AgentDeleteSkillBadRequestBody) UnmarshalBinary(b []byte) error {
	var res AgentDeleteSkillBadRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
AgentDeleteSkillForbiddenBody agent delete skill forbidden body
swagger:model AgentDeleteSkillForbiddenBody
*/
type AgentDeleteSkillForbiddenBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this agent delete skill forbidden body
func (o *AgentDeleteSkillForbiddenBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this agent delete skill forbidden body based on context it is used
func (o *AgentDeleteSkillForbiddenBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *AgentDeleteSkillForbiddenBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *AgentDeleteSkillForbiddenBody) UnmarshalBinary(b []byte) error {
	var res AgentDeleteSkillForbiddenBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
AgentDeleteSkillInternalServerErrorBody agent delete skill internal server error body
swagger:model AgentDeleteSkillInternalServerErrorBody
*/
type AgentDeleteSkillInternalServerErrorBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this agent delete skill internal server error body
func (o *AgentDeleteSkillInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this agent delete skill internal server error body based on context it is used
func (o *AgentDeleteSkillInternalServerErrorBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *AgentDeleteSkillInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *AgentDeleteSkillInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res AgentDeleteSkillInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
AgentDeleteSkillNotFoundBody agent delete skill not found body
swagger:model AgentDeleteSkillNotFoundBody
*/
type AgentDeleteSkillNotFoundBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this agent delete skill not found body
func (o *AgentDeleteSkillNotFoundBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this agent delete skill not found body based on context it is used
func (o *AgentDeleteSkillNotFoundBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *AgentDeleteSkillNotFoundBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *AgentDeleteSkillNotFoundBody) UnmarshalBinary(b []byte) error {
	var res AgentDeleteSkillNotFoundBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
AgentDeleteSkillOKBody agent delete skill o k body
swagger:model AgentDeleteSkillOKBody
*/
type AgentDeleteSkillOKBody struct {

	// skill ID
	// Required: true
	SkillID *string `json:"skill_id"`

	// status
	// Required: true
	Status *string `json:"status"`
}

// Validate validates this agent delete skill o k body
func (o *AgentDeleteSkillOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateSkillID(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *AgentDeleteSkillOKBody) validateSkillID(formats strfmt.Registry) error {

	if err := validate.Required("agentDeleteSkillOK"+"."+"skill_id", "body", o.SkillID); err != nil {
		return err
	}

	return nil
}

func (o *AgentDeleteSkillOKBody) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("agentDeleteSkillOK"+"."+"status", "body", o.Status); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this agent delete skill o k body based on context it is used
func (o *AgentDeleteSkillOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *AgentDeleteSkillOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *AgentDeleteSkillOKBody) UnmarshalBinary(b []byte) error {
	var res AgentDeleteSkillOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
AgentDeleteSkillServiceUnavailableBody agent delete skill service unavailable body
swagger:model AgentDeleteSkillServiceUnavailableBody
*/
type AgentDeleteSkillServiceUnavailableBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this agent delete skill service unavailable body
func (o *AgentDeleteSkillServiceUnavailableBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this agent delete skill service unavailable body based on context it is used
func (o *AgentDeleteSkillServiceUnavailableBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *AgentDeleteSkillServiceUnavailableBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *AgentDeleteSkillServiceUnavailableBody) UnmarshalBinary(b []byte) error {
	var res AgentDeleteSkillServiceUnavailableBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
AgentDeleteSkillUnauthorizedBody agent delete skill unauthorized body
swagger:model AgentDeleteSkillUnauthorizedBody
*/
type AgentDeleteSkillUnauthorizedBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this agent delete skill unauthorized body
func (o *AgentDeleteSkillUnauthorizedBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this agent delete skill unauthorized body based on context it is used
func (o *AgentDeleteSkillUnauthorizedBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *AgentDeleteSkillUnauthorizedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *AgentDeleteSkillUnauthorizedBody) UnmarshalBinary(b []byte) error {
	var res AgentDeleteSkillUnauthorizedBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
