// Code generated by go-swagger; DO NOT EDIT.

package traces_pipeline

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteTracesPipelineConfigParams creates a new DeleteTracesPipelineConfigParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteTracesPipelineConfigParams() *DeleteTracesPipelineConfigParams {
	return &DeleteTracesPipelineConfigParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteTracesPipelineConfigParamsWithTimeout creates a new DeleteTracesPipelineConfigParams object
// with the ability to set a timeout on a request.
func NewDeleteTracesPipelineConfigParamsWithTimeout(timeout time.Duration) *DeleteTracesPipelineConfigParams {
	return &DeleteTracesPipelineConfigParams{
		timeout: timeout,
	}
}

// NewDeleteTracesPipelineConfigParamsWithContext creates a new DeleteTracesPipelineConfigParams object
// with the ability to set a context for a request.
func NewDeleteTracesPipelineConfigParamsWithContext(ctx context.Context) *DeleteTracesPipelineConfigParams {
	return &DeleteTracesPipelineConfigParams{
		Context: ctx,
	}
}

// NewDeleteTracesPipelineConfigParamsWithHTTPClient creates a new DeleteTracesPipelineConfigParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteTracesPipelineConfigParamsWithHTTPClient(client *http.Client) *DeleteTracesPipelineConfigParams {
	return &DeleteTracesPipelineConfigParams{
		HTTPClient: client,
	}
}

/*
DeleteTracesPipelineConfigParams contains all the parameters to send to the API endpoint

	for the delete traces pipeline config operation.

	Typically these are written to a http.Request.
*/
type DeleteTracesPipelineConfigParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete traces pipeline config params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteTracesPipelineConfigParams) WithDefaults() *DeleteTracesPipelineConfigParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete traces pipeline config params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteTracesPipelineConfigParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete traces pipeline config params
func (o *DeleteTracesPipelineConfigParams) WithTimeout(timeout time.Duration) *DeleteTracesPipelineConfigParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete traces pipeline config params
func (o *DeleteTracesPipelineConfigParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete traces pipeline config params
func (o *DeleteTracesPipelineConfigParams) WithContext(ctx context.Context) *DeleteTracesPipelineConfigParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete traces pipeline config params
func (o *DeleteTracesPipelineConfigParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete traces pipeline config params
func (o *DeleteTracesPipelineConfigParams) WithHTTPClient(client *http.Client) *DeleteTracesPipelineConfigParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete traces pipeline config params
func (o *DeleteTracesPipelineConfigParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteTracesPipelineConfigParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
