// Code generated by go-swagger; DO NOT EDIT.

package traces_pipeline

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/groundcover-com/groundcover-sdk-go/pkg/models"
)

// GetTracesPipelineConfigReader is a Reader for the GetTracesPipelineConfig structure.
type GetTracesPipelineConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTracesPipelineConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetTracesPipelineConfigOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 204:
		result := NewGetTracesPipelineConfigNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetTracesPipelineConfigInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewGetTracesPipelineConfigServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/pipelines/traces/config] getTracesPipelineConfig", response, response.Code())
	}
}

// NewGetTracesPipelineConfigOK creates a GetTracesPipelineConfigOK with default headers values
func NewGetTracesPipelineConfigOK() *GetTracesPipelineConfigOK {
	return &GetTracesPipelineConfigOK{}
}

/*
GetTracesPipelineConfigOK describes a response with status code 200, with default header values.

tracesPipelineConfigResponse contains a traces pipeline configuration entry
*/
type GetTracesPipelineConfigOK struct {
	Payload *models.TracesPipelineConfig
}

// IsSuccess returns true when this get traces pipeline config o k response has a 2xx status code
func (o *GetTracesPipelineConfigOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get traces pipeline config o k response has a 3xx status code
func (o *GetTracesPipelineConfigOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get traces pipeline config o k response has a 4xx status code
func (o *GetTracesPipelineConfigOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get traces pipeline config o k response has a 5xx status code
func (o *GetTracesPipelineConfigOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get traces pipeline config o k response a status code equal to that given
func (o *GetTracesPipelineConfigOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get traces pipeline config o k response
func (o *GetTracesPipelineConfigOK) Code() int {
	return 200
}

func (o *GetTracesPipelineConfigOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/pipelines/traces/config][%d] getTracesPipelineConfigOK %s", 200, payload)
}

func (o *GetTracesPipelineConfigOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/pipelines/traces/config][%d] getTracesPipelineConfigOK %s", 200, payload)
}

func (o *GetTracesPipelineConfigOK) GetPayload() *models.TracesPipelineConfig {
	return o.Payload
}

func (o *GetTracesPipelineConfigOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TracesPipelineConfig)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetTracesPipelineConfigNoContent creates a GetTracesPipelineConfigNoContent with default headers values
func NewGetTracesPipelineConfigNoContent() *GetTracesPipelineConfigNoContent {
	return &GetTracesPipelineConfigNoContent{}
}

/*
GetTracesPipelineConfigNoContent describes a response with status code 204, with default header values.

emptyTracesPipelineConfigResponse is used for empty responses
*/
type GetTracesPipelineConfigNoContent struct {
	Payload any
}

// IsSuccess returns true when this get traces pipeline config no content response has a 2xx status code
func (o *GetTracesPipelineConfigNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get traces pipeline config no content response has a 3xx status code
func (o *GetTracesPipelineConfigNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get traces pipeline config no content response has a 4xx status code
func (o *GetTracesPipelineConfigNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this get traces pipeline config no content response has a 5xx status code
func (o *GetTracesPipelineConfigNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this get traces pipeline config no content response a status code equal to that given
func (o *GetTracesPipelineConfigNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the get traces pipeline config no content response
func (o *GetTracesPipelineConfigNoContent) Code() int {
	return 204
}

func (o *GetTracesPipelineConfigNoContent) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/pipelines/traces/config][%d] getTracesPipelineConfigNoContent %s", 204, payload)
}

func (o *GetTracesPipelineConfigNoContent) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/pipelines/traces/config][%d] getTracesPipelineConfigNoContent %s", 204, payload)
}

func (o *GetTracesPipelineConfigNoContent) GetPayload() any {
	return o.Payload
}

func (o *GetTracesPipelineConfigNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetTracesPipelineConfigInternalServerError creates a GetTracesPipelineConfigInternalServerError with default headers values
func NewGetTracesPipelineConfigInternalServerError() *GetTracesPipelineConfigInternalServerError {
	return &GetTracesPipelineConfigInternalServerError{}
}

/*
GetTracesPipelineConfigInternalServerError describes a response with status code 500, with default header values.

tracesPipelineErrorResponse is used for error responses
*/
type GetTracesPipelineConfigInternalServerError struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this get traces pipeline config internal server error response has a 2xx status code
func (o *GetTracesPipelineConfigInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get traces pipeline config internal server error response has a 3xx status code
func (o *GetTracesPipelineConfigInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get traces pipeline config internal server error response has a 4xx status code
func (o *GetTracesPipelineConfigInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get traces pipeline config internal server error response has a 5xx status code
func (o *GetTracesPipelineConfigInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get traces pipeline config internal server error response a status code equal to that given
func (o *GetTracesPipelineConfigInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get traces pipeline config internal server error response
func (o *GetTracesPipelineConfigInternalServerError) Code() int {
	return 500
}

func (o *GetTracesPipelineConfigInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/pipelines/traces/config][%d] getTracesPipelineConfigInternalServerError %s", 500, payload)
}

func (o *GetTracesPipelineConfigInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/pipelines/traces/config][%d] getTracesPipelineConfigInternalServerError %s", 500, payload)
}

func (o *GetTracesPipelineConfigInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetTracesPipelineConfigInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetTracesPipelineConfigServiceUnavailable creates a GetTracesPipelineConfigServiceUnavailable with default headers values
func NewGetTracesPipelineConfigServiceUnavailable() *GetTracesPipelineConfigServiceUnavailable {
	return &GetTracesPipelineConfigServiceUnavailable{}
}

/*
GetTracesPipelineConfigServiceUnavailable describes a response with status code 503, with default header values.

tracesPipelineErrorResponse is used for error responses
*/
type GetTracesPipelineConfigServiceUnavailable struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this get traces pipeline config service unavailable response has a 2xx status code
func (o *GetTracesPipelineConfigServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get traces pipeline config service unavailable response has a 3xx status code
func (o *GetTracesPipelineConfigServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get traces pipeline config service unavailable response has a 4xx status code
func (o *GetTracesPipelineConfigServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this get traces pipeline config service unavailable response has a 5xx status code
func (o *GetTracesPipelineConfigServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this get traces pipeline config service unavailable response a status code equal to that given
func (o *GetTracesPipelineConfigServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the get traces pipeline config service unavailable response
func (o *GetTracesPipelineConfigServiceUnavailable) Code() int {
	return 503
}

func (o *GetTracesPipelineConfigServiceUnavailable) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/pipelines/traces/config][%d] getTracesPipelineConfigServiceUnavailable %s", 503, payload)
}

func (o *GetTracesPipelineConfigServiceUnavailable) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/pipelines/traces/config][%d] getTracesPipelineConfigServiceUnavailable %s", 503, payload)
}

func (o *GetTracesPipelineConfigServiceUnavailable) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetTracesPipelineConfigServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
