// Code generated by go-swagger; DO NOT EDIT.

package aggregations_metrics

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new aggregations metrics API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new aggregations metrics API client with basic auth credentials.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new aggregations metrics API client with a bearer token for authentication.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for aggregations metrics API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	CreateMetricsAggregatorConfig(params *CreateMetricsAggregatorConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateMetricsAggregatorConfigCreated, error)

	DeleteMetricsAggregatorConfig(params *DeleteMetricsAggregatorConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteMetricsAggregatorConfigOK, error)

	GetMetricsAggregatorConfig(params *GetMetricsAggregatorConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetMetricsAggregatorConfigOK, *GetMetricsAggregatorConfigNoContent, error)

	UpdateMetricsAggregatorConfig(params *UpdateMetricsAggregatorConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*UpdateMetricsAggregatorConfigOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
CreateMetricsAggregatorConfig create metrics aggregator config API
*/
func (a *Client) CreateMetricsAggregatorConfig(params *CreateMetricsAggregatorConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateMetricsAggregatorConfigCreated, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewCreateMetricsAggregatorConfigParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "createMetricsAggregatorConfig",
		Method:             "POST",
		PathPattern:        "/api/aggregations/v1/metrics/config",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CreateMetricsAggregatorConfigReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*CreateMetricsAggregatorConfigCreated)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for createMetricsAggregatorConfig: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
DeleteMetricsAggregatorConfig delete metrics aggregator config API
*/
func (a *Client) DeleteMetricsAggregatorConfig(params *DeleteMetricsAggregatorConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteMetricsAggregatorConfigOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewDeleteMetricsAggregatorConfigParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "deleteMetricsAggregatorConfig",
		Method:             "DELETE",
		PathPattern:        "/api/aggregations/v1/metrics/config",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DeleteMetricsAggregatorConfigReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*DeleteMetricsAggregatorConfigOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for deleteMetricsAggregatorConfig: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetMetricsAggregatorConfig get metrics aggregator config API
*/
func (a *Client) GetMetricsAggregatorConfig(params *GetMetricsAggregatorConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetMetricsAggregatorConfigOK, *GetMetricsAggregatorConfigNoContent, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetMetricsAggregatorConfigParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "getMetricsAggregatorConfig",
		Method:             "GET",
		PathPattern:        "/api/aggregations/v1/metrics/config",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetMetricsAggregatorConfigReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, nil, err
	}

	// several success responses have to be checked
	switch value := result.(type) {
	case *GetMetricsAggregatorConfigOK:
		return value, nil, nil
	case *GetMetricsAggregatorConfigNoContent:
		return nil, value, nil
	}

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for aggregations_metrics: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
UpdateMetricsAggregatorConfig update metrics aggregator config API
*/
func (a *Client) UpdateMetricsAggregatorConfig(params *UpdateMetricsAggregatorConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*UpdateMetricsAggregatorConfigOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewUpdateMetricsAggregatorConfigParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "updateMetricsAggregatorConfig",
		Method:             "PUT",
		PathPattern:        "/api/aggregations/v1/metrics/config",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &UpdateMetricsAggregatorConfigReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*UpdateMetricsAggregatorConfigOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for updateMetricsAggregatorConfig: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
