// Code generated by go-swagger; DO NOT EDIT.

package aggregations_metrics

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/groundcover-com/groundcover-sdk-go/pkg/models"
)

// DeleteMetricsAggregatorConfigReader is a Reader for the DeleteMetricsAggregatorConfig structure.
type DeleteMetricsAggregatorConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteMetricsAggregatorConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteMetricsAggregatorConfigOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteMetricsAggregatorConfigBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteMetricsAggregatorConfigInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewDeleteMetricsAggregatorConfigServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /api/aggregations/v1/metrics/config] deleteMetricsAggregatorConfig", response, response.Code())
	}
}

// NewDeleteMetricsAggregatorConfigOK creates a DeleteMetricsAggregatorConfigOK with default headers values
func NewDeleteMetricsAggregatorConfigOK() *DeleteMetricsAggregatorConfigOK {
	return &DeleteMetricsAggregatorConfigOK{}
}

/*
DeleteMetricsAggregatorConfigOK describes a response with status code 200, with default header values.

emptyMetricsAggregatorConfigResponse is used for empty responses
*/
type DeleteMetricsAggregatorConfigOK struct {
	Payload any
}

// IsSuccess returns true when this delete metrics aggregator config o k response has a 2xx status code
func (o *DeleteMetricsAggregatorConfigOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete metrics aggregator config o k response has a 3xx status code
func (o *DeleteMetricsAggregatorConfigOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete metrics aggregator config o k response has a 4xx status code
func (o *DeleteMetricsAggregatorConfigOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete metrics aggregator config o k response has a 5xx status code
func (o *DeleteMetricsAggregatorConfigOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete metrics aggregator config o k response a status code equal to that given
func (o *DeleteMetricsAggregatorConfigOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete metrics aggregator config o k response
func (o *DeleteMetricsAggregatorConfigOK) Code() int {
	return 200
}

func (o *DeleteMetricsAggregatorConfigOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/aggregations/v1/metrics/config][%d] deleteMetricsAggregatorConfigOK %s", 200, payload)
}

func (o *DeleteMetricsAggregatorConfigOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/aggregations/v1/metrics/config][%d] deleteMetricsAggregatorConfigOK %s", 200, payload)
}

func (o *DeleteMetricsAggregatorConfigOK) GetPayload() any {
	return o.Payload
}

func (o *DeleteMetricsAggregatorConfigOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteMetricsAggregatorConfigBadRequest creates a DeleteMetricsAggregatorConfigBadRequest with default headers values
func NewDeleteMetricsAggregatorConfigBadRequest() *DeleteMetricsAggregatorConfigBadRequest {
	return &DeleteMetricsAggregatorConfigBadRequest{}
}

/*
DeleteMetricsAggregatorConfigBadRequest describes a response with status code 400, with default header values.

metricsAggregatorErrorResponse is used for error responses
*/
type DeleteMetricsAggregatorConfigBadRequest struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this delete metrics aggregator config bad request response has a 2xx status code
func (o *DeleteMetricsAggregatorConfigBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete metrics aggregator config bad request response has a 3xx status code
func (o *DeleteMetricsAggregatorConfigBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete metrics aggregator config bad request response has a 4xx status code
func (o *DeleteMetricsAggregatorConfigBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete metrics aggregator config bad request response has a 5xx status code
func (o *DeleteMetricsAggregatorConfigBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this delete metrics aggregator config bad request response a status code equal to that given
func (o *DeleteMetricsAggregatorConfigBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the delete metrics aggregator config bad request response
func (o *DeleteMetricsAggregatorConfigBadRequest) Code() int {
	return 400
}

func (o *DeleteMetricsAggregatorConfigBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/aggregations/v1/metrics/config][%d] deleteMetricsAggregatorConfigBadRequest %s", 400, payload)
}

func (o *DeleteMetricsAggregatorConfigBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/aggregations/v1/metrics/config][%d] deleteMetricsAggregatorConfigBadRequest %s", 400, payload)
}

func (o *DeleteMetricsAggregatorConfigBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *DeleteMetricsAggregatorConfigBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteMetricsAggregatorConfigInternalServerError creates a DeleteMetricsAggregatorConfigInternalServerError with default headers values
func NewDeleteMetricsAggregatorConfigInternalServerError() *DeleteMetricsAggregatorConfigInternalServerError {
	return &DeleteMetricsAggregatorConfigInternalServerError{}
}

/*
DeleteMetricsAggregatorConfigInternalServerError describes a response with status code 500, with default header values.

metricsAggregatorErrorResponse is used for error responses
*/
type DeleteMetricsAggregatorConfigInternalServerError struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this delete metrics aggregator config internal server error response has a 2xx status code
func (o *DeleteMetricsAggregatorConfigInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete metrics aggregator config internal server error response has a 3xx status code
func (o *DeleteMetricsAggregatorConfigInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete metrics aggregator config internal server error response has a 4xx status code
func (o *DeleteMetricsAggregatorConfigInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete metrics aggregator config internal server error response has a 5xx status code
func (o *DeleteMetricsAggregatorConfigInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this delete metrics aggregator config internal server error response a status code equal to that given
func (o *DeleteMetricsAggregatorConfigInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the delete metrics aggregator config internal server error response
func (o *DeleteMetricsAggregatorConfigInternalServerError) Code() int {
	return 500
}

func (o *DeleteMetricsAggregatorConfigInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/aggregations/v1/metrics/config][%d] deleteMetricsAggregatorConfigInternalServerError %s", 500, payload)
}

func (o *DeleteMetricsAggregatorConfigInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/aggregations/v1/metrics/config][%d] deleteMetricsAggregatorConfigInternalServerError %s", 500, payload)
}

func (o *DeleteMetricsAggregatorConfigInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *DeleteMetricsAggregatorConfigInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteMetricsAggregatorConfigServiceUnavailable creates a DeleteMetricsAggregatorConfigServiceUnavailable with default headers values
func NewDeleteMetricsAggregatorConfigServiceUnavailable() *DeleteMetricsAggregatorConfigServiceUnavailable {
	return &DeleteMetricsAggregatorConfigServiceUnavailable{}
}

/*
DeleteMetricsAggregatorConfigServiceUnavailable describes a response with status code 503, with default header values.

metricsAggregatorErrorResponse is used for error responses
*/
type DeleteMetricsAggregatorConfigServiceUnavailable struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this delete metrics aggregator config service unavailable response has a 2xx status code
func (o *DeleteMetricsAggregatorConfigServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete metrics aggregator config service unavailable response has a 3xx status code
func (o *DeleteMetricsAggregatorConfigServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete metrics aggregator config service unavailable response has a 4xx status code
func (o *DeleteMetricsAggregatorConfigServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete metrics aggregator config service unavailable response has a 5xx status code
func (o *DeleteMetricsAggregatorConfigServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this delete metrics aggregator config service unavailable response a status code equal to that given
func (o *DeleteMetricsAggregatorConfigServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the delete metrics aggregator config service unavailable response
func (o *DeleteMetricsAggregatorConfigServiceUnavailable) Code() int {
	return 503
}

func (o *DeleteMetricsAggregatorConfigServiceUnavailable) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/aggregations/v1/metrics/config][%d] deleteMetricsAggregatorConfigServiceUnavailable %s", 503, payload)
}

func (o *DeleteMetricsAggregatorConfigServiceUnavailable) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/aggregations/v1/metrics/config][%d] deleteMetricsAggregatorConfigServiceUnavailable %s", 503, payload)
}

func (o *DeleteMetricsAggregatorConfigServiceUnavailable) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *DeleteMetricsAggregatorConfigServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
