// Code generated by go-swagger; DO NOT EDIT.

package connected_apps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/groundcover-com/groundcover-sdk-go/pkg/models"
)

// CreateConnectedAppReader is a Reader for the CreateConnectedApp structure.
type CreateConnectedAppReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateConnectedAppReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 201:
		result := NewCreateConnectedAppCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateConnectedAppBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewCreateConnectedAppConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateConnectedAppInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /api/connected-apps/v1] createConnectedApp", response, response.Code())
	}
}

// NewCreateConnectedAppCreated creates a CreateConnectedAppCreated with default headers values
func NewCreateConnectedAppCreated() *CreateConnectedAppCreated {
	return &CreateConnectedAppCreated{}
}

/*
CreateConnectedAppCreated describes a response with status code 201, with default header values.

CreateConnectedAppCreated create connected app created
*/
type CreateConnectedAppCreated struct {
	Payload *models.CreateConnectedAppResponse
}

// IsSuccess returns true when this create connected app created response has a 2xx status code
func (o *CreateConnectedAppCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create connected app created response has a 3xx status code
func (o *CreateConnectedAppCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create connected app created response has a 4xx status code
func (o *CreateConnectedAppCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this create connected app created response has a 5xx status code
func (o *CreateConnectedAppCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this create connected app created response a status code equal to that given
func (o *CreateConnectedAppCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the create connected app created response
func (o *CreateConnectedAppCreated) Code() int {
	return 201
}

func (o *CreateConnectedAppCreated) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/connected-apps/v1][%d] createConnectedAppCreated %s", 201, payload)
}

func (o *CreateConnectedAppCreated) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/connected-apps/v1][%d] createConnectedAppCreated %s", 201, payload)
}

func (o *CreateConnectedAppCreated) GetPayload() *models.CreateConnectedAppResponse {
	return o.Payload
}

func (o *CreateConnectedAppCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CreateConnectedAppResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCreateConnectedAppBadRequest creates a CreateConnectedAppBadRequest with default headers values
func NewCreateConnectedAppBadRequest() *CreateConnectedAppBadRequest {
	return &CreateConnectedAppBadRequest{}
}

/*
CreateConnectedAppBadRequest describes a response with status code 400, with default header values.

ErrorResponse defines a common error response structure.
*/
type CreateConnectedAppBadRequest struct {
	Payload *CreateConnectedAppBadRequestBody
}

// IsSuccess returns true when this create connected app bad request response has a 2xx status code
func (o *CreateConnectedAppBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create connected app bad request response has a 3xx status code
func (o *CreateConnectedAppBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create connected app bad request response has a 4xx status code
func (o *CreateConnectedAppBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this create connected app bad request response has a 5xx status code
func (o *CreateConnectedAppBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this create connected app bad request response a status code equal to that given
func (o *CreateConnectedAppBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the create connected app bad request response
func (o *CreateConnectedAppBadRequest) Code() int {
	return 400
}

func (o *CreateConnectedAppBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/connected-apps/v1][%d] createConnectedAppBadRequest %s", 400, payload)
}

func (o *CreateConnectedAppBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/connected-apps/v1][%d] createConnectedAppBadRequest %s", 400, payload)
}

func (o *CreateConnectedAppBadRequest) GetPayload() *CreateConnectedAppBadRequestBody {
	return o.Payload
}

func (o *CreateConnectedAppBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(CreateConnectedAppBadRequestBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCreateConnectedAppConflict creates a CreateConnectedAppConflict with default headers values
func NewCreateConnectedAppConflict() *CreateConnectedAppConflict {
	return &CreateConnectedAppConflict{}
}

/*
CreateConnectedAppConflict describes a response with status code 409, with default header values.

ErrorResponse defines a common error response structure.
*/
type CreateConnectedAppConflict struct {
	Payload *CreateConnectedAppConflictBody
}

// IsSuccess returns true when this create connected app conflict response has a 2xx status code
func (o *CreateConnectedAppConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create connected app conflict response has a 3xx status code
func (o *CreateConnectedAppConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create connected app conflict response has a 4xx status code
func (o *CreateConnectedAppConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this create connected app conflict response has a 5xx status code
func (o *CreateConnectedAppConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this create connected app conflict response a status code equal to that given
func (o *CreateConnectedAppConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the create connected app conflict response
func (o *CreateConnectedAppConflict) Code() int {
	return 409
}

func (o *CreateConnectedAppConflict) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/connected-apps/v1][%d] createConnectedAppConflict %s", 409, payload)
}

func (o *CreateConnectedAppConflict) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/connected-apps/v1][%d] createConnectedAppConflict %s", 409, payload)
}

func (o *CreateConnectedAppConflict) GetPayload() *CreateConnectedAppConflictBody {
	return o.Payload
}

func (o *CreateConnectedAppConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(CreateConnectedAppConflictBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCreateConnectedAppInternalServerError creates a CreateConnectedAppInternalServerError with default headers values
func NewCreateConnectedAppInternalServerError() *CreateConnectedAppInternalServerError {
	return &CreateConnectedAppInternalServerError{}
}

/*
CreateConnectedAppInternalServerError describes a response with status code 500, with default header values.

ErrorResponse defines a common error response structure.
*/
type CreateConnectedAppInternalServerError struct {
	Payload *CreateConnectedAppInternalServerErrorBody
}

// IsSuccess returns true when this create connected app internal server error response has a 2xx status code
func (o *CreateConnectedAppInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create connected app internal server error response has a 3xx status code
func (o *CreateConnectedAppInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create connected app internal server error response has a 4xx status code
func (o *CreateConnectedAppInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this create connected app internal server error response has a 5xx status code
func (o *CreateConnectedAppInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this create connected app internal server error response a status code equal to that given
func (o *CreateConnectedAppInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the create connected app internal server error response
func (o *CreateConnectedAppInternalServerError) Code() int {
	return 500
}

func (o *CreateConnectedAppInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/connected-apps/v1][%d] createConnectedAppInternalServerError %s", 500, payload)
}

func (o *CreateConnectedAppInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/connected-apps/v1][%d] createConnectedAppInternalServerError %s", 500, payload)
}

func (o *CreateConnectedAppInternalServerError) GetPayload() *CreateConnectedAppInternalServerErrorBody {
	return o.Payload
}

func (o *CreateConnectedAppInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(CreateConnectedAppInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
CreateConnectedAppBadRequestBody create connected app bad request body
swagger:model CreateConnectedAppBadRequestBody
*/
type CreateConnectedAppBadRequestBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this create connected app bad request body
func (o *CreateConnectedAppBadRequestBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create connected app bad request body based on context it is used
func (o *CreateConnectedAppBadRequestBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *CreateConnectedAppBadRequestBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreateConnectedAppBadRequestBody) UnmarshalBinary(b []byte) error {
	var res CreateConnectedAppBadRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
CreateConnectedAppConflictBody create connected app conflict body
swagger:model CreateConnectedAppConflictBody
*/
type CreateConnectedAppConflictBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this create connected app conflict body
func (o *CreateConnectedAppConflictBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create connected app conflict body based on context it is used
func (o *CreateConnectedAppConflictBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *CreateConnectedAppConflictBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreateConnectedAppConflictBody) UnmarshalBinary(b []byte) error {
	var res CreateConnectedAppConflictBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
CreateConnectedAppInternalServerErrorBody create connected app internal server error body
swagger:model CreateConnectedAppInternalServerErrorBody
*/
type CreateConnectedAppInternalServerErrorBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this create connected app internal server error body
func (o *CreateConnectedAppInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create connected app internal server error body based on context it is used
func (o *CreateConnectedAppInternalServerErrorBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *CreateConnectedAppInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreateConnectedAppInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res CreateConnectedAppInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
