// Code generated by go-swagger; DO NOT EDIT.

package connected_apps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/groundcover-com/groundcover-sdk-go/pkg/models"
)

// NewCreateConnectedAppParams creates a new CreateConnectedAppParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateConnectedAppParams() *CreateConnectedAppParams {
	return &CreateConnectedAppParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateConnectedAppParamsWithTimeout creates a new CreateConnectedAppParams object
// with the ability to set a timeout on a request.
func NewCreateConnectedAppParamsWithTimeout(timeout time.Duration) *CreateConnectedAppParams {
	return &CreateConnectedAppParams{
		timeout: timeout,
	}
}

// NewCreateConnectedAppParamsWithContext creates a new CreateConnectedAppParams object
// with the ability to set a context for a request.
func NewCreateConnectedAppParamsWithContext(ctx context.Context) *CreateConnectedAppParams {
	return &CreateConnectedAppParams{
		Context: ctx,
	}
}

// NewCreateConnectedAppParamsWithHTTPClient creates a new CreateConnectedAppParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateConnectedAppParamsWithHTTPClient(client *http.Client) *CreateConnectedAppParams {
	return &CreateConnectedAppParams{
		HTTPClient: client,
	}
}

/*
CreateConnectedAppParams contains all the parameters to send to the API endpoint

	for the create connected app operation.

	Typically these are written to a http.Request.
*/
type CreateConnectedAppParams struct {

	/* Body.

	   Connected app creation request
	*/
	Body *models.CreateConnectedAppRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create connected app params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateConnectedAppParams) WithDefaults() *CreateConnectedAppParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create connected app params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateConnectedAppParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create connected app params
func (o *CreateConnectedAppParams) WithTimeout(timeout time.Duration) *CreateConnectedAppParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create connected app params
func (o *CreateConnectedAppParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create connected app params
func (o *CreateConnectedAppParams) WithContext(ctx context.Context) *CreateConnectedAppParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create connected app params
func (o *CreateConnectedAppParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create connected app params
func (o *CreateConnectedAppParams) WithHTTPClient(client *http.Client) *CreateConnectedAppParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create connected app params
func (o *CreateConnectedAppParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create connected app params
func (o *CreateConnectedAppParams) WithBody(body *models.CreateConnectedAppRequest) *CreateConnectedAppParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create connected app params
func (o *CreateConnectedAppParams) SetBody(body *models.CreateConnectedAppRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateConnectedAppParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
