// Code generated by go-swagger; DO NOT EDIT.

package rum

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/groundcover-com/groundcover-sdk-go/pkg/models"
)

// UploadSourceMapReader is a Reader for the UploadSourceMap structure.
type UploadSourceMapReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UploadSourceMapReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 201:
		result := NewUploadSourceMapCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUploadSourceMapBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 413:
		result := NewUploadSourceMapRequestEntityTooLarge()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewUploadSourceMapInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 502:
		result := NewUploadSourceMapBadGateway()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewUploadSourceMapServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /api/rum/sourcemaps] uploadSourceMap", response, response.Code())
	}
}

// NewUploadSourceMapCreated creates a UploadSourceMapCreated with default headers values
func NewUploadSourceMapCreated() *UploadSourceMapCreated {
	return &UploadSourceMapCreated{}
}

/*
UploadSourceMapCreated describes a response with status code 201, with default header values.

UploadSourceMapCreated upload source map created
*/
type UploadSourceMapCreated struct {
	Payload *models.SourceMapUploadResponse
}

// IsSuccess returns true when this upload source map created response has a 2xx status code
func (o *UploadSourceMapCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this upload source map created response has a 3xx status code
func (o *UploadSourceMapCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this upload source map created response has a 4xx status code
func (o *UploadSourceMapCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this upload source map created response has a 5xx status code
func (o *UploadSourceMapCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this upload source map created response a status code equal to that given
func (o *UploadSourceMapCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the upload source map created response
func (o *UploadSourceMapCreated) Code() int {
	return 201
}

func (o *UploadSourceMapCreated) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/rum/sourcemaps][%d] uploadSourceMapCreated %s", 201, payload)
}

func (o *UploadSourceMapCreated) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/rum/sourcemaps][%d] uploadSourceMapCreated %s", 201, payload)
}

func (o *UploadSourceMapCreated) GetPayload() *models.SourceMapUploadResponse {
	return o.Payload
}

func (o *UploadSourceMapCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SourceMapUploadResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewUploadSourceMapBadRequest creates a UploadSourceMapBadRequest with default headers values
func NewUploadSourceMapBadRequest() *UploadSourceMapBadRequest {
	return &UploadSourceMapBadRequest{}
}

/*
UploadSourceMapBadRequest describes a response with status code 400, with default header values.

UploadSourceMapBadRequest upload source map bad request
*/
type UploadSourceMapBadRequest struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this upload source map bad request response has a 2xx status code
func (o *UploadSourceMapBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this upload source map bad request response has a 3xx status code
func (o *UploadSourceMapBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this upload source map bad request response has a 4xx status code
func (o *UploadSourceMapBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this upload source map bad request response has a 5xx status code
func (o *UploadSourceMapBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this upload source map bad request response a status code equal to that given
func (o *UploadSourceMapBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the upload source map bad request response
func (o *UploadSourceMapBadRequest) Code() int {
	return 400
}

func (o *UploadSourceMapBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/rum/sourcemaps][%d] uploadSourceMapBadRequest %s", 400, payload)
}

func (o *UploadSourceMapBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/rum/sourcemaps][%d] uploadSourceMapBadRequest %s", 400, payload)
}

func (o *UploadSourceMapBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *UploadSourceMapBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewUploadSourceMapRequestEntityTooLarge creates a UploadSourceMapRequestEntityTooLarge with default headers values
func NewUploadSourceMapRequestEntityTooLarge() *UploadSourceMapRequestEntityTooLarge {
	return &UploadSourceMapRequestEntityTooLarge{}
}

/*
UploadSourceMapRequestEntityTooLarge describes a response with status code 413, with default header values.

UploadSourceMapRequestEntityTooLarge upload source map request entity too large
*/
type UploadSourceMapRequestEntityTooLarge struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this upload source map request entity too large response has a 2xx status code
func (o *UploadSourceMapRequestEntityTooLarge) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this upload source map request entity too large response has a 3xx status code
func (o *UploadSourceMapRequestEntityTooLarge) IsRedirect() bool {
	return false
}

// IsClientError returns true when this upload source map request entity too large response has a 4xx status code
func (o *UploadSourceMapRequestEntityTooLarge) IsClientError() bool {
	return true
}

// IsServerError returns true when this upload source map request entity too large response has a 5xx status code
func (o *UploadSourceMapRequestEntityTooLarge) IsServerError() bool {
	return false
}

// IsCode returns true when this upload source map request entity too large response a status code equal to that given
func (o *UploadSourceMapRequestEntityTooLarge) IsCode(code int) bool {
	return code == 413
}

// Code gets the status code for the upload source map request entity too large response
func (o *UploadSourceMapRequestEntityTooLarge) Code() int {
	return 413
}

func (o *UploadSourceMapRequestEntityTooLarge) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/rum/sourcemaps][%d] uploadSourceMapRequestEntityTooLarge %s", 413, payload)
}

func (o *UploadSourceMapRequestEntityTooLarge) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/rum/sourcemaps][%d] uploadSourceMapRequestEntityTooLarge %s", 413, payload)
}

func (o *UploadSourceMapRequestEntityTooLarge) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *UploadSourceMapRequestEntityTooLarge) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewUploadSourceMapInternalServerError creates a UploadSourceMapInternalServerError with default headers values
func NewUploadSourceMapInternalServerError() *UploadSourceMapInternalServerError {
	return &UploadSourceMapInternalServerError{}
}

/*
UploadSourceMapInternalServerError describes a response with status code 500, with default header values.

UploadSourceMapInternalServerError upload source map internal server error
*/
type UploadSourceMapInternalServerError struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this upload source map internal server error response has a 2xx status code
func (o *UploadSourceMapInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this upload source map internal server error response has a 3xx status code
func (o *UploadSourceMapInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this upload source map internal server error response has a 4xx status code
func (o *UploadSourceMapInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this upload source map internal server error response has a 5xx status code
func (o *UploadSourceMapInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this upload source map internal server error response a status code equal to that given
func (o *UploadSourceMapInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the upload source map internal server error response
func (o *UploadSourceMapInternalServerError) Code() int {
	return 500
}

func (o *UploadSourceMapInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/rum/sourcemaps][%d] uploadSourceMapInternalServerError %s", 500, payload)
}

func (o *UploadSourceMapInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/rum/sourcemaps][%d] uploadSourceMapInternalServerError %s", 500, payload)
}

func (o *UploadSourceMapInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *UploadSourceMapInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewUploadSourceMapBadGateway creates a UploadSourceMapBadGateway with default headers values
func NewUploadSourceMapBadGateway() *UploadSourceMapBadGateway {
	return &UploadSourceMapBadGateway{}
}

/*
UploadSourceMapBadGateway describes a response with status code 502, with default header values.

UploadSourceMapBadGateway upload source map bad gateway
*/
type UploadSourceMapBadGateway struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this upload source map bad gateway response has a 2xx status code
func (o *UploadSourceMapBadGateway) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this upload source map bad gateway response has a 3xx status code
func (o *UploadSourceMapBadGateway) IsRedirect() bool {
	return false
}

// IsClientError returns true when this upload source map bad gateway response has a 4xx status code
func (o *UploadSourceMapBadGateway) IsClientError() bool {
	return false
}

// IsServerError returns true when this upload source map bad gateway response has a 5xx status code
func (o *UploadSourceMapBadGateway) IsServerError() bool {
	return true
}

// IsCode returns true when this upload source map bad gateway response a status code equal to that given
func (o *UploadSourceMapBadGateway) IsCode(code int) bool {
	return code == 502
}

// Code gets the status code for the upload source map bad gateway response
func (o *UploadSourceMapBadGateway) Code() int {
	return 502
}

func (o *UploadSourceMapBadGateway) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/rum/sourcemaps][%d] uploadSourceMapBadGateway %s", 502, payload)
}

func (o *UploadSourceMapBadGateway) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/rum/sourcemaps][%d] uploadSourceMapBadGateway %s", 502, payload)
}

func (o *UploadSourceMapBadGateway) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *UploadSourceMapBadGateway) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewUploadSourceMapServiceUnavailable creates a UploadSourceMapServiceUnavailable with default headers values
func NewUploadSourceMapServiceUnavailable() *UploadSourceMapServiceUnavailable {
	return &UploadSourceMapServiceUnavailable{}
}

/*
UploadSourceMapServiceUnavailable describes a response with status code 503, with default header values.

UploadSourceMapServiceUnavailable upload source map service unavailable
*/
type UploadSourceMapServiceUnavailable struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this upload source map service unavailable response has a 2xx status code
func (o *UploadSourceMapServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this upload source map service unavailable response has a 3xx status code
func (o *UploadSourceMapServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this upload source map service unavailable response has a 4xx status code
func (o *UploadSourceMapServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this upload source map service unavailable response has a 5xx status code
func (o *UploadSourceMapServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this upload source map service unavailable response a status code equal to that given
func (o *UploadSourceMapServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the upload source map service unavailable response
func (o *UploadSourceMapServiceUnavailable) Code() int {
	return 503
}

func (o *UploadSourceMapServiceUnavailable) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/rum/sourcemaps][%d] uploadSourceMapServiceUnavailable %s", 503, payload)
}

func (o *UploadSourceMapServiceUnavailable) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/rum/sourcemaps][%d] uploadSourceMapServiceUnavailable %s", 503, payload)
}

func (o *UploadSourceMapServiceUnavailable) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *UploadSourceMapServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
