// Code generated by go-swagger; DO NOT EDIT.

package secret

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DeleteSecretReader is a Reader for the DeleteSecret structure.
type DeleteSecretReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteSecretReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteSecretNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteSecretBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteSecretNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteSecretInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /api/secret/{id}] deleteSecret", response, response.Code())
	}
}

// NewDeleteSecretNoContent creates a DeleteSecretNoContent with default headers values
func NewDeleteSecretNoContent() *DeleteSecretNoContent {
	return &DeleteSecretNoContent{}
}

/*
DeleteSecretNoContent describes a response with status code 204, with default header values.

NoContentResponse indicates success but that no response body is expected or included.
*/
type DeleteSecretNoContent struct {
}

// IsSuccess returns true when this delete secret no content response has a 2xx status code
func (o *DeleteSecretNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete secret no content response has a 3xx status code
func (o *DeleteSecretNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete secret no content response has a 4xx status code
func (o *DeleteSecretNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete secret no content response has a 5xx status code
func (o *DeleteSecretNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete secret no content response a status code equal to that given
func (o *DeleteSecretNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the delete secret no content response
func (o *DeleteSecretNoContent) Code() int {
	return 204
}

func (o *DeleteSecretNoContent) Error() string {
	return fmt.Sprintf("[DELETE /api/secret/{id}][%d] deleteSecretNoContent", 204)
}

func (o *DeleteSecretNoContent) String() string {
	return fmt.Sprintf("[DELETE /api/secret/{id}][%d] deleteSecretNoContent", 204)
}

func (o *DeleteSecretNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteSecretBadRequest creates a DeleteSecretBadRequest with default headers values
func NewDeleteSecretBadRequest() *DeleteSecretBadRequest {
	return &DeleteSecretBadRequest{}
}

/*
DeleteSecretBadRequest describes a response with status code 400, with default header values.

ErrorResponse defines a common error response structure.
*/
type DeleteSecretBadRequest struct {
	Payload *DeleteSecretBadRequestBody
}

// IsSuccess returns true when this delete secret bad request response has a 2xx status code
func (o *DeleteSecretBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete secret bad request response has a 3xx status code
func (o *DeleteSecretBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete secret bad request response has a 4xx status code
func (o *DeleteSecretBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete secret bad request response has a 5xx status code
func (o *DeleteSecretBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this delete secret bad request response a status code equal to that given
func (o *DeleteSecretBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the delete secret bad request response
func (o *DeleteSecretBadRequest) Code() int {
	return 400
}

func (o *DeleteSecretBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/secret/{id}][%d] deleteSecretBadRequest %s", 400, payload)
}

func (o *DeleteSecretBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/secret/{id}][%d] deleteSecretBadRequest %s", 400, payload)
}

func (o *DeleteSecretBadRequest) GetPayload() *DeleteSecretBadRequestBody {
	return o.Payload
}

func (o *DeleteSecretBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(DeleteSecretBadRequestBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteSecretNotFound creates a DeleteSecretNotFound with default headers values
func NewDeleteSecretNotFound() *DeleteSecretNotFound {
	return &DeleteSecretNotFound{}
}

/*
DeleteSecretNotFound describes a response with status code 404, with default header values.

ErrorResponse defines a common error response structure.
*/
type DeleteSecretNotFound struct {
	Payload *DeleteSecretNotFoundBody
}

// IsSuccess returns true when this delete secret not found response has a 2xx status code
func (o *DeleteSecretNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete secret not found response has a 3xx status code
func (o *DeleteSecretNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete secret not found response has a 4xx status code
func (o *DeleteSecretNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete secret not found response has a 5xx status code
func (o *DeleteSecretNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete secret not found response a status code equal to that given
func (o *DeleteSecretNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the delete secret not found response
func (o *DeleteSecretNotFound) Code() int {
	return 404
}

func (o *DeleteSecretNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/secret/{id}][%d] deleteSecretNotFound %s", 404, payload)
}

func (o *DeleteSecretNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/secret/{id}][%d] deleteSecretNotFound %s", 404, payload)
}

func (o *DeleteSecretNotFound) GetPayload() *DeleteSecretNotFoundBody {
	return o.Payload
}

func (o *DeleteSecretNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(DeleteSecretNotFoundBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteSecretInternalServerError creates a DeleteSecretInternalServerError with default headers values
func NewDeleteSecretInternalServerError() *DeleteSecretInternalServerError {
	return &DeleteSecretInternalServerError{}
}

/*
DeleteSecretInternalServerError describes a response with status code 500, with default header values.

ErrorResponse defines a common error response structure.
*/
type DeleteSecretInternalServerError struct {
	Payload *DeleteSecretInternalServerErrorBody
}

// IsSuccess returns true when this delete secret internal server error response has a 2xx status code
func (o *DeleteSecretInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete secret internal server error response has a 3xx status code
func (o *DeleteSecretInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete secret internal server error response has a 4xx status code
func (o *DeleteSecretInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete secret internal server error response has a 5xx status code
func (o *DeleteSecretInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this delete secret internal server error response a status code equal to that given
func (o *DeleteSecretInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the delete secret internal server error response
func (o *DeleteSecretInternalServerError) Code() int {
	return 500
}

func (o *DeleteSecretInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/secret/{id}][%d] deleteSecretInternalServerError %s", 500, payload)
}

func (o *DeleteSecretInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/secret/{id}][%d] deleteSecretInternalServerError %s", 500, payload)
}

func (o *DeleteSecretInternalServerError) GetPayload() *DeleteSecretInternalServerErrorBody {
	return o.Payload
}

func (o *DeleteSecretInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(DeleteSecretInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
DeleteSecretBadRequestBody delete secret bad request body
swagger:model DeleteSecretBadRequestBody
*/
type DeleteSecretBadRequestBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this delete secret bad request body
func (o *DeleteSecretBadRequestBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this delete secret bad request body based on context it is used
func (o *DeleteSecretBadRequestBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteSecretBadRequestBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteSecretBadRequestBody) UnmarshalBinary(b []byte) error {
	var res DeleteSecretBadRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
DeleteSecretInternalServerErrorBody delete secret internal server error body
swagger:model DeleteSecretInternalServerErrorBody
*/
type DeleteSecretInternalServerErrorBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this delete secret internal server error body
func (o *DeleteSecretInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this delete secret internal server error body based on context it is used
func (o *DeleteSecretInternalServerErrorBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteSecretInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteSecretInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res DeleteSecretInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
DeleteSecretNotFoundBody delete secret not found body
swagger:model DeleteSecretNotFoundBody
*/
type DeleteSecretNotFoundBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this delete secret not found body
func (o *DeleteSecretNotFoundBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this delete secret not found body based on context it is used
func (o *DeleteSecretNotFoundBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteSecretNotFoundBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteSecretNotFoundBody) UnmarshalBinary(b []byte) error {
	var res DeleteSecretNotFoundBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
