// Code generated by go-swagger; DO NOT EDIT.

package notification_routes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DeleteNotificationRouteReader is a Reader for the DeleteNotificationRoute structure.
type DeleteNotificationRouteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteNotificationRouteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteNotificationRouteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewDeleteNotificationRouteNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteNotificationRouteInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /api/notification-routes/v1/{id}] deleteNotificationRoute", response, response.Code())
	}
}

// NewDeleteNotificationRouteNoContent creates a DeleteNotificationRouteNoContent with default headers values
func NewDeleteNotificationRouteNoContent() *DeleteNotificationRouteNoContent {
	return &DeleteNotificationRouteNoContent{}
}

/*
DeleteNotificationRouteNoContent describes a response with status code 204, with default header values.

DeleteNotificationRouteNoContent delete notification route no content
*/
type DeleteNotificationRouteNoContent struct {
}

// IsSuccess returns true when this delete notification route no content response has a 2xx status code
func (o *DeleteNotificationRouteNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete notification route no content response has a 3xx status code
func (o *DeleteNotificationRouteNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete notification route no content response has a 4xx status code
func (o *DeleteNotificationRouteNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete notification route no content response has a 5xx status code
func (o *DeleteNotificationRouteNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete notification route no content response a status code equal to that given
func (o *DeleteNotificationRouteNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the delete notification route no content response
func (o *DeleteNotificationRouteNoContent) Code() int {
	return 204
}

func (o *DeleteNotificationRouteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /api/notification-routes/v1/{id}][%d] deleteNotificationRouteNoContent", 204)
}

func (o *DeleteNotificationRouteNoContent) String() string {
	return fmt.Sprintf("[DELETE /api/notification-routes/v1/{id}][%d] deleteNotificationRouteNoContent", 204)
}

func (o *DeleteNotificationRouteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteNotificationRouteNotFound creates a DeleteNotificationRouteNotFound with default headers values
func NewDeleteNotificationRouteNotFound() *DeleteNotificationRouteNotFound {
	return &DeleteNotificationRouteNotFound{}
}

/*
DeleteNotificationRouteNotFound describes a response with status code 404, with default header values.

ErrorResponse defines a common error response structure.
*/
type DeleteNotificationRouteNotFound struct {
	Payload *DeleteNotificationRouteNotFoundBody
}

// IsSuccess returns true when this delete notification route not found response has a 2xx status code
func (o *DeleteNotificationRouteNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete notification route not found response has a 3xx status code
func (o *DeleteNotificationRouteNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete notification route not found response has a 4xx status code
func (o *DeleteNotificationRouteNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete notification route not found response has a 5xx status code
func (o *DeleteNotificationRouteNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete notification route not found response a status code equal to that given
func (o *DeleteNotificationRouteNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the delete notification route not found response
func (o *DeleteNotificationRouteNotFound) Code() int {
	return 404
}

func (o *DeleteNotificationRouteNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/notification-routes/v1/{id}][%d] deleteNotificationRouteNotFound %s", 404, payload)
}

func (o *DeleteNotificationRouteNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/notification-routes/v1/{id}][%d] deleteNotificationRouteNotFound %s", 404, payload)
}

func (o *DeleteNotificationRouteNotFound) GetPayload() *DeleteNotificationRouteNotFoundBody {
	return o.Payload
}

func (o *DeleteNotificationRouteNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(DeleteNotificationRouteNotFoundBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteNotificationRouteInternalServerError creates a DeleteNotificationRouteInternalServerError with default headers values
func NewDeleteNotificationRouteInternalServerError() *DeleteNotificationRouteInternalServerError {
	return &DeleteNotificationRouteInternalServerError{}
}

/*
DeleteNotificationRouteInternalServerError describes a response with status code 500, with default header values.

ErrorResponse defines a common error response structure.
*/
type DeleteNotificationRouteInternalServerError struct {
	Payload *DeleteNotificationRouteInternalServerErrorBody
}

// IsSuccess returns true when this delete notification route internal server error response has a 2xx status code
func (o *DeleteNotificationRouteInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete notification route internal server error response has a 3xx status code
func (o *DeleteNotificationRouteInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete notification route internal server error response has a 4xx status code
func (o *DeleteNotificationRouteInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete notification route internal server error response has a 5xx status code
func (o *DeleteNotificationRouteInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this delete notification route internal server error response a status code equal to that given
func (o *DeleteNotificationRouteInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the delete notification route internal server error response
func (o *DeleteNotificationRouteInternalServerError) Code() int {
	return 500
}

func (o *DeleteNotificationRouteInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/notification-routes/v1/{id}][%d] deleteNotificationRouteInternalServerError %s", 500, payload)
}

func (o *DeleteNotificationRouteInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/notification-routes/v1/{id}][%d] deleteNotificationRouteInternalServerError %s", 500, payload)
}

func (o *DeleteNotificationRouteInternalServerError) GetPayload() *DeleteNotificationRouteInternalServerErrorBody {
	return o.Payload
}

func (o *DeleteNotificationRouteInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(DeleteNotificationRouteInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
DeleteNotificationRouteInternalServerErrorBody delete notification route internal server error body
swagger:model DeleteNotificationRouteInternalServerErrorBody
*/
type DeleteNotificationRouteInternalServerErrorBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this delete notification route internal server error body
func (o *DeleteNotificationRouteInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this delete notification route internal server error body based on context it is used
func (o *DeleteNotificationRouteInternalServerErrorBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteNotificationRouteInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteNotificationRouteInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res DeleteNotificationRouteInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
DeleteNotificationRouteNotFoundBody delete notification route not found body
swagger:model DeleteNotificationRouteNotFoundBody
*/
type DeleteNotificationRouteNotFoundBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this delete notification route not found body
func (o *DeleteNotificationRouteNotFoundBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this delete notification route not found body based on context it is used
func (o *DeleteNotificationRouteNotFoundBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteNotificationRouteNotFoundBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteNotificationRouteNotFoundBody) UnmarshalBinary(b []byte) error {
	var res DeleteNotificationRouteNotFoundBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
