// Code generated by go-swagger; DO NOT EDIT.

package notification_routes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/groundcover-com/groundcover-sdk-go/pkg/models"
)

// GetNotificationRouteReader is a Reader for the GetNotificationRoute structure.
type GetNotificationRouteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetNotificationRouteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetNotificationRouteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetNotificationRouteNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetNotificationRouteInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/notification-routes/v1/{id}] getNotificationRoute", response, response.Code())
	}
}

// NewGetNotificationRouteOK creates a GetNotificationRouteOK with default headers values
func NewGetNotificationRouteOK() *GetNotificationRouteOK {
	return &GetNotificationRouteOK{}
}

/*
GetNotificationRouteOK describes a response with status code 200, with default header values.

GetNotificationRouteOK get notification route o k
*/
type GetNotificationRouteOK struct {
	Payload *models.NotificationRouteResponse
}

// IsSuccess returns true when this get notification route o k response has a 2xx status code
func (o *GetNotificationRouteOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get notification route o k response has a 3xx status code
func (o *GetNotificationRouteOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get notification route o k response has a 4xx status code
func (o *GetNotificationRouteOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get notification route o k response has a 5xx status code
func (o *GetNotificationRouteOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get notification route o k response a status code equal to that given
func (o *GetNotificationRouteOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get notification route o k response
func (o *GetNotificationRouteOK) Code() int {
	return 200
}

func (o *GetNotificationRouteOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/notification-routes/v1/{id}][%d] getNotificationRouteOK %s", 200, payload)
}

func (o *GetNotificationRouteOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/notification-routes/v1/{id}][%d] getNotificationRouteOK %s", 200, payload)
}

func (o *GetNotificationRouteOK) GetPayload() *models.NotificationRouteResponse {
	return o.Payload
}

func (o *GetNotificationRouteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NotificationRouteResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetNotificationRouteNotFound creates a GetNotificationRouteNotFound with default headers values
func NewGetNotificationRouteNotFound() *GetNotificationRouteNotFound {
	return &GetNotificationRouteNotFound{}
}

/*
GetNotificationRouteNotFound describes a response with status code 404, with default header values.

ErrorResponse defines a common error response structure.
*/
type GetNotificationRouteNotFound struct {
	Payload *GetNotificationRouteNotFoundBody
}

// IsSuccess returns true when this get notification route not found response has a 2xx status code
func (o *GetNotificationRouteNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get notification route not found response has a 3xx status code
func (o *GetNotificationRouteNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get notification route not found response has a 4xx status code
func (o *GetNotificationRouteNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get notification route not found response has a 5xx status code
func (o *GetNotificationRouteNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get notification route not found response a status code equal to that given
func (o *GetNotificationRouteNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get notification route not found response
func (o *GetNotificationRouteNotFound) Code() int {
	return 404
}

func (o *GetNotificationRouteNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/notification-routes/v1/{id}][%d] getNotificationRouteNotFound %s", 404, payload)
}

func (o *GetNotificationRouteNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/notification-routes/v1/{id}][%d] getNotificationRouteNotFound %s", 404, payload)
}

func (o *GetNotificationRouteNotFound) GetPayload() *GetNotificationRouteNotFoundBody {
	return o.Payload
}

func (o *GetNotificationRouteNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetNotificationRouteNotFoundBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetNotificationRouteInternalServerError creates a GetNotificationRouteInternalServerError with default headers values
func NewGetNotificationRouteInternalServerError() *GetNotificationRouteInternalServerError {
	return &GetNotificationRouteInternalServerError{}
}

/*
GetNotificationRouteInternalServerError describes a response with status code 500, with default header values.

ErrorResponse defines a common error response structure.
*/
type GetNotificationRouteInternalServerError struct {
	Payload *GetNotificationRouteInternalServerErrorBody
}

// IsSuccess returns true when this get notification route internal server error response has a 2xx status code
func (o *GetNotificationRouteInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get notification route internal server error response has a 3xx status code
func (o *GetNotificationRouteInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get notification route internal server error response has a 4xx status code
func (o *GetNotificationRouteInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get notification route internal server error response has a 5xx status code
func (o *GetNotificationRouteInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get notification route internal server error response a status code equal to that given
func (o *GetNotificationRouteInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get notification route internal server error response
func (o *GetNotificationRouteInternalServerError) Code() int {
	return 500
}

func (o *GetNotificationRouteInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/notification-routes/v1/{id}][%d] getNotificationRouteInternalServerError %s", 500, payload)
}

func (o *GetNotificationRouteInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/notification-routes/v1/{id}][%d] getNotificationRouteInternalServerError %s", 500, payload)
}

func (o *GetNotificationRouteInternalServerError) GetPayload() *GetNotificationRouteInternalServerErrorBody {
	return o.Payload
}

func (o *GetNotificationRouteInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetNotificationRouteInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
GetNotificationRouteInternalServerErrorBody get notification route internal server error body
swagger:model GetNotificationRouteInternalServerErrorBody
*/
type GetNotificationRouteInternalServerErrorBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this get notification route internal server error body
func (o *GetNotificationRouteInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get notification route internal server error body based on context it is used
func (o *GetNotificationRouteInternalServerErrorBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetNotificationRouteInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetNotificationRouteInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res GetNotificationRouteInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
GetNotificationRouteNotFoundBody get notification route not found body
swagger:model GetNotificationRouteNotFoundBody
*/
type GetNotificationRouteNotFoundBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this get notification route not found body
func (o *GetNotificationRouteNotFoundBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get notification route not found body based on context it is used
func (o *GetNotificationRouteNotFoundBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetNotificationRouteNotFoundBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetNotificationRouteNotFoundBody) UnmarshalBinary(b []byte) error {
	var res GetNotificationRouteNotFoundBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
