// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ConnectedAppDeliveryOptions ConnectedAppDeliveryOptions carries per-app delivery options for direct-to-connected-app
// monitor notifications. Fields are app-type specific; unrelated fields are ignored.
//
// swagger:model ConnectedAppDeliveryOptions
type ConnectedAppDeliveryOptions struct {

	// Channels lists Slack channel IDs to post to (slack-app connected apps).
	// Multiple channels result in one notification per channel via dispatch-center fanout.
	Channels []string `json:"channels"`
}

// Validate validates this connected app delivery options
func (m *ConnectedAppDeliveryOptions) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this connected app delivery options based on context it is used
func (m *ConnectedAppDeliveryOptions) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ConnectedAppDeliveryOptions) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConnectedAppDeliveryOptions) UnmarshalBinary(b []byte) error {
	var res ConnectedAppDeliveryOptions
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
