// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateDashboardRequest create dashboard request
//
// swagger:model CreateDashboardRequest
type CreateDashboardRequest struct {

	// description
	Description string `json:"description,omitempty"`

	// is provisioned
	IsProvisioned bool `json:"isProvisioned,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// preset
	Preset string `json:"preset,omitempty"`

	// team
	Team string `json:"team,omitempty"`
}

// Validate validates this create dashboard request
func (m *CreateDashboardRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create dashboard request based on context it is used
func (m *CreateDashboardRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateDashboardRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateDashboardRequest) UnmarshalBinary(b []byte) error {
	var res CreateDashboardRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
