// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateServiceAccountResponse create service account response
//
// swagger:model CreateServiceAccountResponse
type CreateServiceAccountResponse struct {

	// body
	Body *CreateServiceAccountResponseBody `json:"Body,omitempty"`
}

// Validate validates this create service account response
func (m *CreateServiceAccountResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBody(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateServiceAccountResponse) validateBody(formats strfmt.Registry) error {
	if swag.IsZero(m.Body) { // not required
		return nil
	}

	if m.Body != nil {
		if err := m.Body.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Body")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("Body")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this create service account response based on the context it is used
func (m *CreateServiceAccountResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateBody(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateServiceAccountResponse) contextValidateBody(ctx context.Context, formats strfmt.Registry) error {

	if m.Body != nil {

		if swag.IsZero(m.Body) { // not required
			return nil
		}

		if err := m.Body.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Body")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("Body")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CreateServiceAccountResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateServiceAccountResponse) UnmarshalBinary(b []byte) error {
	var res CreateServiceAccountResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// CreateServiceAccountResponseBody The UUID of the created service account.
// in: body
//
// swagger:model CreateServiceAccountResponseBody
type CreateServiceAccountResponseBody struct {

	// The UUID of the created service account.
	// Required: true
	ServiceAccountID *string `json:"serviceAccountId"`
}

// Validate validates this create service account response body
func (m *CreateServiceAccountResponseBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateServiceAccountID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateServiceAccountResponseBody) validateServiceAccountID(formats strfmt.Registry) error {

	if err := validate.Required("Body"+"."+"serviceAccountId", "body", m.ServiceAccountID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this create service account response body based on context it is used
func (m *CreateServiceAccountResponseBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateServiceAccountResponseBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateServiceAccountResponseBody) UnmarshalBinary(b []byte) error {
	var res CreateServiceAccountResponseBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
