// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateConnectedAppRequest CreateConnectedAppRequest is the request body for creating a new connected app.
//
// swagger:model CreateConnectedAppRequest
type CreateConnectedAppRequest struct {

	// The connected app-specific data. Schema depends on the 'type' field:
	// For type "slack-webhook": use SlackWebhookData schema
	// For type "pagerduty": use PagerDutyData schema
	// For type "opsgenie": use OpsGenieData schema
	// For type "incidentio": use IncidentIOData schema
	// For type "webhook": use WebhookData schema ({"url": "https://...", "method": "POST", "headers": {...}, "auth_type": "bearer", "api_key": "..."})
	// Required: true
	Data map[string]any `json:"data"`

	// The name of the connected app
	// Example: my-slack-app
	// Required: true
	Name *string `json:"name"`

	// The type of the connected app
	// Example: slack-webhook
	// Required: true
	// Enum: ["slack-webhook","pagerduty","opsgenie","incidentio","webhook"]
	Type *string `json:"type"`
}

// Validate validates this create connected app request
func (m *CreateConnectedAppRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateData(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateConnectedAppRequest) validateData(formats strfmt.Registry) error {

	if err := validate.Required("data", "body", m.Data); err != nil {
		return err
	}

	for k := range m.Data {

		if err := validate.Required("data"+"."+k, "body", m.Data[k]); err != nil {
			return err
		}

	}

	return nil
}

func (m *CreateConnectedAppRequest) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

var createConnectedAppRequestTypeTypePropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["slack-webhook","pagerduty","opsgenie","incidentio","webhook"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		createConnectedAppRequestTypeTypePropEnum = append(createConnectedAppRequestTypeTypePropEnum, v)
	}
}

const (

	// CreateConnectedAppRequestTypeSlackDashWebhook captures enum value "slack-webhook"
	CreateConnectedAppRequestTypeSlackDashWebhook string = "slack-webhook"

	// CreateConnectedAppRequestTypePagerduty captures enum value "pagerduty"
	CreateConnectedAppRequestTypePagerduty string = "pagerduty"

	// CreateConnectedAppRequestTypeOpsgenie captures enum value "opsgenie"
	CreateConnectedAppRequestTypeOpsgenie string = "opsgenie"

	// CreateConnectedAppRequestTypeIncidentio captures enum value "incidentio"
	CreateConnectedAppRequestTypeIncidentio string = "incidentio"

	// CreateConnectedAppRequestTypeWebhook captures enum value "webhook"
	CreateConnectedAppRequestTypeWebhook string = "webhook"
)

// prop value enum
func (m *CreateConnectedAppRequest) validateTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, createConnectedAppRequestTypeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *CreateConnectedAppRequest) validateType(formats strfmt.Registry) error {

	if err := validate.Required("type", "body", m.Type); err != nil {
		return err
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", *m.Type); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this create connected app request based on context it is used
func (m *CreateConnectedAppRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateConnectedAppRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateConnectedAppRequest) UnmarshalBinary(b []byte) error {
	var res CreateConnectedAppRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
