// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateConnectedAppResponse create connected app response
//
// swagger:model CreateConnectedAppResponse
type CreateConnectedAppResponse struct {

	// The ID of the created connected app
	// Example: 1a2b-3c4d
	ID string `json:"id,omitempty"`

	// The type of the connected app
	// Example: slack-webhook
	Type string `json:"type,omitempty"`
}

// Validate validates this create connected app response
func (m *CreateConnectedAppResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create connected app response based on context it is used
func (m *CreateConnectedAppResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateConnectedAppResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateConnectedAppResponse) UnmarshalBinary(b []byte) error {
	var res CreateConnectedAppResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
