// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CustomResolveThreshold CustomResolveThreshold defines a hysteresis recovery condition for a Threshold.
//
// The Operator must be the directional opposite of the parent Threshold.Operator
// and Values must not overlap the firing range (e.g. fire above 100, recover below 80).
// This maps to Grafana's "Custom recovery threshold" (unloadEvaluator) on the
// threshold expression node.
//
// swagger:model CustomResolveThreshold
type CustomResolveThreshold struct {

	// Comparison operator for recovery. Must be the directional opposite of the
	// parent threshold's Operator.
	// Required: true
	// Enum: ["gt","lt","within_range","outside_range"]
	Operator *string `json:"operator"`

	// Resolve values (one for gt/lt, two for range operators). Must not overlap
	// the firing values — see validateCustomResolveThreshold for the exact rules.
	// Required: true
	Values []float64 `json:"values"`
}

// Validate validates this custom resolve threshold
func (m *CustomResolveThreshold) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOperator(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValues(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var customResolveThresholdTypeOperatorPropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["gt","lt","within_range","outside_range"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		customResolveThresholdTypeOperatorPropEnum = append(customResolveThresholdTypeOperatorPropEnum, v)
	}
}

const (

	// CustomResolveThresholdOperatorGt captures enum value "gt"
	CustomResolveThresholdOperatorGt string = "gt"

	// CustomResolveThresholdOperatorLt captures enum value "lt"
	CustomResolveThresholdOperatorLt string = "lt"

	// CustomResolveThresholdOperatorWithinRange captures enum value "within_range"
	CustomResolveThresholdOperatorWithinRange string = "within_range"

	// CustomResolveThresholdOperatorOutsideRange captures enum value "outside_range"
	CustomResolveThresholdOperatorOutsideRange string = "outside_range"
)

// prop value enum
func (m *CustomResolveThreshold) validateOperatorEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, customResolveThresholdTypeOperatorPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *CustomResolveThreshold) validateOperator(formats strfmt.Registry) error {

	if err := validate.Required("operator", "body", m.Operator); err != nil {
		return err
	}

	// value enum
	if err := m.validateOperatorEnum("operator", "body", *m.Operator); err != nil {
		return err
	}

	return nil
}

func (m *CustomResolveThreshold) validateValues(formats strfmt.Registry) error {

	if err := validate.Required("values", "body", m.Values); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this custom resolve threshold based on context it is used
func (m *CustomResolveThreshold) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CustomResolveThreshold) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CustomResolveThreshold) UnmarshalBinary(b []byte) error {
	var res CustomResolveThreshold
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
