// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DNSRequest DnsRequest defines model for DnsRequest.
//
// swagger:model DnsRequest
type DNSRequest struct {

	// dnssec
	Dnssec bool `json:"dnssec,omitempty"`

	// domain
	Domain string `json:"domain,omitempty"`

	// port
	Port int64 `json:"port,omitempty"`

	// resolver
	Resolver string `json:"resolver,omitempty"`

	// timeout
	Timeout string `json:"timeout,omitempty"`

	// kind
	Kind DNSRequestKind `json:"kind,omitempty"`

	// record type
	RecordType DNSRequestRecordType `json:"recordType,omitempty"`
}

// Validate validates this Dns request
func (m *DNSRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateKind(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRecordType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DNSRequest) validateKind(formats strfmt.Registry) error {
	if swag.IsZero(m.Kind) { // not required
		return nil
	}

	if err := m.Kind.Validate(formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("kind")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("kind")
		}

		return err
	}

	return nil
}

func (m *DNSRequest) validateRecordType(formats strfmt.Registry) error {
	if swag.IsZero(m.RecordType) { // not required
		return nil
	}

	if err := m.RecordType.Validate(formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("recordType")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("recordType")
		}

		return err
	}

	return nil
}

// ContextValidate validate this Dns request based on the context it is used
func (m *DNSRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateKind(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateRecordType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DNSRequest) contextValidateKind(ctx context.Context, formats strfmt.Registry) error {

	if swag.IsZero(m.Kind) { // not required
		return nil
	}

	if err := m.Kind.ContextValidate(ctx, formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("kind")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("kind")
		}

		return err
	}

	return nil
}

func (m *DNSRequest) contextValidateRecordType(ctx context.Context, formats strfmt.Registry) error {

	if swag.IsZero(m.RecordType) { // not required
		return nil
	}

	if err := m.RecordType.ContextValidate(ctx, formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("recordType")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("recordType")
		}

		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DNSRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DNSRequest) UnmarshalBinary(b []byte) error {
	var res DNSRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
