// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ListConnectedAppsRequest list connected apps request
//
// swagger:model ListConnectedAppsRequest
type ListConnectedAppsRequest struct {

	// gcQL query to filter connected apps
	// Supports freetext search on name, type:<type>, and notification_route:<route-name>
	// Example: \"best type:slack-webhook notification_route:prod-alerts\
	Query string `json:"query,omitempty"`
}

// Validate validates this list connected apps request
func (m *ListConnectedAppsRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this list connected apps request based on context it is used
func (m *ListConnectedAppsRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ListConnectedAppsRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ListConnectedAppsRequest) UnmarshalBinary(b []byte) error {
	var res ListConnectedAppsRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
