// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RelabelConfig relabel config
//
// swagger:model RelabelConfig
type RelabelConfig struct {

	// add label
	AddLabel map[string]string `json:"addLabel,omitempty"`

	// drop regex
	DropRegex []string `json:"dropRegex"`

	// keep regex
	KeepRegex []string `json:"keepRegex"`

	// raw
	Raw string `json:"raw,omitempty"`

	// remove label
	RemoveLabel []string `json:"removeLabel"`
}

// Validate validates this relabel config
func (m *RelabelConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this relabel config based on context it is used
func (m *RelabelConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RelabelConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RelabelConfig) UnmarshalBinary(b []byte) error {
	var res RelabelConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
