// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SecretResponse secret response
//
// swagger:model SecretResponse
type SecretResponse struct {

	// The unique identifier for the secret
	// Example: secretRef::store::a1b2c3d4e5f6
	ID string `json:"id,omitempty"`

	// The name of the secret
	// Example: my-api-key
	Name string `json:"name,omitempty"`

	// The type of the secret
	// Example: password
	Type string `json:"type,omitempty"`
}

// Validate validates this secret response
func (m *SecretResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this secret response based on context it is used
func (m *SecretResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SecretResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SecretResponse) UnmarshalBinary(b []byte) error {
	var res SecretResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
