// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SourceMapUploadResponse SourceMapUploadResponse is the JSON success body returned by the upload handler.
//
// swagger:model SourceMapUploadResponse
type SourceMapUploadResponse struct {

	// app ID
	AppID string `json:"app_id,omitempty"`

	// filename
	Filename string `json:"filename,omitempty"`

	// release ID
	ReleaseID string `json:"release_id,omitempty"`

	// size bytes
	SizeBytes int64 `json:"size_bytes,omitempty"`

	// status
	Status string `json:"status,omitempty"`
}

// Validate validates this source map upload response
func (m *SourceMapUploadResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this source map upload response based on context it is used
func (m *SourceMapUploadResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SourceMapUploadResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SourceMapUploadResponse) UnmarshalBinary(b []byte) error {
	var res SourceMapUploadResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
