// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SyntheticTestListItem synthetic test list item
//
// swagger:model SyntheticTestListItem
type SyntheticTestListItem struct {

	// creator
	Creator string `json:"creator,omitempty"`

	// Id
	ID string `json:"id,omitempty"`

	// interval
	Interval string `json:"interval,omitempty"`

	// last check latency
	LastCheckLatency string `json:"lastCheckLatency,omitempty"`

	// last check time
	LastCheckTime string `json:"lastCheckTime,omitempty"`

	// modified at
	ModifiedAt string `json:"modifiedAt,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// status
	Status string `json:"status,omitempty"`

	// synthetic type
	SyntheticType string `json:"syntheticType,omitempty"`

	// target
	Target string `json:"target,omitempty"`

	// monitor
	Monitor *SyntheticTestMonitor `json:"monitor,omitempty"`
}

// Validate validates this synthetic test list item
func (m *SyntheticTestListItem) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMonitor(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SyntheticTestListItem) validateMonitor(formats strfmt.Registry) error {
	if swag.IsZero(m.Monitor) { // not required
		return nil
	}

	if m.Monitor != nil {
		if err := m.Monitor.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("monitor")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("monitor")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this synthetic test list item based on the context it is used
func (m *SyntheticTestListItem) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateMonitor(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SyntheticTestListItem) contextValidateMonitor(ctx context.Context, formats strfmt.Registry) error {

	if m.Monitor != nil {

		if swag.IsZero(m.Monitor) { // not required
			return nil
		}

		if err := m.Monitor.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("monitor")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("monitor")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SyntheticTestListItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SyntheticTestListItem) UnmarshalBinary(b []byte) error {
	var res SyntheticTestListItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
