// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SyntheticTestCreateRequest synthetic test create request
//
// swagger:model SyntheticTestCreateRequest
type SyntheticTestCreateRequest struct {

	// Whether to create an associated monitor for this synthetic test.
	// On create, nil or true creates a monitor; false skips monitor creation.
	// On update, nil preserves current monitor state; true creates/keeps the monitor; false deletes it.
	// To create a monitor on a previously monitor-less synthetic, you must explicitly set createMonitor=true.
	// Providing a monitor block when createMonitor=false (or when no monitor exists and createMonitor is nil) returns 400.
	CreateMonitor *bool `json:"createMonitor,omitempty"`

	// enabled
	Enabled bool `json:"enabled,omitempty"`

	// Deprecated: Exporters field is no longer used but kept for backward compatibility
	// to prevent parsing errors from clients that still send it.
	Exporters []string `json:"exporters"`

	// interval
	Interval string `json:"interval,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// version
	Version int64 `json:"version,omitempty"`

	// check config
	CheckConfig *WorkerRequest `json:"checkConfig,omitempty"`

	// label settings
	LabelSettings *LabelSettings `json:"labelSettings,omitempty"`

	// monitor
	Monitor *SyntheticMonitorConfig `json:"monitor,omitempty"`
}

// Validate validates this synthetic test create request
func (m *SyntheticTestCreateRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCheckConfig(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLabelSettings(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMonitor(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SyntheticTestCreateRequest) validateCheckConfig(formats strfmt.Registry) error {
	if swag.IsZero(m.CheckConfig) { // not required
		return nil
	}

	if m.CheckConfig != nil {
		if err := m.CheckConfig.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("checkConfig")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("checkConfig")
			}

			return err
		}
	}

	return nil
}

func (m *SyntheticTestCreateRequest) validateLabelSettings(formats strfmt.Registry) error {
	if swag.IsZero(m.LabelSettings) { // not required
		return nil
	}

	if m.LabelSettings != nil {
		if err := m.LabelSettings.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("labelSettings")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("labelSettings")
			}

			return err
		}
	}

	return nil
}

func (m *SyntheticTestCreateRequest) validateMonitor(formats strfmt.Registry) error {
	if swag.IsZero(m.Monitor) { // not required
		return nil
	}

	if m.Monitor != nil {
		if err := m.Monitor.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("monitor")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("monitor")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this synthetic test create request based on the context it is used
func (m *SyntheticTestCreateRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCheckConfig(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateLabelSettings(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateMonitor(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SyntheticTestCreateRequest) contextValidateCheckConfig(ctx context.Context, formats strfmt.Registry) error {

	if m.CheckConfig != nil {

		if swag.IsZero(m.CheckConfig) { // not required
			return nil
		}

		if err := m.CheckConfig.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("checkConfig")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("checkConfig")
			}

			return err
		}
	}

	return nil
}

func (m *SyntheticTestCreateRequest) contextValidateLabelSettings(ctx context.Context, formats strfmt.Registry) error {

	if m.LabelSettings != nil {

		if swag.IsZero(m.LabelSettings) { // not required
			return nil
		}

		if err := m.LabelSettings.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("labelSettings")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("labelSettings")
			}

			return err
		}
	}

	return nil
}

func (m *SyntheticTestCreateRequest) contextValidateMonitor(ctx context.Context, formats strfmt.Registry) error {

	if m.Monitor != nil {

		if swag.IsZero(m.Monitor) { // not required
			return nil
		}

		if err := m.Monitor.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("monitor")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("monitor")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SyntheticTestCreateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SyntheticTestCreateRequest) UnmarshalBinary(b []byte) error {
	var res SyntheticTestCreateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
