// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Transform Transform represents a column transform that registers in the alias registry.
// Transforms don't create subqueries - they register handlers that resolve aliases to SQL expressions.
//
// Requirements by transform type:
// json_unpack: Args is optional (not used)
//
// swagger:model Transform
type Transform struct {

	// Alias is the name used to reference the transform result in subsequent pipes.
	// Required: true
	Alias *string `json:"alias"`

	// Args contains transform-specific arguments.
	Args []string `json:"args"`

	// SourceColumn is the column to transform.
	// Required: true
	SourceColumn *string `json:"sourceColumn"`

	// Type specifies the kind of transform to apply.
	// json_unpack TransformTypeJsonUnpack  TransformTypeJsonUnpack unpacks JSON fields with prefix matching
	// datetime_extract TransformTypeDatetimeExtract  TransformTypeDatetimeExtract extracts date/time parts from timestamps
	// Required: true
	// Enum: ["json_unpack","datetime_extract"]
	Type *string `json:"type"`
}

// Validate validates this transform
func (m *Transform) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAlias(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSourceColumn(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Transform) validateAlias(formats strfmt.Registry) error {

	if err := validate.Required("alias", "body", m.Alias); err != nil {
		return err
	}

	return nil
}

func (m *Transform) validateSourceColumn(formats strfmt.Registry) error {

	if err := validate.Required("sourceColumn", "body", m.SourceColumn); err != nil {
		return err
	}

	return nil
}

var transformTypeTypePropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["json_unpack","datetime_extract"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		transformTypeTypePropEnum = append(transformTypeTypePropEnum, v)
	}
}

const (

	// TransformTypeJSONUnpack captures enum value "json_unpack"
	TransformTypeJSONUnpack string = "json_unpack"

	// TransformTypeDatetimeExtract captures enum value "datetime_extract"
	TransformTypeDatetimeExtract string = "datetime_extract"
)

// prop value enum
func (m *Transform) validateTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, transformTypeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *Transform) validateType(formats strfmt.Registry) error {

	if err := validate.Required("type", "body", m.Type); err != nil {
		return err
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", *m.Type); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this transform based on context it is used
func (m *Transform) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Transform) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Transform) UnmarshalBinary(b []byte) error {
	var res Transform
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
