// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// UDPRequestKind UdpRequestKind defines model for UdpRequest.Kind.
//
// swagger:model UdpRequestKind
type UDPRequestKind string

// Validate validates this Udp request kind
func (m UDPRequestKind) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this Udp request kind based on context it is used
func (m UDPRequestKind) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
