// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Union Union defines a union operation between two pipelines (UNION ALL).
//
// swagger:model Union
type Union struct {

	// left pipeline
	LeftPipeline *SQLPipeline `json:"leftPipeline,omitempty"`

	// right pipeline
	RightPipeline *SQLPipeline `json:"rightPipeline,omitempty"`
}

// Validate validates this union
func (m *Union) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLeftPipeline(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRightPipeline(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Union) validateLeftPipeline(formats strfmt.Registry) error {
	if swag.IsZero(m.LeftPipeline) { // not required
		return nil
	}

	if m.LeftPipeline != nil {
		if err := m.LeftPipeline.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("leftPipeline")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("leftPipeline")
			}

			return err
		}
	}

	return nil
}

func (m *Union) validateRightPipeline(formats strfmt.Registry) error {
	if swag.IsZero(m.RightPipeline) { // not required
		return nil
	}

	if m.RightPipeline != nil {
		if err := m.RightPipeline.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("rightPipeline")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("rightPipeline")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this union based on the context it is used
func (m *Union) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateLeftPipeline(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateRightPipeline(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Union) contextValidateLeftPipeline(ctx context.Context, formats strfmt.Registry) error {

	if m.LeftPipeline != nil {

		if swag.IsZero(m.LeftPipeline) { // not required
			return nil
		}

		if err := m.LeftPipeline.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("leftPipeline")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("leftPipeline")
			}

			return err
		}
	}

	return nil
}

func (m *Union) contextValidateRightPipeline(ctx context.Context, formats strfmt.Registry) error {

	if m.RightPipeline != nil {

		if swag.IsZero(m.RightPipeline) { // not required
			return nil
		}

		if err := m.RightPipeline.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("rightPipeline")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("rightPipeline")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Union) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Union) UnmarshalBinary(b []byte) error {
	var res Union
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
