// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UpdateConnectedAppRequest UpdateConnectedAppRequest is the request body for updating an existing connected app.
//
// swagger:model UpdateConnectedAppRequest
type UpdateConnectedAppRequest struct {

	// The connected app-specific data. Schema depends on type field:
	// For type "slack-webhook": use SlackWebhookData schema
	// For type "pagerduty": use PagerDutyData schema
	// Required: true
	Data map[string]any `json:"data"`

	// The name of the connected app
	// Example: my-slack-app
	// Required: true
	Name *string `json:"name"`

	// The type of the connected app
	// Example: slack-webhook
	// Required: true
	// Enum: ["slack-webhook","pagerduty"]
	Type *string `json:"type"`
}

// Validate validates this update connected app request
func (m *UpdateConnectedAppRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateData(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UpdateConnectedAppRequest) validateData(formats strfmt.Registry) error {

	if err := validate.Required("data", "body", m.Data); err != nil {
		return err
	}

	for k := range m.Data {

		if err := validate.Required("data"+"."+k, "body", m.Data[k]); err != nil {
			return err
		}

	}

	return nil
}

func (m *UpdateConnectedAppRequest) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

var updateConnectedAppRequestTypeTypePropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["slack-webhook","pagerduty"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		updateConnectedAppRequestTypeTypePropEnum = append(updateConnectedAppRequestTypeTypePropEnum, v)
	}
}

const (

	// UpdateConnectedAppRequestTypeSlackDashWebhook captures enum value "slack-webhook"
	UpdateConnectedAppRequestTypeSlackDashWebhook string = "slack-webhook"

	// UpdateConnectedAppRequestTypePagerduty captures enum value "pagerduty"
	UpdateConnectedAppRequestTypePagerduty string = "pagerduty"
)

// prop value enum
func (m *UpdateConnectedAppRequest) validateTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, updateConnectedAppRequestTypeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *UpdateConnectedAppRequest) validateType(formats strfmt.Registry) error {

	if err := validate.Required("type", "body", m.Type); err != nil {
		return err
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", *m.Type); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this update connected app request based on context it is used
func (m *UpdateConnectedAppRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdateConnectedAppRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateConnectedAppRequest) UnmarshalBinary(b []byte) error {
	var res UpdateConnectedAppRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
