// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UsedByResponse used by response
//
// swagger:model UsedByResponse
type UsedByResponse struct {

	// The ID of the notification route or monitor
	ID string `json:"id,omitempty"`

	// The name of the notification route or monitor
	Name string `json:"name,omitempty"`

	// The type of the reference: "notification_route" or "monitor"
	Type string `json:"type,omitempty"`
}

// Validate validates this used by response
func (m *UsedByResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this used by response based on context it is used
func (m *UsedByResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UsedByResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UsedByResponse) UnmarshalBinary(b []byte) error {
	var res UsedByResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
