// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// WorkerRequestKind WorkerRequestKind Type of synthetic check to perform
//
// swagger:model WorkerRequestKind
type WorkerRequestKind string

// Validate validates this worker request kind
func (m WorkerRequestKind) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this worker request kind based on context it is used
func (m WorkerRequestKind) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
