// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// WorkerRequest WorkerRequest defines model for WorkerRequest.
//
// swagger:model WorkerRequest
type WorkerRequest struct {

	// execution policy
	ExecutionPolicy *ExecutionPolicy `json:"executionPolicy,omitempty"`

	// kind
	Kind WorkerRequestKind `json:"kind,omitempty"`

	// metadata
	Metadata *Metadata `json:"metadata,omitempty"`

	// request
	Request *Request `json:"request,omitempty"`

	// tracing
	Tracing *Tracing `json:"tracing,omitempty"`
}

// Validate validates this worker request
func (m *WorkerRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateExecutionPolicy(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateKind(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMetadata(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRequest(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTracing(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WorkerRequest) validateExecutionPolicy(formats strfmt.Registry) error {
	if swag.IsZero(m.ExecutionPolicy) { // not required
		return nil
	}

	if m.ExecutionPolicy != nil {
		if err := m.ExecutionPolicy.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("executionPolicy")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("executionPolicy")
			}

			return err
		}
	}

	return nil
}

func (m *WorkerRequest) validateKind(formats strfmt.Registry) error {
	if swag.IsZero(m.Kind) { // not required
		return nil
	}

	if err := m.Kind.Validate(formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("kind")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("kind")
		}

		return err
	}

	return nil
}

func (m *WorkerRequest) validateMetadata(formats strfmt.Registry) error {
	if swag.IsZero(m.Metadata) { // not required
		return nil
	}

	if m.Metadata != nil {
		if err := m.Metadata.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("metadata")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("metadata")
			}

			return err
		}
	}

	return nil
}

func (m *WorkerRequest) validateRequest(formats strfmt.Registry) error {
	if swag.IsZero(m.Request) { // not required
		return nil
	}

	if m.Request != nil {
		if err := m.Request.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("request")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("request")
			}

			return err
		}
	}

	return nil
}

func (m *WorkerRequest) validateTracing(formats strfmt.Registry) error {
	if swag.IsZero(m.Tracing) { // not required
		return nil
	}

	if m.Tracing != nil {
		if err := m.Tracing.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("tracing")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("tracing")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this worker request based on the context it is used
func (m *WorkerRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateExecutionPolicy(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateKind(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateMetadata(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateRequest(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTracing(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WorkerRequest) contextValidateExecutionPolicy(ctx context.Context, formats strfmt.Registry) error {

	if m.ExecutionPolicy != nil {

		if swag.IsZero(m.ExecutionPolicy) { // not required
			return nil
		}

		if err := m.ExecutionPolicy.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("executionPolicy")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("executionPolicy")
			}

			return err
		}
	}

	return nil
}

func (m *WorkerRequest) contextValidateKind(ctx context.Context, formats strfmt.Registry) error {

	if swag.IsZero(m.Kind) { // not required
		return nil
	}

	if err := m.Kind.ContextValidate(ctx, formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("kind")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("kind")
		}

		return err
	}

	return nil
}

func (m *WorkerRequest) contextValidateMetadata(ctx context.Context, formats strfmt.Registry) error {

	if m.Metadata != nil {

		if swag.IsZero(m.Metadata) { // not required
			return nil
		}

		if err := m.Metadata.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("metadata")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("metadata")
			}

			return err
		}
	}

	return nil
}

func (m *WorkerRequest) contextValidateRequest(ctx context.Context, formats strfmt.Registry) error {

	if m.Request != nil {

		if swag.IsZero(m.Request) { // not required
			return nil
		}

		if err := m.Request.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("request")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("request")
			}

			return err
		}
	}

	return nil
}

func (m *WorkerRequest) contextValidateTracing(ctx context.Context, formats strfmt.Registry) error {

	if m.Tracing != nil {

		if swag.IsZero(m.Tracing) { // not required
			return nil
		}

		if err := m.Tracing.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("tracing")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("tracing")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *WorkerRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WorkerRequest) UnmarshalBinary(b []byte) error {
	var res WorkerRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
