// Code generated by go-swagger; DO NOT EDIT.

package logs_pipeline

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/groundcover-com/groundcover-sdk-go/pkg/models"
)

// DeleteLogsPipelineConfigReader is a Reader for the DeleteLogsPipelineConfig structure.
type DeleteLogsPipelineConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteLogsPipelineConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteLogsPipelineConfigOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewDeleteLogsPipelineConfigInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewDeleteLogsPipelineConfigServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /api/pipelines/logs/config] deleteLogsPipelineConfig", response, response.Code())
	}
}

// NewDeleteLogsPipelineConfigOK creates a DeleteLogsPipelineConfigOK with default headers values
func NewDeleteLogsPipelineConfigOK() *DeleteLogsPipelineConfigOK {
	return &DeleteLogsPipelineConfigOK{}
}

/*
DeleteLogsPipelineConfigOK describes a response with status code 200, with default header values.

emptyLogsPipelineConfigResponse is used for empty responses
*/
type DeleteLogsPipelineConfigOK struct {
	Payload any
}

// IsSuccess returns true when this delete logs pipeline config o k response has a 2xx status code
func (o *DeleteLogsPipelineConfigOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete logs pipeline config o k response has a 3xx status code
func (o *DeleteLogsPipelineConfigOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete logs pipeline config o k response has a 4xx status code
func (o *DeleteLogsPipelineConfigOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete logs pipeline config o k response has a 5xx status code
func (o *DeleteLogsPipelineConfigOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete logs pipeline config o k response a status code equal to that given
func (o *DeleteLogsPipelineConfigOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete logs pipeline config o k response
func (o *DeleteLogsPipelineConfigOK) Code() int {
	return 200
}

func (o *DeleteLogsPipelineConfigOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/pipelines/logs/config][%d] deleteLogsPipelineConfigOK %s", 200, payload)
}

func (o *DeleteLogsPipelineConfigOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/pipelines/logs/config][%d] deleteLogsPipelineConfigOK %s", 200, payload)
}

func (o *DeleteLogsPipelineConfigOK) GetPayload() any {
	return o.Payload
}

func (o *DeleteLogsPipelineConfigOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteLogsPipelineConfigInternalServerError creates a DeleteLogsPipelineConfigInternalServerError with default headers values
func NewDeleteLogsPipelineConfigInternalServerError() *DeleteLogsPipelineConfigInternalServerError {
	return &DeleteLogsPipelineConfigInternalServerError{}
}

/*
DeleteLogsPipelineConfigInternalServerError describes a response with status code 500, with default header values.

logsPipelineErrorResponse is used for error responses
*/
type DeleteLogsPipelineConfigInternalServerError struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this delete logs pipeline config internal server error response has a 2xx status code
func (o *DeleteLogsPipelineConfigInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete logs pipeline config internal server error response has a 3xx status code
func (o *DeleteLogsPipelineConfigInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete logs pipeline config internal server error response has a 4xx status code
func (o *DeleteLogsPipelineConfigInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete logs pipeline config internal server error response has a 5xx status code
func (o *DeleteLogsPipelineConfigInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this delete logs pipeline config internal server error response a status code equal to that given
func (o *DeleteLogsPipelineConfigInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the delete logs pipeline config internal server error response
func (o *DeleteLogsPipelineConfigInternalServerError) Code() int {
	return 500
}

func (o *DeleteLogsPipelineConfigInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/pipelines/logs/config][%d] deleteLogsPipelineConfigInternalServerError %s", 500, payload)
}

func (o *DeleteLogsPipelineConfigInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/pipelines/logs/config][%d] deleteLogsPipelineConfigInternalServerError %s", 500, payload)
}

func (o *DeleteLogsPipelineConfigInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *DeleteLogsPipelineConfigInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteLogsPipelineConfigServiceUnavailable creates a DeleteLogsPipelineConfigServiceUnavailable with default headers values
func NewDeleteLogsPipelineConfigServiceUnavailable() *DeleteLogsPipelineConfigServiceUnavailable {
	return &DeleteLogsPipelineConfigServiceUnavailable{}
}

/*
DeleteLogsPipelineConfigServiceUnavailable describes a response with status code 503, with default header values.

logsPipelineErrorResponse is used for error responses
*/
type DeleteLogsPipelineConfigServiceUnavailable struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this delete logs pipeline config service unavailable response has a 2xx status code
func (o *DeleteLogsPipelineConfigServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete logs pipeline config service unavailable response has a 3xx status code
func (o *DeleteLogsPipelineConfigServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete logs pipeline config service unavailable response has a 4xx status code
func (o *DeleteLogsPipelineConfigServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete logs pipeline config service unavailable response has a 5xx status code
func (o *DeleteLogsPipelineConfigServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this delete logs pipeline config service unavailable response a status code equal to that given
func (o *DeleteLogsPipelineConfigServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the delete logs pipeline config service unavailable response
func (o *DeleteLogsPipelineConfigServiceUnavailable) Code() int {
	return 503
}

func (o *DeleteLogsPipelineConfigServiceUnavailable) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/pipelines/logs/config][%d] deleteLogsPipelineConfigServiceUnavailable %s", 503, payload)
}

func (o *DeleteLogsPipelineConfigServiceUnavailable) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/pipelines/logs/config][%d] deleteLogsPipelineConfigServiceUnavailable %s", 503, payload)
}

func (o *DeleteLogsPipelineConfigServiceUnavailable) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *DeleteLogsPipelineConfigServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
