// Code generated by go-swagger; DO NOT EDIT.

package logs_pipeline

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/groundcover-com/groundcover-sdk-go/pkg/models"
)

// GetLogsPipelineConfigReader is a Reader for the GetLogsPipelineConfig structure.
type GetLogsPipelineConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLogsPipelineConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetLogsPipelineConfigOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 204:
		result := NewGetLogsPipelineConfigNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetLogsPipelineConfigInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewGetLogsPipelineConfigServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/pipelines/logs/config] getLogsPipelineConfig", response, response.Code())
	}
}

// NewGetLogsPipelineConfigOK creates a GetLogsPipelineConfigOK with default headers values
func NewGetLogsPipelineConfigOK() *GetLogsPipelineConfigOK {
	return &GetLogsPipelineConfigOK{}
}

/*
GetLogsPipelineConfigOK describes a response with status code 200, with default header values.

logsPipelineConfigResponse contains a logs pipeline configuration entry
*/
type GetLogsPipelineConfigOK struct {
	Payload *models.LogsPipelineConfig
}

// IsSuccess returns true when this get logs pipeline config o k response has a 2xx status code
func (o *GetLogsPipelineConfigOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get logs pipeline config o k response has a 3xx status code
func (o *GetLogsPipelineConfigOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get logs pipeline config o k response has a 4xx status code
func (o *GetLogsPipelineConfigOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get logs pipeline config o k response has a 5xx status code
func (o *GetLogsPipelineConfigOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get logs pipeline config o k response a status code equal to that given
func (o *GetLogsPipelineConfigOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get logs pipeline config o k response
func (o *GetLogsPipelineConfigOK) Code() int {
	return 200
}

func (o *GetLogsPipelineConfigOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/pipelines/logs/config][%d] getLogsPipelineConfigOK %s", 200, payload)
}

func (o *GetLogsPipelineConfigOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/pipelines/logs/config][%d] getLogsPipelineConfigOK %s", 200, payload)
}

func (o *GetLogsPipelineConfigOK) GetPayload() *models.LogsPipelineConfig {
	return o.Payload
}

func (o *GetLogsPipelineConfigOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.LogsPipelineConfig)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetLogsPipelineConfigNoContent creates a GetLogsPipelineConfigNoContent with default headers values
func NewGetLogsPipelineConfigNoContent() *GetLogsPipelineConfigNoContent {
	return &GetLogsPipelineConfigNoContent{}
}

/*
GetLogsPipelineConfigNoContent describes a response with status code 204, with default header values.

emptyLogsPipelineConfigResponse is used for empty responses
*/
type GetLogsPipelineConfigNoContent struct {
	Payload any
}

// IsSuccess returns true when this get logs pipeline config no content response has a 2xx status code
func (o *GetLogsPipelineConfigNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get logs pipeline config no content response has a 3xx status code
func (o *GetLogsPipelineConfigNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get logs pipeline config no content response has a 4xx status code
func (o *GetLogsPipelineConfigNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this get logs pipeline config no content response has a 5xx status code
func (o *GetLogsPipelineConfigNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this get logs pipeline config no content response a status code equal to that given
func (o *GetLogsPipelineConfigNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the get logs pipeline config no content response
func (o *GetLogsPipelineConfigNoContent) Code() int {
	return 204
}

func (o *GetLogsPipelineConfigNoContent) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/pipelines/logs/config][%d] getLogsPipelineConfigNoContent %s", 204, payload)
}

func (o *GetLogsPipelineConfigNoContent) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/pipelines/logs/config][%d] getLogsPipelineConfigNoContent %s", 204, payload)
}

func (o *GetLogsPipelineConfigNoContent) GetPayload() any {
	return o.Payload
}

func (o *GetLogsPipelineConfigNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetLogsPipelineConfigInternalServerError creates a GetLogsPipelineConfigInternalServerError with default headers values
func NewGetLogsPipelineConfigInternalServerError() *GetLogsPipelineConfigInternalServerError {
	return &GetLogsPipelineConfigInternalServerError{}
}

/*
GetLogsPipelineConfigInternalServerError describes a response with status code 500, with default header values.

logsPipelineErrorResponse is used for error responses
*/
type GetLogsPipelineConfigInternalServerError struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this get logs pipeline config internal server error response has a 2xx status code
func (o *GetLogsPipelineConfigInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get logs pipeline config internal server error response has a 3xx status code
func (o *GetLogsPipelineConfigInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get logs pipeline config internal server error response has a 4xx status code
func (o *GetLogsPipelineConfigInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get logs pipeline config internal server error response has a 5xx status code
func (o *GetLogsPipelineConfigInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get logs pipeline config internal server error response a status code equal to that given
func (o *GetLogsPipelineConfigInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get logs pipeline config internal server error response
func (o *GetLogsPipelineConfigInternalServerError) Code() int {
	return 500
}

func (o *GetLogsPipelineConfigInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/pipelines/logs/config][%d] getLogsPipelineConfigInternalServerError %s", 500, payload)
}

func (o *GetLogsPipelineConfigInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/pipelines/logs/config][%d] getLogsPipelineConfigInternalServerError %s", 500, payload)
}

func (o *GetLogsPipelineConfigInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetLogsPipelineConfigInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetLogsPipelineConfigServiceUnavailable creates a GetLogsPipelineConfigServiceUnavailable with default headers values
func NewGetLogsPipelineConfigServiceUnavailable() *GetLogsPipelineConfigServiceUnavailable {
	return &GetLogsPipelineConfigServiceUnavailable{}
}

/*
GetLogsPipelineConfigServiceUnavailable describes a response with status code 503, with default header values.

logsPipelineErrorResponse is used for error responses
*/
type GetLogsPipelineConfigServiceUnavailable struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this get logs pipeline config service unavailable response has a 2xx status code
func (o *GetLogsPipelineConfigServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get logs pipeline config service unavailable response has a 3xx status code
func (o *GetLogsPipelineConfigServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get logs pipeline config service unavailable response has a 4xx status code
func (o *GetLogsPipelineConfigServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this get logs pipeline config service unavailable response has a 5xx status code
func (o *GetLogsPipelineConfigServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this get logs pipeline config service unavailable response a status code equal to that given
func (o *GetLogsPipelineConfigServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the get logs pipeline config service unavailable response
func (o *GetLogsPipelineConfigServiceUnavailable) Code() int {
	return 503
}

func (o *GetLogsPipelineConfigServiceUnavailable) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/pipelines/logs/config][%d] getLogsPipelineConfigServiceUnavailable %s", 503, payload)
}

func (o *GetLogsPipelineConfigServiceUnavailable) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/pipelines/logs/config][%d] getLogsPipelineConfigServiceUnavailable %s", 503, payload)
}

func (o *GetLogsPipelineConfigServiceUnavailable) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetLogsPipelineConfigServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
