// Code generated by go-swagger; DO NOT EDIT.

package logs_pipeline

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetLogsPipelineConfigParams creates a new GetLogsPipelineConfigParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetLogsPipelineConfigParams() *GetLogsPipelineConfigParams {
	return &GetLogsPipelineConfigParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetLogsPipelineConfigParamsWithTimeout creates a new GetLogsPipelineConfigParams object
// with the ability to set a timeout on a request.
func NewGetLogsPipelineConfigParamsWithTimeout(timeout time.Duration) *GetLogsPipelineConfigParams {
	return &GetLogsPipelineConfigParams{
		timeout: timeout,
	}
}

// NewGetLogsPipelineConfigParamsWithContext creates a new GetLogsPipelineConfigParams object
// with the ability to set a context for a request.
func NewGetLogsPipelineConfigParamsWithContext(ctx context.Context) *GetLogsPipelineConfigParams {
	return &GetLogsPipelineConfigParams{
		Context: ctx,
	}
}

// NewGetLogsPipelineConfigParamsWithHTTPClient creates a new GetLogsPipelineConfigParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetLogsPipelineConfigParamsWithHTTPClient(client *http.Client) *GetLogsPipelineConfigParams {
	return &GetLogsPipelineConfigParams{
		HTTPClient: client,
	}
}

/*
GetLogsPipelineConfigParams contains all the parameters to send to the API endpoint

	for the get logs pipeline config operation.

	Typically these are written to a http.Request.
*/
type GetLogsPipelineConfigParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get logs pipeline config params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetLogsPipelineConfigParams) WithDefaults() *GetLogsPipelineConfigParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get logs pipeline config params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetLogsPipelineConfigParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get logs pipeline config params
func (o *GetLogsPipelineConfigParams) WithTimeout(timeout time.Duration) *GetLogsPipelineConfigParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get logs pipeline config params
func (o *GetLogsPipelineConfigParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get logs pipeline config params
func (o *GetLogsPipelineConfigParams) WithContext(ctx context.Context) *GetLogsPipelineConfigParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get logs pipeline config params
func (o *GetLogsPipelineConfigParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get logs pipeline config params
func (o *GetLogsPipelineConfigParams) WithHTTPClient(client *http.Client) *GetLogsPipelineConfigParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get logs pipeline config params
func (o *GetLogsPipelineConfigParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetLogsPipelineConfigParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
