// Code generated by go-swagger; DO NOT EDIT.

package skills

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/groundcover-com/groundcover-sdk-go/pkg/models"
)

type responseReader struct {
	formats   strfmt.Registry
	operation string
	payload   any
	wrap      func(any) any
}

func (o *responseReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	if response.Code() != 200 {
		return nil, runtime.NewAPIError(o.operation, response, response.Code())
	}
	payload := o.payload
	if err := consumer.Consume(response.Body(), payload); err != nil && !stderrors.Is(err, io.EOF) {
		return nil, err
	}
	return o.wrap(payload), nil
}

type ListSkillsReader struct {
	formats strfmt.Registry
}

func (o *ListSkillsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	return (&responseReader{
		formats:   o.formats,
		operation: "[GET /api/agent/skills] listSkills",
		payload:   new(models.UserSkillsListResponse),
		wrap: func(payload any) any {
			return &ListSkillsOK{Payload: payload.(*models.UserSkillsListResponse)}
		},
	}).ReadResponse(response, consumer)
}

type ListSkillsOK struct {
	Payload *models.UserSkillsListResponse
}

func (o *ListSkillsOK) IsSuccess() bool     { return true }
func (o *ListSkillsOK) IsRedirect() bool    { return false }
func (o *ListSkillsOK) IsClientError() bool { return false }
func (o *ListSkillsOK) IsServerError() bool { return false }
func (o *ListSkillsOK) IsCode(code int) bool {
	return code == 200
}
func (o *ListSkillsOK) Code() int { return 200 }
func (o *ListSkillsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/agent/skills][%d] listSkillsOK %s", 200, payload)
}
func (o *ListSkillsOK) String() string                             { return o.Error() }
func (o *ListSkillsOK) GetPayload() *models.UserSkillsListResponse { return o.Payload }

type CreateSkillReader struct {
	formats strfmt.Registry
}

func (o *CreateSkillReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	return (&responseReader{
		formats:   o.formats,
		operation: "[POST /api/agent/skills] createSkill",
		payload:   new(models.UserSkillResponse),
		wrap: func(payload any) any {
			return &CreateSkillOK{Payload: payload.(*models.UserSkillResponse)}
		},
	}).ReadResponse(response, consumer)
}

type CreateSkillOK struct {
	Payload *models.UserSkillResponse
}

func (o *CreateSkillOK) IsSuccess() bool     { return true }
func (o *CreateSkillOK) IsRedirect() bool    { return false }
func (o *CreateSkillOK) IsClientError() bool { return false }
func (o *CreateSkillOK) IsServerError() bool { return false }
func (o *CreateSkillOK) IsCode(code int) bool {
	return code == 200
}
func (o *CreateSkillOK) Code() int { return 200 }
func (o *CreateSkillOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/agent/skills][%d] createSkillOK %s", 200, payload)
}
func (o *CreateSkillOK) String() string                        { return o.Error() }
func (o *CreateSkillOK) GetPayload() *models.UserSkillResponse { return o.Payload }

type GetSkillReader struct {
	formats strfmt.Registry
}

func (o *GetSkillReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	return (&responseReader{
		formats:   o.formats,
		operation: "[GET /api/agent/skills/{skill_id}] getSkill",
		payload:   new(models.UserSkillResponse),
		wrap: func(payload any) any {
			return &GetSkillOK{Payload: payload.(*models.UserSkillResponse)}
		},
	}).ReadResponse(response, consumer)
}

type GetSkillOK struct {
	Payload *models.UserSkillResponse
}

func (o *GetSkillOK) IsSuccess() bool     { return true }
func (o *GetSkillOK) IsRedirect() bool    { return false }
func (o *GetSkillOK) IsClientError() bool { return false }
func (o *GetSkillOK) IsServerError() bool { return false }
func (o *GetSkillOK) IsCode(code int) bool {
	return code == 200
}
func (o *GetSkillOK) Code() int { return 200 }
func (o *GetSkillOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/agent/skills/{skill_id}][%d] getSkillOK %s", 200, payload)
}
func (o *GetSkillOK) String() string                        { return o.Error() }
func (o *GetSkillOK) GetPayload() *models.UserSkillResponse { return o.Payload }

type UpdateSkillReader struct {
	formats strfmt.Registry
}

func (o *UpdateSkillReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	return (&responseReader{
		formats:   o.formats,
		operation: "[PUT /api/agent/skills/{skill_id}] updateSkill",
		payload:   new(models.UserSkillResponse),
		wrap: func(payload any) any {
			return &UpdateSkillOK{Payload: payload.(*models.UserSkillResponse)}
		},
	}).ReadResponse(response, consumer)
}

type UpdateSkillOK struct {
	Payload *models.UserSkillResponse
}

func (o *UpdateSkillOK) IsSuccess() bool     { return true }
func (o *UpdateSkillOK) IsRedirect() bool    { return false }
func (o *UpdateSkillOK) IsClientError() bool { return false }
func (o *UpdateSkillOK) IsServerError() bool { return false }
func (o *UpdateSkillOK) IsCode(code int) bool {
	return code == 200
}
func (o *UpdateSkillOK) Code() int { return 200 }
func (o *UpdateSkillOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/agent/skills/{skill_id}][%d] updateSkillOK %s", 200, payload)
}
func (o *UpdateSkillOK) String() string                        { return o.Error() }
func (o *UpdateSkillOK) GetPayload() *models.UserSkillResponse { return o.Payload }

type DeleteSkillReader struct {
	formats strfmt.Registry
}

func (o *DeleteSkillReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	return (&responseReader{
		formats:   o.formats,
		operation: "[DELETE /api/agent/skills/{skill_id}] deleteSkill",
		payload:   new(models.UserSkillDeleteResponse),
		wrap: func(payload any) any {
			return &DeleteSkillOK{Payload: payload.(*models.UserSkillDeleteResponse)}
		},
	}).ReadResponse(response, consumer)
}

type DeleteSkillOK struct {
	Payload *models.UserSkillDeleteResponse
}

func (o *DeleteSkillOK) IsSuccess() bool     { return true }
func (o *DeleteSkillOK) IsRedirect() bool    { return false }
func (o *DeleteSkillOK) IsClientError() bool { return false }
func (o *DeleteSkillOK) IsServerError() bool { return false }
func (o *DeleteSkillOK) IsCode(code int) bool {
	return code == 200
}
func (o *DeleteSkillOK) Code() int { return 200 }
func (o *DeleteSkillOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/agent/skills/{skill_id}][%d] deleteSkillOK %s", 200, payload)
}
func (o *DeleteSkillOK) String() string                              { return o.Error() }
func (o *DeleteSkillOK) GetPayload() *models.UserSkillDeleteResponse { return o.Payload }
