// Code generated by go-swagger; DO NOT EDIT.

package metrics_pipeline

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/groundcover-com/groundcover-sdk-go/pkg/models"
)

// UpdateMetricsPipelineConfigReader is a Reader for the UpdateMetricsPipelineConfig structure.
type UpdateMetricsPipelineConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateMetricsPipelineConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateMetricsPipelineConfigOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUpdateMetricsPipelineConfigBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewUpdateMetricsPipelineConfigInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewUpdateMetricsPipelineConfigServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /api/pipelines/v1/metrics/config] updateMetricsPipelineConfig", response, response.Code())
	}
}

// NewUpdateMetricsPipelineConfigOK creates a UpdateMetricsPipelineConfigOK with default headers values
func NewUpdateMetricsPipelineConfigOK() *UpdateMetricsPipelineConfigOK {
	return &UpdateMetricsPipelineConfigOK{}
}

/*
UpdateMetricsPipelineConfigOK describes a response with status code 200, with default header values.

Represents a metrics pipeline configuration entry
*/
type UpdateMetricsPipelineConfigOK struct {
	Payload *models.MetricsPipelineConfigInfo
}

// IsSuccess returns true when this update metrics pipeline config o k response has a 2xx status code
func (o *UpdateMetricsPipelineConfigOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update metrics pipeline config o k response has a 3xx status code
func (o *UpdateMetricsPipelineConfigOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update metrics pipeline config o k response has a 4xx status code
func (o *UpdateMetricsPipelineConfigOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this update metrics pipeline config o k response has a 5xx status code
func (o *UpdateMetricsPipelineConfigOK) IsServerError() bool {
	return false
}

// IsCode returns true when this update metrics pipeline config o k response a status code equal to that given
func (o *UpdateMetricsPipelineConfigOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the update metrics pipeline config o k response
func (o *UpdateMetricsPipelineConfigOK) Code() int {
	return 200
}

func (o *UpdateMetricsPipelineConfigOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/pipelines/v1/metrics/config][%d] updateMetricsPipelineConfigOK %s", 200, payload)
}

func (o *UpdateMetricsPipelineConfigOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/pipelines/v1/metrics/config][%d] updateMetricsPipelineConfigOK %s", 200, payload)
}

func (o *UpdateMetricsPipelineConfigOK) GetPayload() *models.MetricsPipelineConfigInfo {
	return o.Payload
}

func (o *UpdateMetricsPipelineConfigOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MetricsPipelineConfigInfo)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewUpdateMetricsPipelineConfigBadRequest creates a UpdateMetricsPipelineConfigBadRequest with default headers values
func NewUpdateMetricsPipelineConfigBadRequest() *UpdateMetricsPipelineConfigBadRequest {
	return &UpdateMetricsPipelineConfigBadRequest{}
}

/*
UpdateMetricsPipelineConfigBadRequest describes a response with status code 400, with default header values.

Used for error responses
*/
type UpdateMetricsPipelineConfigBadRequest struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this update metrics pipeline config bad request response has a 2xx status code
func (o *UpdateMetricsPipelineConfigBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update metrics pipeline config bad request response has a 3xx status code
func (o *UpdateMetricsPipelineConfigBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update metrics pipeline config bad request response has a 4xx status code
func (o *UpdateMetricsPipelineConfigBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this update metrics pipeline config bad request response has a 5xx status code
func (o *UpdateMetricsPipelineConfigBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this update metrics pipeline config bad request response a status code equal to that given
func (o *UpdateMetricsPipelineConfigBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the update metrics pipeline config bad request response
func (o *UpdateMetricsPipelineConfigBadRequest) Code() int {
	return 400
}

func (o *UpdateMetricsPipelineConfigBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/pipelines/v1/metrics/config][%d] updateMetricsPipelineConfigBadRequest %s", 400, payload)
}

func (o *UpdateMetricsPipelineConfigBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/pipelines/v1/metrics/config][%d] updateMetricsPipelineConfigBadRequest %s", 400, payload)
}

func (o *UpdateMetricsPipelineConfigBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *UpdateMetricsPipelineConfigBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewUpdateMetricsPipelineConfigInternalServerError creates a UpdateMetricsPipelineConfigInternalServerError with default headers values
func NewUpdateMetricsPipelineConfigInternalServerError() *UpdateMetricsPipelineConfigInternalServerError {
	return &UpdateMetricsPipelineConfigInternalServerError{}
}

/*
UpdateMetricsPipelineConfigInternalServerError describes a response with status code 500, with default header values.

Used for error responses
*/
type UpdateMetricsPipelineConfigInternalServerError struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this update metrics pipeline config internal server error response has a 2xx status code
func (o *UpdateMetricsPipelineConfigInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update metrics pipeline config internal server error response has a 3xx status code
func (o *UpdateMetricsPipelineConfigInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update metrics pipeline config internal server error response has a 4xx status code
func (o *UpdateMetricsPipelineConfigInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this update metrics pipeline config internal server error response has a 5xx status code
func (o *UpdateMetricsPipelineConfigInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this update metrics pipeline config internal server error response a status code equal to that given
func (o *UpdateMetricsPipelineConfigInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the update metrics pipeline config internal server error response
func (o *UpdateMetricsPipelineConfigInternalServerError) Code() int {
	return 500
}

func (o *UpdateMetricsPipelineConfigInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/pipelines/v1/metrics/config][%d] updateMetricsPipelineConfigInternalServerError %s", 500, payload)
}

func (o *UpdateMetricsPipelineConfigInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/pipelines/v1/metrics/config][%d] updateMetricsPipelineConfigInternalServerError %s", 500, payload)
}

func (o *UpdateMetricsPipelineConfigInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *UpdateMetricsPipelineConfigInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewUpdateMetricsPipelineConfigServiceUnavailable creates a UpdateMetricsPipelineConfigServiceUnavailable with default headers values
func NewUpdateMetricsPipelineConfigServiceUnavailable() *UpdateMetricsPipelineConfigServiceUnavailable {
	return &UpdateMetricsPipelineConfigServiceUnavailable{}
}

/*
UpdateMetricsPipelineConfigServiceUnavailable describes a response with status code 503, with default header values.

Used for error responses
*/
type UpdateMetricsPipelineConfigServiceUnavailable struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this update metrics pipeline config service unavailable response has a 2xx status code
func (o *UpdateMetricsPipelineConfigServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update metrics pipeline config service unavailable response has a 3xx status code
func (o *UpdateMetricsPipelineConfigServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update metrics pipeline config service unavailable response has a 4xx status code
func (o *UpdateMetricsPipelineConfigServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this update metrics pipeline config service unavailable response has a 5xx status code
func (o *UpdateMetricsPipelineConfigServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this update metrics pipeline config service unavailable response a status code equal to that given
func (o *UpdateMetricsPipelineConfigServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the update metrics pipeline config service unavailable response
func (o *UpdateMetricsPipelineConfigServiceUnavailable) Code() int {
	return 503
}

func (o *UpdateMetricsPipelineConfigServiceUnavailable) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/pipelines/v1/metrics/config][%d] updateMetricsPipelineConfigServiceUnavailable %s", 503, payload)
}

func (o *UpdateMetricsPipelineConfigServiceUnavailable) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/pipelines/v1/metrics/config][%d] updateMetricsPipelineConfigServiceUnavailable %s", 503, payload)
}

func (o *UpdateMetricsPipelineConfigServiceUnavailable) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *UpdateMetricsPipelineConfigServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
