// Code generated by go-swagger; DO NOT EDIT.

package integrations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/groundcover-com/groundcover-sdk-go/pkg/models"
)

// CreateDataIntegrationConfigReader is a Reader for the CreateDataIntegrationConfig structure.
type CreateDataIntegrationConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateDataIntegrationConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 201:
		result := NewCreateDataIntegrationConfigCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateDataIntegrationConfigBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateDataIntegrationConfigInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewCreateDataIntegrationConfigServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /api/integrations/v1/data/config/{type}] createDataIntegrationConfig", response, response.Code())
	}
}

// NewCreateDataIntegrationConfigCreated creates a CreateDataIntegrationConfigCreated with default headers values
func NewCreateDataIntegrationConfigCreated() *CreateDataIntegrationConfigCreated {
	return &CreateDataIntegrationConfigCreated{}
}

/*
CreateDataIntegrationConfigCreated describes a response with status code 201, with default header values.

CreateDataIntegrationConfigCreated create data integration config created
*/
type CreateDataIntegrationConfigCreated struct {
	Payload *models.DataIntegrationConfig
}

// IsSuccess returns true when this create data integration config created response has a 2xx status code
func (o *CreateDataIntegrationConfigCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create data integration config created response has a 3xx status code
func (o *CreateDataIntegrationConfigCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create data integration config created response has a 4xx status code
func (o *CreateDataIntegrationConfigCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this create data integration config created response has a 5xx status code
func (o *CreateDataIntegrationConfigCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this create data integration config created response a status code equal to that given
func (o *CreateDataIntegrationConfigCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the create data integration config created response
func (o *CreateDataIntegrationConfigCreated) Code() int {
	return 201
}

func (o *CreateDataIntegrationConfigCreated) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/integrations/v1/data/config/{type}][%d] createDataIntegrationConfigCreated %s", 201, payload)
}

func (o *CreateDataIntegrationConfigCreated) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/integrations/v1/data/config/{type}][%d] createDataIntegrationConfigCreated %s", 201, payload)
}

func (o *CreateDataIntegrationConfigCreated) GetPayload() *models.DataIntegrationConfig {
	return o.Payload
}

func (o *CreateDataIntegrationConfigCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DataIntegrationConfig)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCreateDataIntegrationConfigBadRequest creates a CreateDataIntegrationConfigBadRequest with default headers values
func NewCreateDataIntegrationConfigBadRequest() *CreateDataIntegrationConfigBadRequest {
	return &CreateDataIntegrationConfigBadRequest{}
}

/*
CreateDataIntegrationConfigBadRequest describes a response with status code 400, with default header values.

CreateDataIntegrationConfigBadRequest create data integration config bad request
*/
type CreateDataIntegrationConfigBadRequest struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this create data integration config bad request response has a 2xx status code
func (o *CreateDataIntegrationConfigBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create data integration config bad request response has a 3xx status code
func (o *CreateDataIntegrationConfigBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create data integration config bad request response has a 4xx status code
func (o *CreateDataIntegrationConfigBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this create data integration config bad request response has a 5xx status code
func (o *CreateDataIntegrationConfigBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this create data integration config bad request response a status code equal to that given
func (o *CreateDataIntegrationConfigBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the create data integration config bad request response
func (o *CreateDataIntegrationConfigBadRequest) Code() int {
	return 400
}

func (o *CreateDataIntegrationConfigBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/integrations/v1/data/config/{type}][%d] createDataIntegrationConfigBadRequest %s", 400, payload)
}

func (o *CreateDataIntegrationConfigBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/integrations/v1/data/config/{type}][%d] createDataIntegrationConfigBadRequest %s", 400, payload)
}

func (o *CreateDataIntegrationConfigBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *CreateDataIntegrationConfigBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCreateDataIntegrationConfigInternalServerError creates a CreateDataIntegrationConfigInternalServerError with default headers values
func NewCreateDataIntegrationConfigInternalServerError() *CreateDataIntegrationConfigInternalServerError {
	return &CreateDataIntegrationConfigInternalServerError{}
}

/*
CreateDataIntegrationConfigInternalServerError describes a response with status code 500, with default header values.

CreateDataIntegrationConfigInternalServerError create data integration config internal server error
*/
type CreateDataIntegrationConfigInternalServerError struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this create data integration config internal server error response has a 2xx status code
func (o *CreateDataIntegrationConfigInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create data integration config internal server error response has a 3xx status code
func (o *CreateDataIntegrationConfigInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create data integration config internal server error response has a 4xx status code
func (o *CreateDataIntegrationConfigInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this create data integration config internal server error response has a 5xx status code
func (o *CreateDataIntegrationConfigInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this create data integration config internal server error response a status code equal to that given
func (o *CreateDataIntegrationConfigInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the create data integration config internal server error response
func (o *CreateDataIntegrationConfigInternalServerError) Code() int {
	return 500
}

func (o *CreateDataIntegrationConfigInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/integrations/v1/data/config/{type}][%d] createDataIntegrationConfigInternalServerError %s", 500, payload)
}

func (o *CreateDataIntegrationConfigInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/integrations/v1/data/config/{type}][%d] createDataIntegrationConfigInternalServerError %s", 500, payload)
}

func (o *CreateDataIntegrationConfigInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *CreateDataIntegrationConfigInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCreateDataIntegrationConfigServiceUnavailable creates a CreateDataIntegrationConfigServiceUnavailable with default headers values
func NewCreateDataIntegrationConfigServiceUnavailable() *CreateDataIntegrationConfigServiceUnavailable {
	return &CreateDataIntegrationConfigServiceUnavailable{}
}

/*
CreateDataIntegrationConfigServiceUnavailable describes a response with status code 503, with default header values.

CreateDataIntegrationConfigServiceUnavailable create data integration config service unavailable
*/
type CreateDataIntegrationConfigServiceUnavailable struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this create data integration config service unavailable response has a 2xx status code
func (o *CreateDataIntegrationConfigServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create data integration config service unavailable response has a 3xx status code
func (o *CreateDataIntegrationConfigServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create data integration config service unavailable response has a 4xx status code
func (o *CreateDataIntegrationConfigServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this create data integration config service unavailable response has a 5xx status code
func (o *CreateDataIntegrationConfigServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this create data integration config service unavailable response a status code equal to that given
func (o *CreateDataIntegrationConfigServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the create data integration config service unavailable response
func (o *CreateDataIntegrationConfigServiceUnavailable) Code() int {
	return 503
}

func (o *CreateDataIntegrationConfigServiceUnavailable) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/integrations/v1/data/config/{type}][%d] createDataIntegrationConfigServiceUnavailable %s", 503, payload)
}

func (o *CreateDataIntegrationConfigServiceUnavailable) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/integrations/v1/data/config/{type}][%d] createDataIntegrationConfigServiceUnavailable %s", 503, payload)
}

func (o *CreateDataIntegrationConfigServiceUnavailable) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *CreateDataIntegrationConfigServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
