// Code generated by go-swagger; DO NOT EDIT.

package integrations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetDataIntegrationConfigsByTypeParams creates a new GetDataIntegrationConfigsByTypeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetDataIntegrationConfigsByTypeParams() *GetDataIntegrationConfigsByTypeParams {
	return &GetDataIntegrationConfigsByTypeParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetDataIntegrationConfigsByTypeParamsWithTimeout creates a new GetDataIntegrationConfigsByTypeParams object
// with the ability to set a timeout on a request.
func NewGetDataIntegrationConfigsByTypeParamsWithTimeout(timeout time.Duration) *GetDataIntegrationConfigsByTypeParams {
	return &GetDataIntegrationConfigsByTypeParams{
		timeout: timeout,
	}
}

// NewGetDataIntegrationConfigsByTypeParamsWithContext creates a new GetDataIntegrationConfigsByTypeParams object
// with the ability to set a context for a request.
func NewGetDataIntegrationConfigsByTypeParamsWithContext(ctx context.Context) *GetDataIntegrationConfigsByTypeParams {
	return &GetDataIntegrationConfigsByTypeParams{
		Context: ctx,
	}
}

// NewGetDataIntegrationConfigsByTypeParamsWithHTTPClient creates a new GetDataIntegrationConfigsByTypeParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetDataIntegrationConfigsByTypeParamsWithHTTPClient(client *http.Client) *GetDataIntegrationConfigsByTypeParams {
	return &GetDataIntegrationConfigsByTypeParams{
		HTTPClient: client,
	}
}

/*
GetDataIntegrationConfigsByTypeParams contains all the parameters to send to the API endpoint

	for the get data integration configs by type operation.

	Typically these are written to a http.Request.
*/
type GetDataIntegrationConfigsByTypeParams struct {

	/* IncludeArchived.

	   Include archived (deleted) configurations
	*/
	IncludeArchived *bool

	/* Type.

	   Data Integration type
	*/
	Type string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get data integration configs by type params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDataIntegrationConfigsByTypeParams) WithDefaults() *GetDataIntegrationConfigsByTypeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get data integration configs by type params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDataIntegrationConfigsByTypeParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get data integration configs by type params
func (o *GetDataIntegrationConfigsByTypeParams) WithTimeout(timeout time.Duration) *GetDataIntegrationConfigsByTypeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get data integration configs by type params
func (o *GetDataIntegrationConfigsByTypeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get data integration configs by type params
func (o *GetDataIntegrationConfigsByTypeParams) WithContext(ctx context.Context) *GetDataIntegrationConfigsByTypeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get data integration configs by type params
func (o *GetDataIntegrationConfigsByTypeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get data integration configs by type params
func (o *GetDataIntegrationConfigsByTypeParams) WithHTTPClient(client *http.Client) *GetDataIntegrationConfigsByTypeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get data integration configs by type params
func (o *GetDataIntegrationConfigsByTypeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIncludeArchived adds the includeArchived to the get data integration configs by type params
func (o *GetDataIntegrationConfigsByTypeParams) WithIncludeArchived(includeArchived *bool) *GetDataIntegrationConfigsByTypeParams {
	o.SetIncludeArchived(includeArchived)
	return o
}

// SetIncludeArchived adds the includeArchived to the get data integration configs by type params
func (o *GetDataIntegrationConfigsByTypeParams) SetIncludeArchived(includeArchived *bool) {
	o.IncludeArchived = includeArchived
}

// WithType adds the typeVar to the get data integration configs by type params
func (o *GetDataIntegrationConfigsByTypeParams) WithType(typeVar string) *GetDataIntegrationConfigsByTypeParams {
	o.SetType(typeVar)
	return o
}

// SetType adds the type to the get data integration configs by type params
func (o *GetDataIntegrationConfigsByTypeParams) SetType(typeVar string) {
	o.Type = typeVar
}

// WriteToRequest writes these params to a swagger request
func (o *GetDataIntegrationConfigsByTypeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.IncludeArchived != nil {

		// query param includeArchived
		var qrIncludeArchived bool

		if o.IncludeArchived != nil {
			qrIncludeArchived = *o.IncludeArchived
		}
		qIncludeArchived := swag.FormatBool(qrIncludeArchived)
		if qIncludeArchived != "" {

			if err := r.SetQueryParam("includeArchived", qIncludeArchived); err != nil {
				return err
			}
		}
	}

	// path param type
	if err := r.SetPathParam("type", o.Type); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
