// Code generated by go-swagger; DO NOT EDIT.

package integrations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/groundcover-com/groundcover-sdk-go/pkg/models"
)

// GetDataIntegrationConfigReader is a Reader for the GetDataIntegrationConfig structure.
type GetDataIntegrationConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDataIntegrationConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetDataIntegrationConfigOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetDataIntegrationConfigBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetDataIntegrationConfigNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetDataIntegrationConfigInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewGetDataIntegrationConfigServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/integrations/v1/data/config/{type}/{id}] getDataIntegrationConfig", response, response.Code())
	}
}

// NewGetDataIntegrationConfigOK creates a GetDataIntegrationConfigOK with default headers values
func NewGetDataIntegrationConfigOK() *GetDataIntegrationConfigOK {
	return &GetDataIntegrationConfigOK{}
}

/*
GetDataIntegrationConfigOK describes a response with status code 200, with default header values.

GetDataIntegrationConfigOK get data integration config o k
*/
type GetDataIntegrationConfigOK struct {
	Payload *models.DataIntegrationConfig
}

// IsSuccess returns true when this get data integration config o k response has a 2xx status code
func (o *GetDataIntegrationConfigOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get data integration config o k response has a 3xx status code
func (o *GetDataIntegrationConfigOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get data integration config o k response has a 4xx status code
func (o *GetDataIntegrationConfigOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get data integration config o k response has a 5xx status code
func (o *GetDataIntegrationConfigOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get data integration config o k response a status code equal to that given
func (o *GetDataIntegrationConfigOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get data integration config o k response
func (o *GetDataIntegrationConfigOK) Code() int {
	return 200
}

func (o *GetDataIntegrationConfigOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/integrations/v1/data/config/{type}/{id}][%d] getDataIntegrationConfigOK %s", 200, payload)
}

func (o *GetDataIntegrationConfigOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/integrations/v1/data/config/{type}/{id}][%d] getDataIntegrationConfigOK %s", 200, payload)
}

func (o *GetDataIntegrationConfigOK) GetPayload() *models.DataIntegrationConfig {
	return o.Payload
}

func (o *GetDataIntegrationConfigOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DataIntegrationConfig)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetDataIntegrationConfigBadRequest creates a GetDataIntegrationConfigBadRequest with default headers values
func NewGetDataIntegrationConfigBadRequest() *GetDataIntegrationConfigBadRequest {
	return &GetDataIntegrationConfigBadRequest{}
}

/*
GetDataIntegrationConfigBadRequest describes a response with status code 400, with default header values.

GetDataIntegrationConfigBadRequest get data integration config bad request
*/
type GetDataIntegrationConfigBadRequest struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this get data integration config bad request response has a 2xx status code
func (o *GetDataIntegrationConfigBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get data integration config bad request response has a 3xx status code
func (o *GetDataIntegrationConfigBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get data integration config bad request response has a 4xx status code
func (o *GetDataIntegrationConfigBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get data integration config bad request response has a 5xx status code
func (o *GetDataIntegrationConfigBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get data integration config bad request response a status code equal to that given
func (o *GetDataIntegrationConfigBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get data integration config bad request response
func (o *GetDataIntegrationConfigBadRequest) Code() int {
	return 400
}

func (o *GetDataIntegrationConfigBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/integrations/v1/data/config/{type}/{id}][%d] getDataIntegrationConfigBadRequest %s", 400, payload)
}

func (o *GetDataIntegrationConfigBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/integrations/v1/data/config/{type}/{id}][%d] getDataIntegrationConfigBadRequest %s", 400, payload)
}

func (o *GetDataIntegrationConfigBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetDataIntegrationConfigBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetDataIntegrationConfigNotFound creates a GetDataIntegrationConfigNotFound with default headers values
func NewGetDataIntegrationConfigNotFound() *GetDataIntegrationConfigNotFound {
	return &GetDataIntegrationConfigNotFound{}
}

/*
GetDataIntegrationConfigNotFound describes a response with status code 404, with default header values.

GetDataIntegrationConfigNotFound get data integration config not found
*/
type GetDataIntegrationConfigNotFound struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this get data integration config not found response has a 2xx status code
func (o *GetDataIntegrationConfigNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get data integration config not found response has a 3xx status code
func (o *GetDataIntegrationConfigNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get data integration config not found response has a 4xx status code
func (o *GetDataIntegrationConfigNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get data integration config not found response has a 5xx status code
func (o *GetDataIntegrationConfigNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get data integration config not found response a status code equal to that given
func (o *GetDataIntegrationConfigNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get data integration config not found response
func (o *GetDataIntegrationConfigNotFound) Code() int {
	return 404
}

func (o *GetDataIntegrationConfigNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/integrations/v1/data/config/{type}/{id}][%d] getDataIntegrationConfigNotFound %s", 404, payload)
}

func (o *GetDataIntegrationConfigNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/integrations/v1/data/config/{type}/{id}][%d] getDataIntegrationConfigNotFound %s", 404, payload)
}

func (o *GetDataIntegrationConfigNotFound) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetDataIntegrationConfigNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetDataIntegrationConfigInternalServerError creates a GetDataIntegrationConfigInternalServerError with default headers values
func NewGetDataIntegrationConfigInternalServerError() *GetDataIntegrationConfigInternalServerError {
	return &GetDataIntegrationConfigInternalServerError{}
}

/*
GetDataIntegrationConfigInternalServerError describes a response with status code 500, with default header values.

GetDataIntegrationConfigInternalServerError get data integration config internal server error
*/
type GetDataIntegrationConfigInternalServerError struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this get data integration config internal server error response has a 2xx status code
func (o *GetDataIntegrationConfigInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get data integration config internal server error response has a 3xx status code
func (o *GetDataIntegrationConfigInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get data integration config internal server error response has a 4xx status code
func (o *GetDataIntegrationConfigInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get data integration config internal server error response has a 5xx status code
func (o *GetDataIntegrationConfigInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get data integration config internal server error response a status code equal to that given
func (o *GetDataIntegrationConfigInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get data integration config internal server error response
func (o *GetDataIntegrationConfigInternalServerError) Code() int {
	return 500
}

func (o *GetDataIntegrationConfigInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/integrations/v1/data/config/{type}/{id}][%d] getDataIntegrationConfigInternalServerError %s", 500, payload)
}

func (o *GetDataIntegrationConfigInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/integrations/v1/data/config/{type}/{id}][%d] getDataIntegrationConfigInternalServerError %s", 500, payload)
}

func (o *GetDataIntegrationConfigInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetDataIntegrationConfigInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetDataIntegrationConfigServiceUnavailable creates a GetDataIntegrationConfigServiceUnavailable with default headers values
func NewGetDataIntegrationConfigServiceUnavailable() *GetDataIntegrationConfigServiceUnavailable {
	return &GetDataIntegrationConfigServiceUnavailable{}
}

/*
GetDataIntegrationConfigServiceUnavailable describes a response with status code 503, with default header values.

GetDataIntegrationConfigServiceUnavailable get data integration config service unavailable
*/
type GetDataIntegrationConfigServiceUnavailable struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this get data integration config service unavailable response has a 2xx status code
func (o *GetDataIntegrationConfigServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get data integration config service unavailable response has a 3xx status code
func (o *GetDataIntegrationConfigServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get data integration config service unavailable response has a 4xx status code
func (o *GetDataIntegrationConfigServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this get data integration config service unavailable response has a 5xx status code
func (o *GetDataIntegrationConfigServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this get data integration config service unavailable response a status code equal to that given
func (o *GetDataIntegrationConfigServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the get data integration config service unavailable response
func (o *GetDataIntegrationConfigServiceUnavailable) Code() int {
	return 503
}

func (o *GetDataIntegrationConfigServiceUnavailable) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/integrations/v1/data/config/{type}/{id}][%d] getDataIntegrationConfigServiceUnavailable %s", 503, payload)
}

func (o *GetDataIntegrationConfigServiceUnavailable) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/integrations/v1/data/config/{type}/{id}][%d] getDataIntegrationConfigServiceUnavailable %s", 503, payload)
}

func (o *GetDataIntegrationConfigServiceUnavailable) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetDataIntegrationConfigServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
