// Code generated by go-swagger; DO NOT EDIT.

package integrations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/groundcover-com/groundcover-sdk-go/pkg/models"
)

// GetDataIntegrationConfigsReader is a Reader for the GetDataIntegrationConfigs structure.
type GetDataIntegrationConfigsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDataIntegrationConfigsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDataIntegrationConfigsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 204:
		result := NewGetDataIntegrationConfigsNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetDataIntegrationConfigsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetDataIntegrationConfigsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewGetDataIntegrationConfigsServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/integrations/v1/data/config] getDataIntegrationConfigs", response, response.Code())
	}
}

// NewGetDataIntegrationConfigsOK creates a GetDataIntegrationConfigsOK with default headers values
func NewGetDataIntegrationConfigsOK() *GetDataIntegrationConfigsOK {
	return &GetDataIntegrationConfigsOK{}
}

/*
GetDataIntegrationConfigsOK describes a response with status code 200, with default header values.

GetDataIntegrationConfigsOK get data integration configs o k
*/
type GetDataIntegrationConfigsOK struct {
	Payload []*models.DataIntegrationConfig
}

// IsSuccess returns true when this get data integration configs o k response has a 2xx status code
func (o *GetDataIntegrationConfigsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get data integration configs o k response has a 3xx status code
func (o *GetDataIntegrationConfigsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get data integration configs o k response has a 4xx status code
func (o *GetDataIntegrationConfigsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get data integration configs o k response has a 5xx status code
func (o *GetDataIntegrationConfigsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get data integration configs o k response a status code equal to that given
func (o *GetDataIntegrationConfigsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get data integration configs o k response
func (o *GetDataIntegrationConfigsOK) Code() int {
	return 200
}

func (o *GetDataIntegrationConfigsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/integrations/v1/data/config][%d] getDataIntegrationConfigsOK %s", 200, payload)
}

func (o *GetDataIntegrationConfigsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/integrations/v1/data/config][%d] getDataIntegrationConfigsOK %s", 200, payload)
}

func (o *GetDataIntegrationConfigsOK) GetPayload() []*models.DataIntegrationConfig {
	return o.Payload
}

func (o *GetDataIntegrationConfigsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDataIntegrationConfigsNoContent creates a GetDataIntegrationConfigsNoContent with default headers values
func NewGetDataIntegrationConfigsNoContent() *GetDataIntegrationConfigsNoContent {
	return &GetDataIntegrationConfigsNoContent{}
}

/*
GetDataIntegrationConfigsNoContent describes a response with status code 204, with default header values.

GetDataIntegrationConfigsNoContent get data integration configs no content
*/
type GetDataIntegrationConfigsNoContent struct {
	Payload interface{}
}

// IsSuccess returns true when this get data integration configs no content response has a 2xx status code
func (o *GetDataIntegrationConfigsNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get data integration configs no content response has a 3xx status code
func (o *GetDataIntegrationConfigsNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get data integration configs no content response has a 4xx status code
func (o *GetDataIntegrationConfigsNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this get data integration configs no content response has a 5xx status code
func (o *GetDataIntegrationConfigsNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this get data integration configs no content response a status code equal to that given
func (o *GetDataIntegrationConfigsNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the get data integration configs no content response
func (o *GetDataIntegrationConfigsNoContent) Code() int {
	return 204
}

func (o *GetDataIntegrationConfigsNoContent) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/integrations/v1/data/config][%d] getDataIntegrationConfigsNoContent %s", 204, payload)
}

func (o *GetDataIntegrationConfigsNoContent) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/integrations/v1/data/config][%d] getDataIntegrationConfigsNoContent %s", 204, payload)
}

func (o *GetDataIntegrationConfigsNoContent) GetPayload() interface{} {
	return o.Payload
}

func (o *GetDataIntegrationConfigsNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDataIntegrationConfigsBadRequest creates a GetDataIntegrationConfigsBadRequest with default headers values
func NewGetDataIntegrationConfigsBadRequest() *GetDataIntegrationConfigsBadRequest {
	return &GetDataIntegrationConfigsBadRequest{}
}

/*
GetDataIntegrationConfigsBadRequest describes a response with status code 400, with default header values.

GetDataIntegrationConfigsBadRequest get data integration configs bad request
*/
type GetDataIntegrationConfigsBadRequest struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this get data integration configs bad request response has a 2xx status code
func (o *GetDataIntegrationConfigsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get data integration configs bad request response has a 3xx status code
func (o *GetDataIntegrationConfigsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get data integration configs bad request response has a 4xx status code
func (o *GetDataIntegrationConfigsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get data integration configs bad request response has a 5xx status code
func (o *GetDataIntegrationConfigsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get data integration configs bad request response a status code equal to that given
func (o *GetDataIntegrationConfigsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get data integration configs bad request response
func (o *GetDataIntegrationConfigsBadRequest) Code() int {
	return 400
}

func (o *GetDataIntegrationConfigsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/integrations/v1/data/config][%d] getDataIntegrationConfigsBadRequest %s", 400, payload)
}

func (o *GetDataIntegrationConfigsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/integrations/v1/data/config][%d] getDataIntegrationConfigsBadRequest %s", 400, payload)
}

func (o *GetDataIntegrationConfigsBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetDataIntegrationConfigsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDataIntegrationConfigsInternalServerError creates a GetDataIntegrationConfigsInternalServerError with default headers values
func NewGetDataIntegrationConfigsInternalServerError() *GetDataIntegrationConfigsInternalServerError {
	return &GetDataIntegrationConfigsInternalServerError{}
}

/*
GetDataIntegrationConfigsInternalServerError describes a response with status code 500, with default header values.

GetDataIntegrationConfigsInternalServerError get data integration configs internal server error
*/
type GetDataIntegrationConfigsInternalServerError struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this get data integration configs internal server error response has a 2xx status code
func (o *GetDataIntegrationConfigsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get data integration configs internal server error response has a 3xx status code
func (o *GetDataIntegrationConfigsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get data integration configs internal server error response has a 4xx status code
func (o *GetDataIntegrationConfigsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get data integration configs internal server error response has a 5xx status code
func (o *GetDataIntegrationConfigsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get data integration configs internal server error response a status code equal to that given
func (o *GetDataIntegrationConfigsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get data integration configs internal server error response
func (o *GetDataIntegrationConfigsInternalServerError) Code() int {
	return 500
}

func (o *GetDataIntegrationConfigsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/integrations/v1/data/config][%d] getDataIntegrationConfigsInternalServerError %s", 500, payload)
}

func (o *GetDataIntegrationConfigsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/integrations/v1/data/config][%d] getDataIntegrationConfigsInternalServerError %s", 500, payload)
}

func (o *GetDataIntegrationConfigsInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetDataIntegrationConfigsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDataIntegrationConfigsServiceUnavailable creates a GetDataIntegrationConfigsServiceUnavailable with default headers values
func NewGetDataIntegrationConfigsServiceUnavailable() *GetDataIntegrationConfigsServiceUnavailable {
	return &GetDataIntegrationConfigsServiceUnavailable{}
}

/*
GetDataIntegrationConfigsServiceUnavailable describes a response with status code 503, with default header values.

GetDataIntegrationConfigsServiceUnavailable get data integration configs service unavailable
*/
type GetDataIntegrationConfigsServiceUnavailable struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this get data integration configs service unavailable response has a 2xx status code
func (o *GetDataIntegrationConfigsServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get data integration configs service unavailable response has a 3xx status code
func (o *GetDataIntegrationConfigsServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get data integration configs service unavailable response has a 4xx status code
func (o *GetDataIntegrationConfigsServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this get data integration configs service unavailable response has a 5xx status code
func (o *GetDataIntegrationConfigsServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this get data integration configs service unavailable response a status code equal to that given
func (o *GetDataIntegrationConfigsServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the get data integration configs service unavailable response
func (o *GetDataIntegrationConfigsServiceUnavailable) Code() int {
	return 503
}

func (o *GetDataIntegrationConfigsServiceUnavailable) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/integrations/v1/data/config][%d] getDataIntegrationConfigsServiceUnavailable %s", 503, payload)
}

func (o *GetDataIntegrationConfigsServiceUnavailable) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/integrations/v1/data/config][%d] getDataIntegrationConfigsServiceUnavailable %s", 503, payload)
}

func (o *GetDataIntegrationConfigsServiceUnavailable) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetDataIntegrationConfigsServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
