// Code generated by go-swagger; DO NOT EDIT.

package integrations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetDataIntegrationConfigsParams creates a new GetDataIntegrationConfigsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetDataIntegrationConfigsParams() *GetDataIntegrationConfigsParams {
	return &GetDataIntegrationConfigsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetDataIntegrationConfigsParamsWithTimeout creates a new GetDataIntegrationConfigsParams object
// with the ability to set a timeout on a request.
func NewGetDataIntegrationConfigsParamsWithTimeout(timeout time.Duration) *GetDataIntegrationConfigsParams {
	return &GetDataIntegrationConfigsParams{
		timeout: timeout,
	}
}

// NewGetDataIntegrationConfigsParamsWithContext creates a new GetDataIntegrationConfigsParams object
// with the ability to set a context for a request.
func NewGetDataIntegrationConfigsParamsWithContext(ctx context.Context) *GetDataIntegrationConfigsParams {
	return &GetDataIntegrationConfigsParams{
		Context: ctx,
	}
}

// NewGetDataIntegrationConfigsParamsWithHTTPClient creates a new GetDataIntegrationConfigsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetDataIntegrationConfigsParamsWithHTTPClient(client *http.Client) *GetDataIntegrationConfigsParams {
	return &GetDataIntegrationConfigsParams{
		HTTPClient: client,
	}
}

/*
GetDataIntegrationConfigsParams contains all the parameters to send to the API endpoint

	for the get data integration configs operation.

	Typically these are written to a http.Request.
*/
type GetDataIntegrationConfigsParams struct {

	/* IncludeArchived.

	   Include archived (deleted) configurations
	*/
	IncludeArchived *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get data integration configs params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDataIntegrationConfigsParams) WithDefaults() *GetDataIntegrationConfigsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get data integration configs params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDataIntegrationConfigsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get data integration configs params
func (o *GetDataIntegrationConfigsParams) WithTimeout(timeout time.Duration) *GetDataIntegrationConfigsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get data integration configs params
func (o *GetDataIntegrationConfigsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get data integration configs params
func (o *GetDataIntegrationConfigsParams) WithContext(ctx context.Context) *GetDataIntegrationConfigsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get data integration configs params
func (o *GetDataIntegrationConfigsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get data integration configs params
func (o *GetDataIntegrationConfigsParams) WithHTTPClient(client *http.Client) *GetDataIntegrationConfigsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get data integration configs params
func (o *GetDataIntegrationConfigsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIncludeArchived adds the includeArchived to the get data integration configs params
func (o *GetDataIntegrationConfigsParams) WithIncludeArchived(includeArchived *bool) *GetDataIntegrationConfigsParams {
	o.SetIncludeArchived(includeArchived)
	return o
}

// SetIncludeArchived adds the includeArchived to the get data integration configs params
func (o *GetDataIntegrationConfigsParams) SetIncludeArchived(includeArchived *bool) {
	o.IncludeArchived = includeArchived
}

// WriteToRequest writes these params to a swagger request
func (o *GetDataIntegrationConfigsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.IncludeArchived != nil {

		// query param includeArchived
		var qrIncludeArchived bool

		if o.IncludeArchived != nil {
			qrIncludeArchived = *o.IncludeArchived
		}
		qIncludeArchived := swag.FormatBool(qrIncludeArchived)
		if qIncludeArchived != "" {

			if err := r.SetQueryParam("includeArchived", qIncludeArchived); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
