// Code generated by go-swagger; DO NOT EDIT.

package monitors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/groundcover-com/groundcover-sdk-go/pkg/models"
)

// NewCreateRecurringSilenceParams creates a new CreateRecurringSilenceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateRecurringSilenceParams() *CreateRecurringSilenceParams {
	return &CreateRecurringSilenceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateRecurringSilenceParamsWithTimeout creates a new CreateRecurringSilenceParams object
// with the ability to set a timeout on a request.
func NewCreateRecurringSilenceParamsWithTimeout(timeout time.Duration) *CreateRecurringSilenceParams {
	return &CreateRecurringSilenceParams{
		timeout: timeout,
	}
}

// NewCreateRecurringSilenceParamsWithContext creates a new CreateRecurringSilenceParams object
// with the ability to set a context for a request.
func NewCreateRecurringSilenceParamsWithContext(ctx context.Context) *CreateRecurringSilenceParams {
	return &CreateRecurringSilenceParams{
		Context: ctx,
	}
}

// NewCreateRecurringSilenceParamsWithHTTPClient creates a new CreateRecurringSilenceParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateRecurringSilenceParamsWithHTTPClient(client *http.Client) *CreateRecurringSilenceParams {
	return &CreateRecurringSilenceParams{
		HTTPClient: client,
	}
}

/*
CreateRecurringSilenceParams contains all the parameters to send to the API endpoint

	for the create recurring silence operation.

	Typically these are written to a http.Request.
*/
type CreateRecurringSilenceParams struct {

	// Body.
	Body *models.CreateRecurringSilenceRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create recurring silence params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateRecurringSilenceParams) WithDefaults() *CreateRecurringSilenceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create recurring silence params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateRecurringSilenceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create recurring silence params
func (o *CreateRecurringSilenceParams) WithTimeout(timeout time.Duration) *CreateRecurringSilenceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create recurring silence params
func (o *CreateRecurringSilenceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create recurring silence params
func (o *CreateRecurringSilenceParams) WithContext(ctx context.Context) *CreateRecurringSilenceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create recurring silence params
func (o *CreateRecurringSilenceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create recurring silence params
func (o *CreateRecurringSilenceParams) WithHTTPClient(client *http.Client) *CreateRecurringSilenceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create recurring silence params
func (o *CreateRecurringSilenceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create recurring silence params
func (o *CreateRecurringSilenceParams) WithBody(body *models.CreateRecurringSilenceRequest) *CreateRecurringSilenceParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create recurring silence params
func (o *CreateRecurringSilenceParams) SetBody(body *models.CreateRecurringSilenceRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateRecurringSilenceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
