// Code generated by go-swagger; DO NOT EDIT.

package monitors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/groundcover-com/groundcover-sdk-go/pkg/models"
)

// CreateRecurringSilenceReader is a Reader for the CreateRecurringSilence structure.
type CreateRecurringSilenceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateRecurringSilenceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewCreateRecurringSilenceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateRecurringSilenceBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateRecurringSilenceInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /api/monitors/recurring-silences] createRecurringSilence", response, response.Code())
	}
}

// NewCreateRecurringSilenceOK creates a CreateRecurringSilenceOK with default headers values
func NewCreateRecurringSilenceOK() *CreateRecurringSilenceOK {
	return &CreateRecurringSilenceOK{}
}

/*
CreateRecurringSilenceOK describes a response with status code 200, with default header values.

CreateRecurringSilenceOK create recurring silence o k
*/
type CreateRecurringSilenceOK struct {
	Payload *models.RecurringSilenceResponse
}

// IsSuccess returns true when this create recurring silence o k response has a 2xx status code
func (o *CreateRecurringSilenceOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create recurring silence o k response has a 3xx status code
func (o *CreateRecurringSilenceOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create recurring silence o k response has a 4xx status code
func (o *CreateRecurringSilenceOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this create recurring silence o k response has a 5xx status code
func (o *CreateRecurringSilenceOK) IsServerError() bool {
	return false
}

// IsCode returns true when this create recurring silence o k response a status code equal to that given
func (o *CreateRecurringSilenceOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the create recurring silence o k response
func (o *CreateRecurringSilenceOK) Code() int {
	return 200
}

func (o *CreateRecurringSilenceOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/monitors/recurring-silences][%d] createRecurringSilenceOK %s", 200, payload)
}

func (o *CreateRecurringSilenceOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/monitors/recurring-silences][%d] createRecurringSilenceOK %s", 200, payload)
}

func (o *CreateRecurringSilenceOK) GetPayload() *models.RecurringSilenceResponse {
	return o.Payload
}

func (o *CreateRecurringSilenceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RecurringSilenceResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCreateRecurringSilenceBadRequest creates a CreateRecurringSilenceBadRequest with default headers values
func NewCreateRecurringSilenceBadRequest() *CreateRecurringSilenceBadRequest {
	return &CreateRecurringSilenceBadRequest{}
}

/*
CreateRecurringSilenceBadRequest describes a response with status code 400, with default header values.

ErrorResponse defines a common error response structure.
*/
type CreateRecurringSilenceBadRequest struct {
	Payload *CreateRecurringSilenceBadRequestBody
}

// IsSuccess returns true when this create recurring silence bad request response has a 2xx status code
func (o *CreateRecurringSilenceBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create recurring silence bad request response has a 3xx status code
func (o *CreateRecurringSilenceBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create recurring silence bad request response has a 4xx status code
func (o *CreateRecurringSilenceBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this create recurring silence bad request response has a 5xx status code
func (o *CreateRecurringSilenceBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this create recurring silence bad request response a status code equal to that given
func (o *CreateRecurringSilenceBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the create recurring silence bad request response
func (o *CreateRecurringSilenceBadRequest) Code() int {
	return 400
}

func (o *CreateRecurringSilenceBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/monitors/recurring-silences][%d] createRecurringSilenceBadRequest %s", 400, payload)
}

func (o *CreateRecurringSilenceBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/monitors/recurring-silences][%d] createRecurringSilenceBadRequest %s", 400, payload)
}

func (o *CreateRecurringSilenceBadRequest) GetPayload() *CreateRecurringSilenceBadRequestBody {
	return o.Payload
}

func (o *CreateRecurringSilenceBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(CreateRecurringSilenceBadRequestBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCreateRecurringSilenceInternalServerError creates a CreateRecurringSilenceInternalServerError with default headers values
func NewCreateRecurringSilenceInternalServerError() *CreateRecurringSilenceInternalServerError {
	return &CreateRecurringSilenceInternalServerError{}
}

/*
CreateRecurringSilenceInternalServerError describes a response with status code 500, with default header values.

ErrorResponse defines a common error response structure.
*/
type CreateRecurringSilenceInternalServerError struct {
	Payload *CreateRecurringSilenceInternalServerErrorBody
}

// IsSuccess returns true when this create recurring silence internal server error response has a 2xx status code
func (o *CreateRecurringSilenceInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create recurring silence internal server error response has a 3xx status code
func (o *CreateRecurringSilenceInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create recurring silence internal server error response has a 4xx status code
func (o *CreateRecurringSilenceInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this create recurring silence internal server error response has a 5xx status code
func (o *CreateRecurringSilenceInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this create recurring silence internal server error response a status code equal to that given
func (o *CreateRecurringSilenceInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the create recurring silence internal server error response
func (o *CreateRecurringSilenceInternalServerError) Code() int {
	return 500
}

func (o *CreateRecurringSilenceInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/monitors/recurring-silences][%d] createRecurringSilenceInternalServerError %s", 500, payload)
}

func (o *CreateRecurringSilenceInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/monitors/recurring-silences][%d] createRecurringSilenceInternalServerError %s", 500, payload)
}

func (o *CreateRecurringSilenceInternalServerError) GetPayload() *CreateRecurringSilenceInternalServerErrorBody {
	return o.Payload
}

func (o *CreateRecurringSilenceInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(CreateRecurringSilenceInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
CreateRecurringSilenceBadRequestBody create recurring silence bad request body
swagger:model CreateRecurringSilenceBadRequestBody
*/
type CreateRecurringSilenceBadRequestBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this create recurring silence bad request body
func (o *CreateRecurringSilenceBadRequestBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create recurring silence bad request body based on context it is used
func (o *CreateRecurringSilenceBadRequestBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *CreateRecurringSilenceBadRequestBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreateRecurringSilenceBadRequestBody) UnmarshalBinary(b []byte) error {
	var res CreateRecurringSilenceBadRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
CreateRecurringSilenceInternalServerErrorBody create recurring silence internal server error body
swagger:model CreateRecurringSilenceInternalServerErrorBody
*/
type CreateRecurringSilenceInternalServerErrorBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this create recurring silence internal server error body
func (o *CreateRecurringSilenceInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create recurring silence internal server error body based on context it is used
func (o *CreateRecurringSilenceInternalServerErrorBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *CreateRecurringSilenceInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreateRecurringSilenceInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res CreateRecurringSilenceInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
