// Code generated by go-swagger; DO NOT EDIT.

package monitors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DeleteRecurringSilenceReader is a Reader for the DeleteRecurringSilence structure.
type DeleteRecurringSilenceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteRecurringSilenceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteRecurringSilenceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteRecurringSilenceBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteRecurringSilenceNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteRecurringSilenceInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /api/monitors/recurring-silences/{id}] deleteRecurringSilence", response, response.Code())
	}
}

// NewDeleteRecurringSilenceOK creates a DeleteRecurringSilenceOK with default headers values
func NewDeleteRecurringSilenceOK() *DeleteRecurringSilenceOK {
	return &DeleteRecurringSilenceOK{}
}

/*
DeleteRecurringSilenceOK describes a response with status code 200, with default header values.

NoContentResponse indicates success but that no response body is expected or included.
*/
type DeleteRecurringSilenceOK struct {
}

// IsSuccess returns true when this delete recurring silence o k response has a 2xx status code
func (o *DeleteRecurringSilenceOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete recurring silence o k response has a 3xx status code
func (o *DeleteRecurringSilenceOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete recurring silence o k response has a 4xx status code
func (o *DeleteRecurringSilenceOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete recurring silence o k response has a 5xx status code
func (o *DeleteRecurringSilenceOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete recurring silence o k response a status code equal to that given
func (o *DeleteRecurringSilenceOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete recurring silence o k response
func (o *DeleteRecurringSilenceOK) Code() int {
	return 200
}

func (o *DeleteRecurringSilenceOK) Error() string {
	return fmt.Sprintf("[DELETE /api/monitors/recurring-silences/{id}][%d] deleteRecurringSilenceOK", 200)
}

func (o *DeleteRecurringSilenceOK) String() string {
	return fmt.Sprintf("[DELETE /api/monitors/recurring-silences/{id}][%d] deleteRecurringSilenceOK", 200)
}

func (o *DeleteRecurringSilenceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteRecurringSilenceBadRequest creates a DeleteRecurringSilenceBadRequest with default headers values
func NewDeleteRecurringSilenceBadRequest() *DeleteRecurringSilenceBadRequest {
	return &DeleteRecurringSilenceBadRequest{}
}

/*
DeleteRecurringSilenceBadRequest describes a response with status code 400, with default header values.

ErrorResponse defines a common error response structure.
*/
type DeleteRecurringSilenceBadRequest struct {
	Payload *DeleteRecurringSilenceBadRequestBody
}

// IsSuccess returns true when this delete recurring silence bad request response has a 2xx status code
func (o *DeleteRecurringSilenceBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete recurring silence bad request response has a 3xx status code
func (o *DeleteRecurringSilenceBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete recurring silence bad request response has a 4xx status code
func (o *DeleteRecurringSilenceBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete recurring silence bad request response has a 5xx status code
func (o *DeleteRecurringSilenceBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this delete recurring silence bad request response a status code equal to that given
func (o *DeleteRecurringSilenceBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the delete recurring silence bad request response
func (o *DeleteRecurringSilenceBadRequest) Code() int {
	return 400
}

func (o *DeleteRecurringSilenceBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/monitors/recurring-silences/{id}][%d] deleteRecurringSilenceBadRequest %s", 400, payload)
}

func (o *DeleteRecurringSilenceBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/monitors/recurring-silences/{id}][%d] deleteRecurringSilenceBadRequest %s", 400, payload)
}

func (o *DeleteRecurringSilenceBadRequest) GetPayload() *DeleteRecurringSilenceBadRequestBody {
	return o.Payload
}

func (o *DeleteRecurringSilenceBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(DeleteRecurringSilenceBadRequestBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteRecurringSilenceNotFound creates a DeleteRecurringSilenceNotFound with default headers values
func NewDeleteRecurringSilenceNotFound() *DeleteRecurringSilenceNotFound {
	return &DeleteRecurringSilenceNotFound{}
}

/*
DeleteRecurringSilenceNotFound describes a response with status code 404, with default header values.

ErrorResponse defines a common error response structure.
*/
type DeleteRecurringSilenceNotFound struct {
	Payload *DeleteRecurringSilenceNotFoundBody
}

// IsSuccess returns true when this delete recurring silence not found response has a 2xx status code
func (o *DeleteRecurringSilenceNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete recurring silence not found response has a 3xx status code
func (o *DeleteRecurringSilenceNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete recurring silence not found response has a 4xx status code
func (o *DeleteRecurringSilenceNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete recurring silence not found response has a 5xx status code
func (o *DeleteRecurringSilenceNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete recurring silence not found response a status code equal to that given
func (o *DeleteRecurringSilenceNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the delete recurring silence not found response
func (o *DeleteRecurringSilenceNotFound) Code() int {
	return 404
}

func (o *DeleteRecurringSilenceNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/monitors/recurring-silences/{id}][%d] deleteRecurringSilenceNotFound %s", 404, payload)
}

func (o *DeleteRecurringSilenceNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/monitors/recurring-silences/{id}][%d] deleteRecurringSilenceNotFound %s", 404, payload)
}

func (o *DeleteRecurringSilenceNotFound) GetPayload() *DeleteRecurringSilenceNotFoundBody {
	return o.Payload
}

func (o *DeleteRecurringSilenceNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(DeleteRecurringSilenceNotFoundBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteRecurringSilenceInternalServerError creates a DeleteRecurringSilenceInternalServerError with default headers values
func NewDeleteRecurringSilenceInternalServerError() *DeleteRecurringSilenceInternalServerError {
	return &DeleteRecurringSilenceInternalServerError{}
}

/*
DeleteRecurringSilenceInternalServerError describes a response with status code 500, with default header values.

ErrorResponse defines a common error response structure.
*/
type DeleteRecurringSilenceInternalServerError struct {
	Payload *DeleteRecurringSilenceInternalServerErrorBody
}

// IsSuccess returns true when this delete recurring silence internal server error response has a 2xx status code
func (o *DeleteRecurringSilenceInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete recurring silence internal server error response has a 3xx status code
func (o *DeleteRecurringSilenceInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete recurring silence internal server error response has a 4xx status code
func (o *DeleteRecurringSilenceInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete recurring silence internal server error response has a 5xx status code
func (o *DeleteRecurringSilenceInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this delete recurring silence internal server error response a status code equal to that given
func (o *DeleteRecurringSilenceInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the delete recurring silence internal server error response
func (o *DeleteRecurringSilenceInternalServerError) Code() int {
	return 500
}

func (o *DeleteRecurringSilenceInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/monitors/recurring-silences/{id}][%d] deleteRecurringSilenceInternalServerError %s", 500, payload)
}

func (o *DeleteRecurringSilenceInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/monitors/recurring-silences/{id}][%d] deleteRecurringSilenceInternalServerError %s", 500, payload)
}

func (o *DeleteRecurringSilenceInternalServerError) GetPayload() *DeleteRecurringSilenceInternalServerErrorBody {
	return o.Payload
}

func (o *DeleteRecurringSilenceInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(DeleteRecurringSilenceInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
DeleteRecurringSilenceBadRequestBody delete recurring silence bad request body
swagger:model DeleteRecurringSilenceBadRequestBody
*/
type DeleteRecurringSilenceBadRequestBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this delete recurring silence bad request body
func (o *DeleteRecurringSilenceBadRequestBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this delete recurring silence bad request body based on context it is used
func (o *DeleteRecurringSilenceBadRequestBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteRecurringSilenceBadRequestBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteRecurringSilenceBadRequestBody) UnmarshalBinary(b []byte) error {
	var res DeleteRecurringSilenceBadRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
DeleteRecurringSilenceInternalServerErrorBody delete recurring silence internal server error body
swagger:model DeleteRecurringSilenceInternalServerErrorBody
*/
type DeleteRecurringSilenceInternalServerErrorBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this delete recurring silence internal server error body
func (o *DeleteRecurringSilenceInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this delete recurring silence internal server error body based on context it is used
func (o *DeleteRecurringSilenceInternalServerErrorBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteRecurringSilenceInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteRecurringSilenceInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res DeleteRecurringSilenceInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
DeleteRecurringSilenceNotFoundBody delete recurring silence not found body
swagger:model DeleteRecurringSilenceNotFoundBody
*/
type DeleteRecurringSilenceNotFoundBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this delete recurring silence not found body
func (o *DeleteRecurringSilenceNotFoundBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this delete recurring silence not found body based on context it is used
func (o *DeleteRecurringSilenceNotFoundBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteRecurringSilenceNotFoundBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteRecurringSilenceNotFoundBody) UnmarshalBinary(b []byte) error {
	var res DeleteRecurringSilenceNotFoundBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
