// Code generated by go-swagger; DO NOT EDIT.

package monitors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/groundcover-com/groundcover-sdk-go/pkg/models"
)

// ExportMonitorsV2Reader is a Reader for the ExportMonitorsV2 structure.
type ExportMonitorsV2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExportMonitorsV2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewExportMonitorsV2OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewExportMonitorsV2BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewExportMonitorsV2InternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /api/v2/monitors/export] exportMonitorsV2", response, response.Code())
	}
}

// NewExportMonitorsV2OK creates a ExportMonitorsV2OK with default headers values
func NewExportMonitorsV2OK() *ExportMonitorsV2OK {
	return &ExportMonitorsV2OK{}
}

/*
ExportMonitorsV2OK describes a response with status code 200, with default header values.

ExportMonitorsV2ResponseWrapper is the HCL document, served as text/plain.
*/
type ExportMonitorsV2OK struct {
	Payload models.TerraformDocument
}

// IsSuccess returns true when this export monitors v2 o k response has a 2xx status code
func (o *ExportMonitorsV2OK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this export monitors v2 o k response has a 3xx status code
func (o *ExportMonitorsV2OK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this export monitors v2 o k response has a 4xx status code
func (o *ExportMonitorsV2OK) IsClientError() bool {
	return false
}

// IsServerError returns true when this export monitors v2 o k response has a 5xx status code
func (o *ExportMonitorsV2OK) IsServerError() bool {
	return false
}

// IsCode returns true when this export monitors v2 o k response a status code equal to that given
func (o *ExportMonitorsV2OK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the export monitors v2 o k response
func (o *ExportMonitorsV2OK) Code() int {
	return 200
}

func (o *ExportMonitorsV2OK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v2/monitors/export][%d] exportMonitorsV2OK %s", 200, payload)
}

func (o *ExportMonitorsV2OK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v2/monitors/export][%d] exportMonitorsV2OK %s", 200, payload)
}

func (o *ExportMonitorsV2OK) GetPayload() models.TerraformDocument {
	return o.Payload
}

func (o *ExportMonitorsV2OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewExportMonitorsV2BadRequest creates a ExportMonitorsV2BadRequest with default headers values
func NewExportMonitorsV2BadRequest() *ExportMonitorsV2BadRequest {
	return &ExportMonitorsV2BadRequest{}
}

/*
ExportMonitorsV2BadRequest describes a response with status code 400, with default header values.

ErrorResponse defines a common error response structure.
*/
type ExportMonitorsV2BadRequest struct {
	Payload *ExportMonitorsV2BadRequestBody
}

// IsSuccess returns true when this export monitors v2 bad request response has a 2xx status code
func (o *ExportMonitorsV2BadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this export monitors v2 bad request response has a 3xx status code
func (o *ExportMonitorsV2BadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this export monitors v2 bad request response has a 4xx status code
func (o *ExportMonitorsV2BadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this export monitors v2 bad request response has a 5xx status code
func (o *ExportMonitorsV2BadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this export monitors v2 bad request response a status code equal to that given
func (o *ExportMonitorsV2BadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the export monitors v2 bad request response
func (o *ExportMonitorsV2BadRequest) Code() int {
	return 400
}

func (o *ExportMonitorsV2BadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v2/monitors/export][%d] exportMonitorsV2BadRequest %s", 400, payload)
}

func (o *ExportMonitorsV2BadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v2/monitors/export][%d] exportMonitorsV2BadRequest %s", 400, payload)
}

func (o *ExportMonitorsV2BadRequest) GetPayload() *ExportMonitorsV2BadRequestBody {
	return o.Payload
}

func (o *ExportMonitorsV2BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(ExportMonitorsV2BadRequestBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewExportMonitorsV2InternalServerError creates a ExportMonitorsV2InternalServerError with default headers values
func NewExportMonitorsV2InternalServerError() *ExportMonitorsV2InternalServerError {
	return &ExportMonitorsV2InternalServerError{}
}

/*
ExportMonitorsV2InternalServerError describes a response with status code 500, with default header values.

ErrorResponse defines a common error response structure.
*/
type ExportMonitorsV2InternalServerError struct {
	Payload *ExportMonitorsV2InternalServerErrorBody
}

// IsSuccess returns true when this export monitors v2 internal server error response has a 2xx status code
func (o *ExportMonitorsV2InternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this export monitors v2 internal server error response has a 3xx status code
func (o *ExportMonitorsV2InternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this export monitors v2 internal server error response has a 4xx status code
func (o *ExportMonitorsV2InternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this export monitors v2 internal server error response has a 5xx status code
func (o *ExportMonitorsV2InternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this export monitors v2 internal server error response a status code equal to that given
func (o *ExportMonitorsV2InternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the export monitors v2 internal server error response
func (o *ExportMonitorsV2InternalServerError) Code() int {
	return 500
}

func (o *ExportMonitorsV2InternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v2/monitors/export][%d] exportMonitorsV2InternalServerError %s", 500, payload)
}

func (o *ExportMonitorsV2InternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v2/monitors/export][%d] exportMonitorsV2InternalServerError %s", 500, payload)
}

func (o *ExportMonitorsV2InternalServerError) GetPayload() *ExportMonitorsV2InternalServerErrorBody {
	return o.Payload
}

func (o *ExportMonitorsV2InternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(ExportMonitorsV2InternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
ExportMonitorsV2BadRequestBody export monitors v2 bad request body
swagger:model ExportMonitorsV2BadRequestBody
*/
type ExportMonitorsV2BadRequestBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this export monitors v2 bad request body
func (o *ExportMonitorsV2BadRequestBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this export monitors v2 bad request body based on context it is used
func (o *ExportMonitorsV2BadRequestBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *ExportMonitorsV2BadRequestBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ExportMonitorsV2BadRequestBody) UnmarshalBinary(b []byte) error {
	var res ExportMonitorsV2BadRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
ExportMonitorsV2InternalServerErrorBody export monitors v2 internal server error body
swagger:model ExportMonitorsV2InternalServerErrorBody
*/
type ExportMonitorsV2InternalServerErrorBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this export monitors v2 internal server error body
func (o *ExportMonitorsV2InternalServerErrorBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this export monitors v2 internal server error body based on context it is used
func (o *ExportMonitorsV2InternalServerErrorBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *ExportMonitorsV2InternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ExportMonitorsV2InternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res ExportMonitorsV2InternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
