// Code generated by go-swagger; DO NOT EDIT.

package monitors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/groundcover-com/groundcover-sdk-go/pkg/models"
)

// NewUpdateRecurringSilenceParams creates a new UpdateRecurringSilenceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateRecurringSilenceParams() *UpdateRecurringSilenceParams {
	return &UpdateRecurringSilenceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateRecurringSilenceParamsWithTimeout creates a new UpdateRecurringSilenceParams object
// with the ability to set a timeout on a request.
func NewUpdateRecurringSilenceParamsWithTimeout(timeout time.Duration) *UpdateRecurringSilenceParams {
	return &UpdateRecurringSilenceParams{
		timeout: timeout,
	}
}

// NewUpdateRecurringSilenceParamsWithContext creates a new UpdateRecurringSilenceParams object
// with the ability to set a context for a request.
func NewUpdateRecurringSilenceParamsWithContext(ctx context.Context) *UpdateRecurringSilenceParams {
	return &UpdateRecurringSilenceParams{
		Context: ctx,
	}
}

// NewUpdateRecurringSilenceParamsWithHTTPClient creates a new UpdateRecurringSilenceParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateRecurringSilenceParamsWithHTTPClient(client *http.Client) *UpdateRecurringSilenceParams {
	return &UpdateRecurringSilenceParams{
		HTTPClient: client,
	}
}

/*
UpdateRecurringSilenceParams contains all the parameters to send to the API endpoint

	for the update recurring silence operation.

	Typically these are written to a http.Request.
*/
type UpdateRecurringSilenceParams struct {

	// Body.
	Body *models.UpdateRecurringSilenceRequest

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update recurring silence params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateRecurringSilenceParams) WithDefaults() *UpdateRecurringSilenceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update recurring silence params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateRecurringSilenceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update recurring silence params
func (o *UpdateRecurringSilenceParams) WithTimeout(timeout time.Duration) *UpdateRecurringSilenceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update recurring silence params
func (o *UpdateRecurringSilenceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update recurring silence params
func (o *UpdateRecurringSilenceParams) WithContext(ctx context.Context) *UpdateRecurringSilenceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update recurring silence params
func (o *UpdateRecurringSilenceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update recurring silence params
func (o *UpdateRecurringSilenceParams) WithHTTPClient(client *http.Client) *UpdateRecurringSilenceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update recurring silence params
func (o *UpdateRecurringSilenceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update recurring silence params
func (o *UpdateRecurringSilenceParams) WithBody(body *models.UpdateRecurringSilenceRequest) *UpdateRecurringSilenceParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update recurring silence params
func (o *UpdateRecurringSilenceParams) SetBody(body *models.UpdateRecurringSilenceRequest) {
	o.Body = body
}

// WithID adds the id to the update recurring silence params
func (o *UpdateRecurringSilenceParams) WithID(id string) *UpdateRecurringSilenceParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update recurring silence params
func (o *UpdateRecurringSilenceParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateRecurringSilenceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
