// Code generated by go-swagger; DO NOT EDIT.

package monitors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/groundcover-com/groundcover-sdk-go/pkg/models"
)

// NewV2CreateSilenceParams creates a new V2CreateSilenceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewV2CreateSilenceParams() *V2CreateSilenceParams {
	return &V2CreateSilenceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewV2CreateSilenceParamsWithTimeout creates a new V2CreateSilenceParams object
// with the ability to set a timeout on a request.
func NewV2CreateSilenceParamsWithTimeout(timeout time.Duration) *V2CreateSilenceParams {
	return &V2CreateSilenceParams{
		timeout: timeout,
	}
}

// NewV2CreateSilenceParamsWithContext creates a new V2CreateSilenceParams object
// with the ability to set a context for a request.
func NewV2CreateSilenceParamsWithContext(ctx context.Context) *V2CreateSilenceParams {
	return &V2CreateSilenceParams{
		Context: ctx,
	}
}

// NewV2CreateSilenceParamsWithHTTPClient creates a new V2CreateSilenceParams object
// with the ability to set a custom HTTPClient for a request.
func NewV2CreateSilenceParamsWithHTTPClient(client *http.Client) *V2CreateSilenceParams {
	return &V2CreateSilenceParams{
		HTTPClient: client,
	}
}

/*
V2CreateSilenceParams contains all the parameters to send to the API endpoint

	for the v2 create silence operation.

	Typically these are written to a http.Request.
*/
type V2CreateSilenceParams struct {

	// Body.
	Body *models.V2CreateSilenceRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the v2 create silence params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *V2CreateSilenceParams) WithDefaults() *V2CreateSilenceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the v2 create silence params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *V2CreateSilenceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the v2 create silence params
func (o *V2CreateSilenceParams) WithTimeout(timeout time.Duration) *V2CreateSilenceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v2 create silence params
func (o *V2CreateSilenceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v2 create silence params
func (o *V2CreateSilenceParams) WithContext(ctx context.Context) *V2CreateSilenceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v2 create silence params
func (o *V2CreateSilenceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v2 create silence params
func (o *V2CreateSilenceParams) WithHTTPClient(client *http.Client) *V2CreateSilenceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v2 create silence params
func (o *V2CreateSilenceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the v2 create silence params
func (o *V2CreateSilenceParams) WithBody(body *models.V2CreateSilenceRequest) *V2CreateSilenceParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the v2 create silence params
func (o *V2CreateSilenceParams) SetBody(body *models.V2CreateSilenceRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *V2CreateSilenceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
