// Code generated by go-swagger; DO NOT EDIT.

package monitors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V2DeleteSilenceReader is a Reader for the V2DeleteSilence structure.
type V2DeleteSilenceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V2DeleteSilenceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewV2DeleteSilenceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewV2DeleteSilenceBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewV2DeleteSilenceNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewV2DeleteSilenceInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /api/monitors/v2/silences/{id}] v2DeleteSilence", response, response.Code())
	}
}

// NewV2DeleteSilenceOK creates a V2DeleteSilenceOK with default headers values
func NewV2DeleteSilenceOK() *V2DeleteSilenceOK {
	return &V2DeleteSilenceOK{}
}

/*
V2DeleteSilenceOK describes a response with status code 200, with default header values.

NoContentResponse indicates success but that no response body is expected or included.
*/
type V2DeleteSilenceOK struct {
}

// IsSuccess returns true when this v2 delete silence o k response has a 2xx status code
func (o *V2DeleteSilenceOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this v2 delete silence o k response has a 3xx status code
func (o *V2DeleteSilenceOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v2 delete silence o k response has a 4xx status code
func (o *V2DeleteSilenceOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this v2 delete silence o k response has a 5xx status code
func (o *V2DeleteSilenceOK) IsServerError() bool {
	return false
}

// IsCode returns true when this v2 delete silence o k response a status code equal to that given
func (o *V2DeleteSilenceOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the v2 delete silence o k response
func (o *V2DeleteSilenceOK) Code() int {
	return 200
}

func (o *V2DeleteSilenceOK) Error() string {
	return fmt.Sprintf("[DELETE /api/monitors/v2/silences/{id}][%d] v2DeleteSilenceOK", 200)
}

func (o *V2DeleteSilenceOK) String() string {
	return fmt.Sprintf("[DELETE /api/monitors/v2/silences/{id}][%d] v2DeleteSilenceOK", 200)
}

func (o *V2DeleteSilenceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewV2DeleteSilenceBadRequest creates a V2DeleteSilenceBadRequest with default headers values
func NewV2DeleteSilenceBadRequest() *V2DeleteSilenceBadRequest {
	return &V2DeleteSilenceBadRequest{}
}

/*
V2DeleteSilenceBadRequest describes a response with status code 400, with default header values.

ErrorResponse defines a common error response structure.
*/
type V2DeleteSilenceBadRequest struct {
	Payload *V2DeleteSilenceBadRequestBody
}

// IsSuccess returns true when this v2 delete silence bad request response has a 2xx status code
func (o *V2DeleteSilenceBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this v2 delete silence bad request response has a 3xx status code
func (o *V2DeleteSilenceBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v2 delete silence bad request response has a 4xx status code
func (o *V2DeleteSilenceBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this v2 delete silence bad request response has a 5xx status code
func (o *V2DeleteSilenceBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this v2 delete silence bad request response a status code equal to that given
func (o *V2DeleteSilenceBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the v2 delete silence bad request response
func (o *V2DeleteSilenceBadRequest) Code() int {
	return 400
}

func (o *V2DeleteSilenceBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/monitors/v2/silences/{id}][%d] v2DeleteSilenceBadRequest %s", 400, payload)
}

func (o *V2DeleteSilenceBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/monitors/v2/silences/{id}][%d] v2DeleteSilenceBadRequest %s", 400, payload)
}

func (o *V2DeleteSilenceBadRequest) GetPayload() *V2DeleteSilenceBadRequestBody {
	return o.Payload
}

func (o *V2DeleteSilenceBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(V2DeleteSilenceBadRequestBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewV2DeleteSilenceNotFound creates a V2DeleteSilenceNotFound with default headers values
func NewV2DeleteSilenceNotFound() *V2DeleteSilenceNotFound {
	return &V2DeleteSilenceNotFound{}
}

/*
V2DeleteSilenceNotFound describes a response with status code 404, with default header values.

ErrorResponse defines a common error response structure.
*/
type V2DeleteSilenceNotFound struct {
	Payload *V2DeleteSilenceNotFoundBody
}

// IsSuccess returns true when this v2 delete silence not found response has a 2xx status code
func (o *V2DeleteSilenceNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this v2 delete silence not found response has a 3xx status code
func (o *V2DeleteSilenceNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v2 delete silence not found response has a 4xx status code
func (o *V2DeleteSilenceNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this v2 delete silence not found response has a 5xx status code
func (o *V2DeleteSilenceNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this v2 delete silence not found response a status code equal to that given
func (o *V2DeleteSilenceNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the v2 delete silence not found response
func (o *V2DeleteSilenceNotFound) Code() int {
	return 404
}

func (o *V2DeleteSilenceNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/monitors/v2/silences/{id}][%d] v2DeleteSilenceNotFound %s", 404, payload)
}

func (o *V2DeleteSilenceNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/monitors/v2/silences/{id}][%d] v2DeleteSilenceNotFound %s", 404, payload)
}

func (o *V2DeleteSilenceNotFound) GetPayload() *V2DeleteSilenceNotFoundBody {
	return o.Payload
}

func (o *V2DeleteSilenceNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(V2DeleteSilenceNotFoundBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewV2DeleteSilenceInternalServerError creates a V2DeleteSilenceInternalServerError with default headers values
func NewV2DeleteSilenceInternalServerError() *V2DeleteSilenceInternalServerError {
	return &V2DeleteSilenceInternalServerError{}
}

/*
V2DeleteSilenceInternalServerError describes a response with status code 500, with default header values.

ErrorResponse defines a common error response structure.
*/
type V2DeleteSilenceInternalServerError struct {
	Payload *V2DeleteSilenceInternalServerErrorBody
}

// IsSuccess returns true when this v2 delete silence internal server error response has a 2xx status code
func (o *V2DeleteSilenceInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this v2 delete silence internal server error response has a 3xx status code
func (o *V2DeleteSilenceInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v2 delete silence internal server error response has a 4xx status code
func (o *V2DeleteSilenceInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this v2 delete silence internal server error response has a 5xx status code
func (o *V2DeleteSilenceInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this v2 delete silence internal server error response a status code equal to that given
func (o *V2DeleteSilenceInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the v2 delete silence internal server error response
func (o *V2DeleteSilenceInternalServerError) Code() int {
	return 500
}

func (o *V2DeleteSilenceInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/monitors/v2/silences/{id}][%d] v2DeleteSilenceInternalServerError %s", 500, payload)
}

func (o *V2DeleteSilenceInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/monitors/v2/silences/{id}][%d] v2DeleteSilenceInternalServerError %s", 500, payload)
}

func (o *V2DeleteSilenceInternalServerError) GetPayload() *V2DeleteSilenceInternalServerErrorBody {
	return o.Payload
}

func (o *V2DeleteSilenceInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(V2DeleteSilenceInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
V2DeleteSilenceBadRequestBody v2 delete silence bad request body
swagger:model V2DeleteSilenceBadRequestBody
*/
type V2DeleteSilenceBadRequestBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this v2 delete silence bad request body
func (o *V2DeleteSilenceBadRequestBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v2 delete silence bad request body based on context it is used
func (o *V2DeleteSilenceBadRequestBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *V2DeleteSilenceBadRequestBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *V2DeleteSilenceBadRequestBody) UnmarshalBinary(b []byte) error {
	var res V2DeleteSilenceBadRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
V2DeleteSilenceInternalServerErrorBody v2 delete silence internal server error body
swagger:model V2DeleteSilenceInternalServerErrorBody
*/
type V2DeleteSilenceInternalServerErrorBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this v2 delete silence internal server error body
func (o *V2DeleteSilenceInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v2 delete silence internal server error body based on context it is used
func (o *V2DeleteSilenceInternalServerErrorBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *V2DeleteSilenceInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *V2DeleteSilenceInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res V2DeleteSilenceInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
V2DeleteSilenceNotFoundBody v2 delete silence not found body
swagger:model V2DeleteSilenceNotFoundBody
*/
type V2DeleteSilenceNotFoundBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this v2 delete silence not found body
func (o *V2DeleteSilenceNotFoundBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v2 delete silence not found body based on context it is used
func (o *V2DeleteSilenceNotFoundBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *V2DeleteSilenceNotFoundBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *V2DeleteSilenceNotFoundBody) UnmarshalBinary(b []byte) error {
	var res V2DeleteSilenceNotFoundBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
