name: Release SDK
permissions:
  contents: write
  packages: write
concurrency:
  group: release-${{ github.workflow }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      commit_hash:
        description: 'Commit hash to release (default: latest)'
        required: false
        default: 'latest'
      isPatchVersion:
        description: 'Bump patch version instead of minor'
        required: false
        type: boolean
        default: false
      isMajorVersion:
        description: 'Bump major version instead of minor'
        required: false
        type: boolean
        default: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.24'

      - name: Download and Extract SDK
        env:
          COMMIT_HASH: ${{ github.event.inputs.commit_hash }}
        run: |
          # Clean up the SDK to only include the necessary files
          rm -rf pkg/client
          rm -rf pkg/models

          # Download the SDK
          FILE_URL="https://groundcover-openapi-sdk-bucket.s3.us-east-1.amazonaws.com/groundcover-sdk-${COMMIT_HASH}.tar.gz"
          echo "Downloading from ${FILE_URL}"
          curl -L -o groundcover-sdk.tar.gz "${FILE_URL}"
          tar -xzf groundcover-sdk.tar.gz
          # Verify SDK builds successfully
          go mod tidy
          rm groundcover-sdk.tar.gz

      - name: Commit Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          # Check if there are any changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update SDK to version from commit ${{ github.event.inputs.commit_hash }}"
            git push
          fi

      - name: Bump version and create tag
        id: version_bump
        run: |
          # Guardrail for input combinations
          if [ "${{ github.event.inputs.isMajorVersion }}" = "true" ] && [ "${{ github.event.inputs.isPatchVersion }}" = "true" ]; then
            echo "Error: Cannot set both isMajorVersion and isPatchVersion to true. Please choose only one type of bump or neither (for minor bump)."
            exit 1
          fi

          if [ ! -f VERSION ]; then
            echo "VERSION file not found. Creating with v1.0.0."
            NEW_VERSION="v1.0.0"
            # For the output, this indicates the state before this step's main action or the initial state.
            PREVIOUS_VERSION_INFO="N/A (file created with $NEW_VERSION)"
            echo "$NEW_VERSION" > VERSION
            echo "Set initial version to: $NEW_VERSION"
          else
            OLD_VERSION_FROM_FILE=$(cat VERSION)
            PREVIOUS_VERSION_INFO="$OLD_VERSION_FROM_FILE"
            echo "Current version from file: $OLD_VERSION_FROM_FILE"

            VERSION_NUM_NO_V=${OLD_VERSION_FROM_FILE#v} # Remove 'v' prefix
            IFS='.' read -r -a VERSION_PARTS <<< "$VERSION_NUM_NO_V"
            MAJOR=${VERSION_PARTS[0]:-0} # Default to 0 if empty
            MINOR=${VERSION_PARTS[1]:-0} # Default to 0 if empty
            PATCH=${VERSION_PARTS[2]:-0} # Default to 0 if empty

            # Decide which version part to bump based on inputs
            if [ "${{ github.event.inputs.isMajorVersion }}" = "true" ]; then
              echo "Bumping major version..."
              MAJOR=$((MAJOR + 1))
              MINOR=0
              PATCH=0
            elif [ "${{ github.event.inputs.isPatchVersion }}" = "true" ]; then
              echo "Bumping patch version..."
              PATCH=$((PATCH + 1))
              # Major and Minor remain unchanged
            else # Default: Bump minor version
              echo "Bumping minor version..."
              MINOR=$((MINOR + 1))
              PATCH=0
            fi

            NEW_VERSION="v${MAJOR}.${MINOR}.${PATCH}"

            echo "$NEW_VERSION" > VERSION
            echo "Bumped version to: $NEW_VERSION"
          fi

          # GitHub Actions outputs
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "current_version=$PREVIOUS_VERSION_INFO" >> $GITHUB_OUTPUT

          git add VERSION
          git commit -m "Bump version to ${NEW_VERSION}"
          git push
          git tag "${NEW_VERSION}"
          git push origin "${NEW_VERSION}"

      - name: Create GitHub Release (Preview)
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version_bump.outputs.new_version }}
          release_name: "Release ${{ steps.version_bump.outputs.new_version }}"
          body: |
            Automated release for version ${{ steps.version_bump.outputs.new_version }}.
            Released from commit: ${{ github.event.inputs.commit_hash }}
          draft: false
